#!/usr/bin/env php
<?php

use QtBuilder\Commands\DefineCommand;
use QtBuilder\Commands\DoctorCommand;
use QtBuilder\Commands\BuildCommand;
use QtBuilder\Commands\BuildInfoCommand;
use QtBuilder\Commands\BuildModulesCommand;
use QtBuilder\Commands\BuildDiscoverCommand;
use QtBuilder\Commands\ExampleCommand;
use QtBuilder\Commands\GenerateCommand;
use QtBuilder\Commands\InspectCommand;
use QtBuilder\UnixSystemInformation;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$systemInformation = new UnixSystemInformation();
$app = new Application('QT Builder', '0.1.0');

$app->addCommand(new DoctorCommand($systemInformation));
$app->addCommand(new InspectCommand($systemInformation));
$app->addCommand(new DefineCommand());
$app->addCommand(new GenerateCommand($systemInformation));
$app->addCommand(new BuildCommand($systemInformation));
$app->addCommand(new BuildInfoCommand());
$app->addCommand(new BuildModulesCommand($systemInformation));
$app->addCommand(new BuildDiscoverCommand($systemInformation));
$app->addCommand(new ExampleCommand());

$app->run();
