#!/usr/bin/env php
<?php

use QtBuilder\Commands\DoctorCommand;
use QtBuilder\UnixSystemInformation;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$systemInformation = new UnixSystemInformation();
$app = new Application('QT Builder', '0.1.0');

$app->addCommand(new DoctorCommand($systemInformation));

$app->run();
