@php
/** @var \QtBuilder\CodeGen\ClassContext $ctx */
@endphp
/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP wrapper implementation for {!! $ctx->nativeCppType !!}
 * Namespace: {!! $ctx->phpNamespace !!}\{!! $ctx->phpClassName !!}
 */

#include "{!! $ctx->filePrefix !!}.h"
#include "{!! $ctx->filePrefix !!}_arginfo.h"
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstring>
#include <filesystem>
#include <functional>
#include <memory>
#include <mutex>
#include <new>
#include <string>
#include <type_traits>
#include <unordered_set>
#include <utility>
#include <vector>
#include <QString>
#include <QByteArray>
#include <QVariant>
#include <QMetaType>
@if($ctx->nativeCppType === 'QString')
#include <Zend/zend_interfaces.h>
@endif
@if($ctx->hasQObjectPropertySupport())
#include <QMetaMethod>
#include <QMetaProperty>
@endif
@if($ctx->isQObjectClass && !$ctx->supportsRuntimeNotifyFunctorConnect)
#include <QSignalMapper>
@endif
@if($ctx->hasPreventDestroy || $ctx->hasSignals() || $ctx->hasPostCallOwnershipHandling())
#include <QObject>
@endif
@if($ctx->hasSignals())
#include "qt_qmetaobjectconnection.h"
#include <QCoreApplication>
#include <QMetaObject>
#include <QPointer>
#include <QThread>
@endif
@if($ctx->hasPreventDestroy && !$ctx->hasSignals())
#include <QCoreApplication>
@endif
@if($ctx->parentCeVarName && $ctx->parentFilePrefix)
#include "{!! $ctx->parentFilePrefix !!}.h"
@endif
@foreach($ctx->requiredIncludes as $include)
#include "{!! $include !!}"
@endforeach
@if($ctx->nativeCppType === 'QThread' || $ctx->isQObjectDerived)
#include "qt_qthreadruntime.h"
@endif
@if($ctx->nativeCppType === 'QObject')
#include "qt_qthread.h"
@endif

#include "qt_class_helpers.h"
@if($ctx->hasQObjectPropertySupport())
#include "qt_qobject_helpers.h"
@endif
@if($ctx->hasSignals())
#include "qt_signal_helpers.h"
@endif
@if($ctx->isQObjectClass)
#include "qt_qphpsignalconnection.h"
#include "qt_php_signal_helpers.h"
@elseif($ctx->isQObjectDerived)
#include "qt_php_signal_helpers.h"
@endif
@if($ctx->hasPreventDestroy || $ctx->hasPostCallOwnershipHandling())
#include "qt_ownership_helpers.h"
@endif

/* ------------------------------------------------------------------ */
/* Globals                                                             */
/* ------------------------------------------------------------------ */

zend_class_entry *{!! $ctx->ceVarName !!} = NULL;
zend_object_handlers {!! $ctx->handlersVarName !!};
@if($ctx->isQObjectDerived)
static zend_always_inline bool {!! $ctx->filePrefix !!}_is_moved_source_handle({!! $ctx->objectStructName !!} *intern)
{
    return intern != NULL && intern->moved_source && intern->moved_token != 0;
}

static zend_always_inline bool {!! $ctx->filePrefix !!}_moved_source_handle_is_alive({!! $ctx->objectStructName !!} *intern)
{
    return !{!! $ctx->filePrefix !!}_is_moved_source_handle(intern)
        || qt_qthreadruntime_moved_object_is_alive(intern->moved_token);
}

static void {!! $ctx->filePrefix !!}_throw_moved_source_unavailable(void)
{
    zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} moved object is no longer available.");
}

static void {!! $ctx->filePrefix !!}_throw_moved_source_method_error(const char *method_name)
{
    zend_throw_error(
        NULL,
        "{!! addslashes($ctx->phpClassName) !!}::%s() is unavailable on a moved source handle.",
        method_name != NULL ? method_name : "unknown"
    );
}

static void {!! $ctx->filePrefix !!}_throw_moved_source_property_error(zend_string *member, const char *operation)
{
    zend_throw_error(
        NULL,
        "{!! addslashes($ctx->phpClassName) !!}::$%s is unavailable on a moved source handle during %s.",
        member != NULL ? ZSTR_VAL(member) : "<unknown>",
        operation != NULL ? operation : "property access"
    );
}

static zend_always_inline bool {!! $ctx->filePrefix !!}_moved_source_method_allowed(const char *method_name)
{
    if (method_name == NULL) {
        return false;
    }

    return strcmp(method_name, "thread") == 0
        || strcmp(method_name, "objectName") == 0
        || strcmp(method_name, "property") == 0
        || strcmp(method_name, "signalsBlocked") == 0
        || strcmp(method_name, "dynamicPropertyNames") == 0
        || strcmp(method_name, "inherits") == 0
        || strcmp(method_name, "connectPropertyNotify") == 0;
}

static zend_always_inline bool {!! $ctx->filePrefix !!}_guard_moved_source_method(
    {!! $ctx->objectStructName !!} *intern,
    const char *method_name,
    bool allow_on_moved_source
)
{
    if (!{!! $ctx->filePrefix !!}_is_moved_source_handle(intern)) {
        return true;
    }

    if (!{!! $ctx->filePrefix !!}_moved_source_handle_is_alive(intern)) {
        {!! $ctx->filePrefix !!}_throw_moved_source_unavailable();
        return false;
    }

    if (allow_on_moved_source || {!! $ctx->filePrefix !!}_moved_source_method_allowed(method_name)) {
        return true;
    }

    {!! $ctx->filePrefix !!}_throw_moved_source_method_error(method_name);
    return false;
}

static zend_always_inline bool {!! $ctx->filePrefix !!}_guard_moved_source_property(
    {!! $ctx->objectStructName !!} *intern,
    zend_string *member,
    const char *operation
)
{
    if (!{!! $ctx->filePrefix !!}_is_moved_source_handle(intern)) {
        return true;
    }

    if (!{!! $ctx->filePrefix !!}_moved_source_handle_is_alive(intern)) {
        {!! $ctx->filePrefix !!}_throw_moved_source_unavailable();
        return false;
    }

    {!! $ctx->filePrefix !!}_throw_moved_source_property_error(member, operation);
    return false;
}
@endif
@if($ctx->nativeCppType === 'QObject')
static zend_always_inline bool qt_qobject_php_receiver_method_info(
    zend_object *receiver_object,
    const QByteArray &method_signature,
    std::string *method_name_out,
    uint32_t *required_args_out,
    uint32_t *accepted_args_out,
    uint32_t *signature_args_out,
    std::string *error
)
{
    if (receiver_object == NULL || receiver_object->ce == NULL) {
        if (error != NULL) {
            *error = "Receiver PHP object is not initialized.";
        }
        return false;
    }

    const int open_paren = method_signature.indexOf('(');
    if (open_paren <= 0) {
        if (error != NULL) {
            *error = "Receiver method signature must be normalized like doWork().";
        }
        return false;
    }

    QByteArray method_name = method_signature.left(open_paren);
    QByteArray argument_segment = method_signature.mid(open_paren + 1, method_signature.size() - open_paren - 2);
    uint32_t signature_args = 0;
    if (!argument_segment.isEmpty()) {
        signature_args = 1;
        for (const char ch : argument_segment) {
            if (ch == ',') {
                signature_args++;
            }
        }
    }
    zend_function *method = qt_lookup_method(receiver_object->ce, method_name.constData());
    if (method == NULL) {
        if (error != NULL) {
            *error = std::string("Unknown receiver method ") + method_signature.constData() + ".";
        }
        return false;
    }

    if ((method->common.fn_flags & ZEND_ACC_STATIC) != 0) {
        if (error != NULL) {
            *error = std::string("Receiver method ") + method_signature.constData() + " must be an instance method.";
        }
        return false;
    }

    if (method_name_out != NULL) {
        *method_name_out = method_name.toStdString();
    }
    if (required_args_out != NULL) {
        *required_args_out = method->common.required_num_args;
    }
    if (accepted_args_out != NULL) {
        *accepted_args_out = method->common.num_args;
    }
    if (signature_args_out != NULL) {
        *signature_args_out = signature_args;
    }

    return true;
}
@endif
@if($ctx->hasSignals() && $ctx->isQObjectDerived)
@foreach($ctx->signalOverloads as $signal)
@php
$bridgeName = sprintf('%s_php_receiver_bridge_%d', $ctx->filePrefix, $loop->index);
$lambdaParams = [];
$setupLines = [];
$teardownLines = [];
$paramCount = count($signal->params);
foreach ($signal->params as $index => $param) {
    $nativeVar = sprintf('_qt_arg_%d', $index);
    $lambdaParams[] = $param->cppType . ' ' . $nativeVar;
    $setupLines[] = $ctx->typeBridge->signalArgToZvalBlock(
        sprintf('&_qt_params[%d]', $index),
        $param->phpType,
        $param->cppType,
        $nativeVar,
        $index,
    );
    $teardownLines[] = sprintf('zval_ptr_dtor(&_qt_params[%d]);', $index);
}
@endphp
static QMetaObject::Connection {!! $bridgeName !!}(
    QObject *sender_object,
    QObject *receiver_object,
    zend_object *source_receiver_object,
    const std::string &method_name,
    int signal_index,
    Qt::ConnectionType connection_type
)
{
    auto *typed_sender = dynamic_cast<{!! $ctx->nativeCppType !!} *>(sender_object);
    if (typed_sender == NULL || receiver_object == NULL) {
        return QMetaObject::Connection();
    }

    auto state = std::make_shared<qt_qobject_php_receiver_invocation_state>(
        sender_object,
        receiver_object,
        source_receiver_object,
        method_name,
        signal_index
    );

    return QObject::connect(
        typed_sender,
        {!! $signal->memberPointerExpr !!},
        receiver_object,
        [state]({!! implode(', ', $lambdaParams) !!}) mutable {
            if (!state) {
                return;
            }
@if($paramCount > 0)
            zval _qt_params[{!! $paramCount !!}];
@foreach($setupLines as $line)
            {!! $line !!}
@endforeach
            state->invoke_marshaled({!! $paramCount !!}, _qt_params);
@foreach($teardownLines as $line)
            {!! $line !!}
@endforeach
@else
            state->invoke();
@endif
        },
        connection_type
    );
}

@endforeach
@endif
@if($ctx->hasQObjectPropertySupport())
static zval *{!! $ctx->filePrefix !!}_read_property(zend_object *object, zend_string *member, int type, void **cache_slot, zval *rv)
{
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->fromObjFunc !!}(object);
@if($ctx->isQObjectDerived)
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_property(intern, member, "read")) {
        return &EG(uninitialized_zval);
    }
@endif
    if (qt_qobject_should_delegate_to_std_property(object, member)) {
        return zend_std_read_property(object, member, type, cache_slot, rv);
    }

    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        return &EG(uninitialized_zval);
    }

    if (qt_qobject_read_property_mixed(_qt_obj, member, rv)) {
        return rv;
    }

    return zend_std_read_property(object, member, type, cache_slot, rv);
}

static zval *{!! $ctx->filePrefix !!}_write_property(zend_object *object, zend_string *member, zval *value, void **cache_slot)
{
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->fromObjFunc !!}(object);
@if($ctx->isQObjectDerived)
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_property(intern, member, "write")) {
        return &EG(uninitialized_zval);
    }
@endif
    if (qt_qobject_should_delegate_to_std_property(object, member)) {
        return zend_std_write_property(object, member, value, cache_slot);
    }

    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        return &EG(uninitialized_zval);
    }

    if (!qt_qobject_write_property_mixed(_qt_obj, member, value, NULL)) {
        return &EG(uninitialized_zval);
    }

    return value;
}

static zval *{!! $ctx->filePrefix !!}_get_property_ptr_ptr(zend_object *object, zend_string *member, int type, void **cache_slot)
{
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->fromObjFunc !!}(object);
@if($ctx->isQObjectDerived)
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_property(intern, member, "indirect access")) {
        return NULL;
    }
@endif
    if (qt_qobject_should_delegate_to_std_property(object, member)) {
        return zend_std_get_property_ptr_ptr(object, member, type, cache_slot);
    }

    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj != NULL && qt_qobject_has_property_name(_qt_obj, member)) {
        return NULL;
    }

    return zend_std_get_property_ptr_ptr(object, member, type, cache_slot);
}

static int {!! $ctx->filePrefix !!}_has_property(zend_object *object, zend_string *member, int has_set_exists, void **cache_slot)
{
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->fromObjFunc !!}(object);
@if($ctx->isQObjectDerived)
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_property(intern, member, has_set_exists == ZEND_PROPERTY_EXISTS ? "isset" : "empty")) {
        return 0;
    }
@endif
    if (qt_qobject_should_delegate_to_std_property(object, member)) {
        return zend_std_has_property(object, member, has_set_exists, cache_slot);
    }

    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        return zend_std_has_property(object, member, has_set_exists, cache_slot);
    }

    if (!qt_qobject_has_property_name(_qt_obj, member)) {
        return zend_std_has_property(object, member, has_set_exists, cache_slot);
    }

    if (has_set_exists == ZEND_PROPERTY_EXISTS) {
        return 1;
    }

    zval rv;
    ZVAL_NULL(&rv);
    if (!qt_qobject_read_property_mixed(_qt_obj, member, &rv)) {
        return 0;
    }

    const int _qt_result = (has_set_exists == ZEND_PROPERTY_NOT_EMPTY)
        ? zend_is_true(&rv)
        : (Z_TYPE(rv) != IS_NULL);
    zval_ptr_dtor(&rv);

    return _qt_result;
}

static zend_array *{!! $ctx->filePrefix !!}_get_properties_for(zend_object *object, zend_prop_purpose purpose)
{
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->fromObjFunc !!}(object);
@if($ctx->isQObjectDerived)
    if ({!! $ctx->filePrefix !!}_is_moved_source_handle(intern)) {
        return zend_new_array(0);
    }
@endif
    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    zend_array *_qt_props = zend_std_get_properties_for(object, purpose);
    if (_qt_obj == NULL) {
        return _qt_props;
    }

    std::unordered_set<std::string> _qt_seen;

    if (_qt_props == NULL) {
        _qt_props = zend_new_array(8);
    } else {
        zend_string *_qt_existing_key;
        zval *_qt_existing_value;
        ZEND_HASH_FOREACH_STR_KEY_VAL(_qt_props, _qt_existing_key, _qt_existing_value) {
            (void) _qt_existing_value;
            if (_qt_existing_key != NULL) {
                _qt_seen.insert(std::string(ZSTR_VAL(_qt_existing_key), ZSTR_LEN(_qt_existing_key)));
            }
        } ZEND_HASH_FOREACH_END();
    }

    const QMetaObject *_qt_meta = _qt_obj->metaObject();
    const int _qt_meta_count = _qt_meta->propertyCount();
    for (int _qt_i = 0; _qt_i < _qt_meta_count; ++_qt_i) {
        auto _qt_property = _qt_meta->property(_qt_i);
        const char *_qt_name = _qt_property.name();
        if (_qt_name == NULL || *_qt_name == '\0') {
            continue;
        }

        std::string _qt_key(_qt_name);
        if (!_qt_seen.insert(_qt_key).second) {
            continue;
        }

        zval _qt_value;
        ZVAL_NULL(&_qt_value);
        zend_string *_qt_member = zend_string_init(_qt_name, strlen(_qt_name), 0);
        if (qt_qobject_read_property_mixed(_qt_obj, _qt_member, &_qt_value)) {
            zend_hash_update(_qt_props, _qt_member, &_qt_value);
        } else {
            zval_ptr_dtor(&_qt_value);
        }
        zend_string_release(_qt_member);
    }

    const QList<QByteArray> _qt_dynamic_names = _qt_obj->dynamicPropertyNames();
    for (const QByteArray &_qt_name : _qt_dynamic_names) {
        std::string _qt_key(_qt_name.constData(), (size_t) _qt_name.size());
        if (!_qt_seen.insert(_qt_key).second) {
            continue;
        }

        zval _qt_value;
        ZVAL_NULL(&_qt_value);
        zend_string *_qt_member = zend_string_init(_qt_name.constData(), _qt_name.size(), 0);
        if (qt_qobject_read_property_mixed(_qt_obj, _qt_member, &_qt_value)) {
            zend_hash_update(_qt_props, _qt_member, &_qt_value);
        } else {
            zval_ptr_dtor(&_qt_value);
        }
        zend_string_release(_qt_member);
    }

    return _qt_props;
}

@endif

@if($ctx->requiresAccessShim)
/* ------------------------------------------------------------------ */
/* Protected access shim                                               */
/* ------------------------------------------------------------------ */

class {!! $ctx->accessShimTypeName !!} : public {!! $ctx->nativeCppType !!}
{
public:
    using {!! $ctx->nativeCtorOwnerType !!}::{!! $ctx->nativeCtorName !!};
@if($ctx->nativeCppType === 'QThread')

    inline void qt_set_task_runtime_host(void *host)
    {
        qt_task_runtime_host_ = host;
    }

    void run() override
    {
        if (qt_task_runtime_host_ != NULL) {
            auto *_qt_host = static_cast<qt_qthread_task_host *>(qt_task_runtime_host_);
            if (qt_qthread_task_host_execute_pending(_qt_host, this)) {
                return;
            }

            if (qt_qthread_task_host_enter_moved_runtime(_qt_host, this)) {
                if (qt_qthread_task_host_is_moved_runtime_active(_qt_host)) {
                    this->QThread::run();
                    qt_qthread_task_host_leave_moved_runtime(_qt_host);
                }
                return;
            }
        }

        this->QThread::run();
    }

private:
    void *qt_task_runtime_host_{NULL};

public:
@endif

@foreach($ctx->methodsWithCallableProtectedOverloads() as $method)
@foreach($method->overloads as $overloadIndex => $overload)
@if($overload->access === 'protected' && !$overload->isPureVirtual)
@php
    $paramDecls = [];
    $paramArgs = [];
    foreach ($overload->params as $paramIndex => $param) {
        $paramVar = sprintf('_qt_p%d', $paramIndex);
        $paramDecls[] = sprintf(
            '%s %s',
            $ctx->typeBridge->accessShimBoundaryType($param->phpType, $param->cppType),
            $paramVar,
        );
        $paramArgs[] = $ctx->typeBridge->accessShimBoundaryExpr($param->phpType, $param->cppType, $paramVar);
    }
    $declaringClass = $overload->declaringClass !== '' ? $overload->declaringClass : $ctx->nativeCppType;
    $helperReturnType = $ctx->typeBridge->accessShimBoundaryType($overload->phpReturnType, $overload->cppReturnType, true);
    $helperSignature = implode(', ', $paramDecls);
    $helperArgs = implode(', ', $paramArgs);
    $helperCall = $overload->isStatic
        ? sprintf('%s::%s(%s)', $declaringClass, $method->cppName, $helperArgs)
        : sprintf('this->%s::%s(%s)', $declaringClass, $method->cppName, $helperArgs);
    $helperConst = !$overload->isStatic && $overload->isConst ? ' const' : '';
    $helperPrefix = $overload->isStatic ? 'static inline ' : 'inline ';
@endphp
    {!! $helperPrefix !!}{!! $helperReturnType !!} {!! $method->accessShimHelperName($overloadIndex) !!}({!! $helperSignature !!}){!! $helperConst !!}
    {
@if($overload->returnStrategy === 'void')
        {!! $helperCall !!};
@else
        return {!! $ctx->typeBridge->accessShimBoundaryReturnExpr($overload->phpReturnType, $overload->cppReturnType, $helperCall) !!};
@endif
    }

@endif
@endforeach
@endforeach
};

@endif
@if($ctx->requiresVirtualTrampoline)
/* ------------------------------------------------------------------ */
/* Native virtual trampoline                                           */
/* ------------------------------------------------------------------ */

class {!! $ctx->trampolineTypeName !!} : public @if($ctx->requiresAccessShim){!! $ctx->accessShimTypeName !!}@else{!! $ctx->nativeCppType !!}@endif
{
public:
@php
    $trampolineBaseType = $ctx->requiresAccessShim ? $ctx->accessShimTypeName : $ctx->nativeCppType;
@endphp
    template <typename... Args>
    explicit {!! $ctx->trampolineTypeName !!}(Args&&... args)
        : {!! $trampolineBaseType !!}(std::forward<Args>(args)...)
    {
    }

    zend_object *php_object = nullptr;
    mutable bool qt_override_cache_initialized = false;
@foreach($ctx->virtualDispatchCacheEntries() as $entry)
    mutable bool {!! $entry['field'] !!} = false;
@endforeach

    inline void qt_cache_virtual_overrides(zend_class_entry *actual_ce, zend_class_entry *base_ce) const
    {
        if (this->qt_override_cache_initialized) {
            return;
        }

        this->qt_override_cache_initialized = true;
        if (actual_ce == NULL || base_ce == NULL || actual_ce == base_ce) {
            return;
        }

@foreach($ctx->virtualDispatchCacheEntries() as $entry)
        this->{!! $entry['field'] !!} = qt_method_is_overridden_in_ce(actual_ce, base_ce, "{!! $entry['method'] !!}");
@endforeach
    }

@foreach($ctx->virtualMethods() as $method)
@foreach($method->overloads as $overloadIndex => $overload)
@if($overload->isVirtual || $overload->isPureVirtual)
@php
    $paramDecls = [];
    $paramArgs = [];
    $dispatchCaptures = ['this'];
    foreach ($overload->params as $paramIndex => $param) {
        $paramDecls[] = sprintf('%s _qt_p%d', $param->cppType, $paramIndex);
        $paramArgs[] = sprintf('_qt_p%d', $paramIndex);
        $dispatchCaptures[] = sprintf('&_qt_p%d', $paramIndex);
    }
    $overrideSignature = implode(', ', $paramDecls);
    $overrideArgs = implode(', ', $paramArgs);
    $dispatchCaptureList = implode(', ', $dispatchCaptures);
    $declaringClass = $overload->declaringClass !== '' ? $overload->declaringClass : $ctx->nativeCppType;
    $constQualifier = $overload->isConst ? ' const' : '';
    $baseCall = sprintf('%s::%s(%s)', $declaringClass, $method->cppName, $overrideArgs);
    $returnSetup = $ctx->typeBridge->nativeReturnFromZvalSetup($overload->phpReturnType, $overload->cppReturnType, '&_qt_retval', '_qt_native_return');
@endphp
@if($method->access === 'protected')
protected:
@else
public:
@endif
    {!! $overload->cppReturnType !!} {!! $method->cppName !!}({!! $overrideSignature !!}){!! $constQualifier !!} override
    {
@php
    $entryMap = [];
    foreach ($ctx->virtualDispatchCacheEntries() as $entry) {
        $entryMap[$entry['method']] = $entry['field'];
    }
    $overrideField = $entryMap[$method->name] ?? null;
@endphp
        if (!qt_runtime_can_call_zend()) {
            bool _qt_dispatched = false;
            constexpr zend_long _qt_virtual_timeout_ms = 2000;
@if($overload->returnStrategy === 'void')
            _qt_dispatched = qt_runtime_dispatch_owner_sync([{!! $dispatchCaptureList !!}]() mutable {
                this->{!! $method->cppName !!}({!! $overrideArgs !!});
            }, _qt_virtual_timeout_ms);
            if (_qt_dispatched) {
                return;
            }
@else
            {!! $overload->cppReturnType !!} _qt_dispatch_result = {!! $ctx->typeBridge->defaultNativeReturnExpr($overload->phpReturnType, $overload->cppReturnType) !!};
            _qt_dispatched = qt_runtime_dispatch_owner_sync([{!! $dispatchCaptureList !!}, &_qt_dispatch_result]() mutable {
                _qt_dispatch_result = this->{!! $method->cppName !!}({!! $overrideArgs !!});
            }, _qt_virtual_timeout_ms);
            if (_qt_dispatched) {
                return _qt_dispatch_result;
            }
@endif
@if($overload->isPureVirtual)
@if($overload->returnStrategy === 'void')
            return;
@else
            return {!! $ctx->typeBridge->defaultNativeReturnExpr($overload->phpReturnType, $overload->cppReturnType) !!};
@endif
@else
@if($overload->returnStrategy === 'void')
            {!! $baseCall !!};
            return;
@else
            return {!! $baseCall !!};
@endif
@endif
        }

        if (this->php_object == nullptr) {
            zend_throw_error(NULL, "Missing PHP object for {!! addslashes($ctx->phpClassName) !!}::{!! $method->name !!}() virtual dispatch.");
@if($overload->returnStrategy === 'void')
            return;
@else
            return {!! $ctx->typeBridge->defaultNativeReturnExpr($overload->phpReturnType, $overload->cppReturnType) !!};
@endif
        }

        if (!this->qt_override_cache_initialized) {
            this->qt_cache_virtual_overrides(this->php_object->ce, {!! $ctx->ceVarName !!});
        }

        if (!this->{!! $overrideField !!}) {
@if($overload->isPureVirtual)
            zend_throw_error(NULL, "Pure virtual method {!! addslashes($ctx->phpClassName) !!}::{!! $method->name !!}() must be overridden in PHP.");
@if($overload->returnStrategy === 'void')
            return;
@else
            return {!! $ctx->typeBridge->defaultNativeReturnExpr($overload->phpReturnType, $overload->cppReturnType) !!};
@endif
@else
@if($overload->returnStrategy === 'void')
            {!! $baseCall !!};
            return;
@else
            return {!! $baseCall !!};
@endif
@endif
        }

        zval _qt_retval;
        ZVAL_NULL(&_qt_retval);
@if(count($overload->params) > 0)
        zval _qt_params[{!! count($overload->params) !!}];
@foreach($overload->params as $paramIndex => $param)
        {!! $ctx->typeBridge->signalArgToZvalBlock(sprintf('&_qt_params[%d]', $paramIndex), $param->phpType, $param->cppType, sprintf('_qt_p%d', $paramIndex), $paramIndex) !!}
@endforeach
        if (!qt_call_php_method(this->php_object, "{!! $method->name !!}", &_qt_retval, {!! count($overload->params) !!}, _qt_params)) {
@else
        if (!qt_call_php_method(this->php_object, "{!! $method->name !!}", &_qt_retval, 0, NULL)) {
@endif
            zval_ptr_dtor(&_qt_retval);
@foreach($overload->params as $paramIndex => $param)
        zval_ptr_dtor(&_qt_params[{!! $paramIndex !!}]);
@endforeach
@if($overload->isPureVirtual)
            zend_throw_error(NULL, "Pure virtual method {!! addslashes($ctx->phpClassName) !!}::{!! $method->name !!}() failed during PHP override dispatch.");
@if($overload->returnStrategy === 'void')
            return;
@else
            return {!! $ctx->typeBridge->defaultNativeReturnExpr($overload->phpReturnType, $overload->cppReturnType) !!};
@endif
@else
@if($overload->returnStrategy === 'void')
            {!! $baseCall !!};
            return;
@else
            return {!! $baseCall !!};
@endif
@endif
        }

@foreach($returnSetup['lines'] as $line)
        {!! $line !!}
@endforeach
@if($overload->returnStrategy === 'void')
        zval_ptr_dtor(&_qt_retval);
@foreach($overload->params as $paramIndex => $param)
        zval_ptr_dtor(&_qt_params[{!! $paramIndex !!}]);
@endforeach
        return;
@else
        auto _qt_native_result = {!! $returnSetup['expr'] !!};
@foreach($returnSetup['cleanup_lines'] as $line)
        {!! $line !!}
@endforeach
        zval_ptr_dtor(&_qt_retval);
@foreach($overload->params as $paramIndex => $param)
        zval_ptr_dtor(&_qt_params[{!! $paramIndex !!}]);
@endforeach
        return _qt_native_result;
@endif
    }

@endif
@endforeach
@endforeach
};

static void {!! $ctx->filePrefix !!}_rebind_php_object(void *native_ptr, zend_object *php_object, zend_class_entry *actual_ce)
{
    if (native_ptr == NULL) {
        return;
    }

    auto *_qt_trampoline = static_cast<{!! $ctx->trampolineTypeName !!} *>(native_ptr);
    _qt_trampoline->php_object = php_object;
    _qt_trampoline->qt_override_cache_initialized = false;
@foreach($ctx->virtualDispatchCacheEntries() as $entry)
    _qt_trampoline->{!! $entry['field'] !!} = false;
@endforeach

    if (php_object != NULL) {
        _qt_trampoline->qt_cache_virtual_overrides(actual_ce != NULL ? actual_ce : php_object->ce, {!! $ctx->ceVarName !!});
    }
}

@endif

/* ------------------------------------------------------------------ */
/* create_object                                                       */
/* ------------------------------------------------------------------ */

static zend_object *{!! $ctx->filePrefix !!}_create_object(zend_class_entry *ce)
{
    {!! $ctx->objectStructName !!} *intern = ({!! $ctx->objectStructName !!} *)zend_object_alloc(
        sizeof({!! $ctx->objectStructName !!}), ce
    );
    intern->native_ptr = NULL;
@if($ctx->tracksGeneratedNativeSubclass)
    intern->native_is_generated_subclass = false;
@if($ctx->requiresVirtualTrampoline)
    intern->native_is_virtual_trampoline = false;
@endif
@endif
@if($ctx->hasPreventDestroy)
    intern->prevent_destroy = false;
    intern->extra_storage = NULL;
@endif
@if($ctx->isQObjectDerived)
    intern->moved_source = false;
    intern->moved_token = 0;
@endif
@if($ctx->needsArgvStorage)
    intern->extra_storage = new {!! $ctx->argvStorageStructName !!}();
@endif
@if($ctx->nativeCppType === 'QThread')
    intern->extra_storage = qt_qthread_task_host_create();
@endif
    intern->native_rebind_php_object = NULL;

    zend_object_std_init(&intern->std, ce);
    object_properties_init(&intern->std, ce);

    return &intern->std;
}

/* ------------------------------------------------------------------ */
/* free_obj                                                            */
/* ------------------------------------------------------------------ */

static void {!! $ctx->filePrefix !!}_free_object(zend_object *object)
{
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->fromObjFunc !!}(object);
@if($ctx->isQObjectDerived)
    if (intern->native_ptr != NULL) {
        qt_php_signal_unregister_live_wrapper(static_cast<QObject *>(intern->native_ptr), object);
    }
@endif
@if($ctx->isQObjectDerived)
    if (intern->moved_token != 0) {
        intern->moved_token = 0;
    }
    intern->moved_source = false;
@endif

@if($ctx->nativeCppType === 'QThread')
    if (intern->extra_storage != NULL) {
        qt_qthread_task_host_destroy(static_cast<qt_qthread_task_host *>(intern->extra_storage));
        intern->extra_storage = NULL;
    }
@endif

@if($ctx->hasPreventDestroy)
@if($ctx->hasPublicDestructor && $ctx->hasConstructibleConstructor)
    if (qt_should_delete_native(intern->native_ptr, intern->prevent_destroy)) {
@if($ctx->tracksGeneratedNativeSubclass)
        if (intern->native_is_generated_subclass) {
@if($ctx->requiresVirtualTrampoline)
            if (intern->native_is_virtual_trampoline) {
                qt_delete_native_ptr(static_cast<{!! $ctx->trampolineTypeName !!} *>(intern->native_ptr));
            } else {
@if($ctx->plainInstantiationUsesGeneratedType())
                qt_delete_native_ptr(static_cast<{!! $ctx->plainNativeInstantiationType !!} *>(intern->native_ptr));
@else
                qt_delete_native_ptr(intern->native_ptr);
@endif
            }
        } else {
            qt_delete_native_ptr(intern->native_ptr);
        }
@else
            qt_delete_native_ptr(static_cast<{!! $ctx->plainNativeInstantiationType !!} *>(intern->native_ptr));
        } else {
            qt_delete_native_ptr(intern->native_ptr);
        }
@endif
@else
        qt_delete_native_ptr(intern->native_ptr);
@endif
    }
@endif
@else
@if($ctx->hasPublicDestructor && $ctx->hasConstructibleConstructor)
    if (intern->native_ptr) {
@if($ctx->tracksGeneratedNativeSubclass)
        if (intern->native_is_generated_subclass) {
@if($ctx->requiresVirtualTrampoline)
            if (intern->native_is_virtual_trampoline) {
                qt_delete_native_ptr(static_cast<{!! $ctx->trampolineTypeName !!} *>(intern->native_ptr));
            } else {
@if($ctx->plainInstantiationUsesGeneratedType())
                qt_delete_native_ptr(static_cast<{!! $ctx->plainNativeInstantiationType !!} *>(intern->native_ptr));
@else
                qt_delete_native_ptr(intern->native_ptr);
@endif
            }
        } else {
            qt_delete_native_ptr(intern->native_ptr);
        }
@else
            qt_delete_native_ptr(static_cast<{!! $ctx->plainNativeInstantiationType !!} *>(intern->native_ptr));
        } else {
            qt_delete_native_ptr(intern->native_ptr);
        }
@endif
@else
        qt_delete_native_ptr(intern->native_ptr);
@endif
    }
@endif
@endif
    intern->native_ptr = NULL;
@if($ctx->needsArgvStorage)
    if (intern->extra_storage != NULL) {
        delete static_cast<{!! $ctx->argvStorageStructName !!} *>(intern->extra_storage);
        intern->extra_storage = NULL;
    }
@endif

    zend_object_std_dtor(&intern->std);
}

@if($ctx->isCloneable)
/* ------------------------------------------------------------------ */
/* clone_obj                                                           */
/* ------------------------------------------------------------------ */

static zend_object *{!! $ctx->filePrefix !!}_clone_object(zend_object *old_object)
{
    {!! $ctx->objectStructName !!} *old_intern = {!! $ctx->fromObjFunc !!}(old_object);
@if($ctx->isQObjectDerived)
    if ({!! $ctx->filePrefix !!}_is_moved_source_handle(old_intern)) {
        if (!{!! $ctx->filePrefix !!}_moved_source_handle_is_alive(old_intern)) {
            {!! $ctx->filePrefix !!}_throw_moved_source_unavailable();
        } else {
            zend_throw_error(NULL, "Cannot clone a moved source handle of {!! addslashes($ctx->phpClassName) !!}.");
        }
        return NULL;
    }
@endif
    zend_object *new_obj = {!! $ctx->filePrefix !!}_create_object(old_object->ce);
    {!! $ctx->objectStructName !!} *new_intern = {!! $ctx->fromObjFunc !!}(new_obj);

    if (old_intern->native_ptr) {
        new_intern->native_ptr = new {!! $ctx->nativeCppType !!}(*old_intern->native_ptr);
    }

    zend_objects_clone_members(new_obj, old_object);

    return new_obj;
}

@endif
/* ------------------------------------------------------------------ */
/* get_gc                                                              */
/* ------------------------------------------------------------------ */

static HashTable *{!! $ctx->filePrefix !!}_get_gc(zend_object *object, zval **table, int *n)
{
    *table = NULL;
    *n = 0;
    return zend_std_get_properties(object);
}

@if($ctx->wrapNativeFunc)
/* ------------------------------------------------------------------ */
/* wrap_native                                                         */
/* ------------------------------------------------------------------ */

PHP_QT_API void {!! $ctx->wrapNativeFunc !!}(zval *return_value, {!! $ctx->nativeCppType !!} *native,
    zend_class_entry *ce, bool prevent_destroy)
{
    if (!native) {
        ZVAL_NULL(return_value);
        return;
    }

    if (!ce) {
        ce = {!! $ctx->ceVarName !!};
    }

    object_init_ex(return_value, ce);
    if (UNEXPECTED(Z_TYPE_P(return_value) != IS_OBJECT)) {
        if (!EG(exception)) {
            zend_throw_error(NULL, "Failed to instantiate PHP wrapper for {!! addslashes($ctx->phpClassName) !!}");
        }
        return;
    }
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(return_value);
    intern->native_ptr = native;
    qt_track_native_instance(intern->native_ptr);
@if($ctx->isQObjectDerived)
    qt_runtime_try_hook_about_to_quit();
@endif
    intern->prevent_destroy = prevent_destroy;
    intern->native_rebind_php_object = NULL;
@if($ctx->isQObjectDerived)
    intern->moved_source = false;
    intern->moved_token = 0;
@endif
@if($ctx->tracksGeneratedNativeSubclass)
    intern->native_is_generated_subclass = false;
@if($ctx->requiresVirtualTrampoline)
    intern->native_is_virtual_trampoline = false;
@endif
@endif
}

@endif
@if($ctx->nativeCppType === 'QObject')
static void qt_qobject_wrap_runtime_adapter(zval *return_value, QObject *native, bool prevent_destroy)
{
    {!! $ctx->wrapNativeFunc !!}(return_value, static_cast<QObject *>(native), {!! $ctx->ceVarName !!}, prevent_destroy);
}
@elseif($ctx->isQObjectDerived && $ctx->wrapNativeFunc)
static void {!! $ctx->filePrefix !!}_wrap_runtime_adapter(zval *return_value, QObject *native, bool prevent_destroy)
{
    {!! $ctx->wrapNativeFunc !!}(return_value, static_cast<{!! $ctx->nativeCppType !!} *>(native), {!! $ctx->ceVarName !!}, prevent_destroy);
}
@endif
@if($ctx->isQObjectDerived)
static QObject *{!! $ctx->filePrefix !!}_extract_native_adapter(zend_object *object)
{
    if (object == NULL) {
        return NULL;
    }

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->fromObjFunc !!}(object);
    return intern != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
}
@endif
/* ==================================================================
 * Method implementations
 * ================================================================== */

@foreach($ctx->methods as $method)
@if($method->isConstructor)
@include('generation.method.constructor', ['ctx' => $ctx, 'method' => $method])
@elseif($method->isAbstractMethod)
@elseif($method->isOverloaded)
@include('generation.method.overloaded', ['ctx' => $ctx, 'method' => $method])
@else
@include('generation.method.simple', ['ctx' => $ctx, 'method' => $method])
@endif
@endforeach
@if($ctx->nativeCppType === 'QString')

/* __toString */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, __toString)
{
    ZEND_PARSE_PARAMETERS_NONE();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (intern->native_ptr == NULL) {
        RETURN_EMPTY_STRING();
    }

    QByteArray _qt_utf8 = intern->native_ptr->toUtf8();
    RETURN_STRINGL(_qt_utf8.constData(), _qt_utf8.size());
}

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX({!! $ctx->filePrefix !!}_arginfo___tostring, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

@endif
@if($ctx->isQObjectClass)

/* property */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, property)
{
    zend_string *name;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(name)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "property", true)) {
        RETURN_THROWS();
    }
    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

    if (!qt_qobject_read_property_mixed(_qt_obj, name, return_value)) {
        RETURN_NULL();
    }
}

/* setProperty */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, setProperty)
{
    zend_string *name;
    zval *value;
    bool _qt_result = false;

    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_STR(name)
        Z_PARAM_ZVAL(value)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "setProperty", false)) {
        RETURN_THROWS();
    }
    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

    if (!qt_qobject_write_property_mixed(_qt_obj, name, value, &_qt_result)) {
        RETURN_THROWS();
    }

    RETURN_BOOL(_qt_result);
}

/* hasProperty */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, hasProperty)
{
    zend_string *name;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(name)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "hasProperty", false)) {
        RETURN_THROWS();
    }
    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

    RETURN_BOOL(qt_qobject_has_property_name(_qt_obj, name));
}

/* propertyNames */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, propertyNames)
{
    ZEND_PARSE_PARAMETERS_NONE();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "propertyNames", false)) {
        RETURN_THROWS();
    }
    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

    qt_qobject_property_names(_qt_obj, return_value);
}

/* propertyInfo */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, propertyInfo)
{
    zend_string *name;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(name)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "propertyInfo", false)) {
        RETURN_THROWS();
    }
    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

    if (!qt_qobject_property_info(_qt_obj, name, return_value)) {
        zend_value_error("Unknown property %s.", ZSTR_VAL(name));
        RETURN_THROWS();
    }
}

/* connectPropertyNotify */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, connectPropertyNotify)
{
    zend_string *name;
    zval *callback;

    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_STR(name)
        Z_PARAM_ZVAL(callback)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "connectPropertyNotify", true)) {
        RETURN_THROWS();
    }
    QObject *_qt_obj = intern->native_ptr != NULL ? static_cast<QObject *>(intern->native_ptr) : NULL;
    if (_qt_obj == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

    if (qt_qobject_meta_property_index(_qt_obj, name) < 0) {
        if (qt_qobject_has_dynamic_property(_qt_obj, name)) {
            zend_value_error("Dynamic property %s does not provide a NOTIFY signal.", ZSTR_VAL(name));
        } else {
            zend_value_error("Unknown property %s.", ZSTR_VAL(name));
        }
        RETURN_THROWS();
    }

    const int _qt_property_index = qt_qobject_meta_property_index(_qt_obj, name);
    auto _qt_property = _qt_obj->metaObject()->property(_qt_property_index);
    auto _qt_notify = _qt_property.notifySignal();
    if (!_qt_notify.isValid()) {
        zend_value_error("Property %s does not provide a NOTIFY signal.", ZSTR_VAL(name));
        RETURN_THROWS();
    }

    auto _qt_callback = qt_signal_callback_create(_qt_obj, callback);
    if (_qt_callback == nullptr) {
        RETURN_THROWS();
    }

    struct _qt_property_notify_handler_t {
        std::shared_ptr<qt_signal_callback_t> callback;

        void operator()() const
        {
            auto _qt_callback_copy = callback;
            qt_signal_dispatch(_qt_callback_copy, [_qt_callback_copy]() mutable {
                qt_signal_callback_invoke(_qt_callback_copy, 0, nullptr);
            });
        }
    };

@if($ctx->supportsRuntimeNotifyFunctorConnect)
    QMetaObject::Connection _qt_connection = QMetaObject::connect(
        _qt_obj,
        _qt_notify,
        _qt_obj,
        _qt_property_notify_handler_t{_qt_callback}
    );

    qt_qmetaobjectconnection_wrap(return_value, _qt_connection);
@else
    QSignalMapper *_qt_mapper = new QSignalMapper();
    _qt_mapper->setMapping(_qt_obj, _qt_obj);

    const QMetaObject &_qt_mapper_meta = QSignalMapper::staticMetaObject;
    const int _qt_map_index = _qt_mapper_meta.indexOfSlot("map()");
    const int _qt_mapped_index = _qt_mapper_meta.indexOfSignal("mappedObject(QObject*)");
    if (_qt_map_index < 0 || _qt_mapped_index < 0) {
        delete _qt_mapper;
        zend_throw_error(NULL, "QSignalMapper bridge methods are unavailable for connectPropertyNotify().");
        RETURN_THROWS();
    }

    const QMetaMethod _qt_map_method = _qt_mapper_meta.method(_qt_map_index);
    QMetaObject::Connection _qt_connection = QObject::connect(
        _qt_obj,
        _qt_notify,
        _qt_mapper,
        _qt_map_method
    );
    if (!_qt_connection) {
        delete _qt_mapper;
        zend_throw_error(NULL, "Failed to connect property notify bridge for property %s.", ZSTR_VAL(name));
        RETURN_THROWS();
    }

    QMetaObject::Connection _qt_bridge_connection = QObject::connect(
        _qt_mapper,
        qOverload<QObject *>(&QSignalMapper::mappedObject),
        _qt_obj,
        [_qt_handler = _qt_property_notify_handler_t{_qt_callback}](QObject *) {
            _qt_handler();
        }
    );
    if (!_qt_bridge_connection) {
        QObject::disconnect(_qt_connection);
        delete _qt_mapper;
        zend_throw_error(NULL, "Failed to connect property notify callback bridge for property %s.", ZSTR_VAL(name));
        RETURN_THROWS();
    }

    qt_qmetaobjectconnection_wrap_aux(
        return_value,
        _qt_connection,
        qt_qmetaobjectconnection_create_bridge_aux(_qt_mapper, _qt_bridge_connection)
    );
@endif
}
@endif
@if($ctx->hasSignals())

@if($ctx->isQObjectClass)
/* on */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, on)
{
    qt_runtime_owner_safe_point();

    zend_string *signal_name = NULL;
    zval *listener = NULL;
    zend_string *method_name = NULL;

    ZEND_PARSE_PARAMETERS_START(2, 3)
        Z_PARAM_STR(signal_name)
        Z_PARAM_ZVAL(listener)
        Z_PARAM_OPTIONAL
        Z_PARAM_STR_OR_NULL(method_name)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
@if($ctx->isQObjectDerived)
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "on", true)) {
        RETURN_THROWS();
    }
@endif
    if (intern->native_ptr == NULL) {
        zend_throw_error(NULL, "QObject native instance is not initialized");
        RETURN_THROWS();
    }
    if (ZSTR_LEN(signal_name) == 0) {
        zend_argument_value_error(1, "must be a non-empty signal name");
        RETURN_THROWS();
    }

    const bool _qt_use_task_listener_api =
        qt_ce_qthread != NULL && instanceof_function(Z_OBJCE_P(ZEND_THIS), qt_ce_qthread);

    if (_qt_use_task_listener_api && !qt_php_signal_has_declared_signal(Z_OBJCE_P(ZEND_THIS), signal_name)) {
        if (method_name != NULL) {
            zend_argument_value_error(3, "must be omitted for QThread task listeners");
            RETURN_THROWS();
        }
#if !defined(ZTS)
        zend_throw_exception_ex(
            qt_runtime_exception_ce(),
            0,
            "Qt\\Core\\QThread::on() requires a ZTS PHP build (thread start/management APIs are unavailable on NTS)."
        );
        RETURN_THROWS();
#else
        if (intern->extra_storage == NULL) {
            zend_throw_error(NULL, "QThread task runtime host is not initialized.");
            RETURN_THROWS();
        }

        uint64_t listener_id = 0;
        std::string task_error;
        if (!qt_qthread_task_host_on(
            static_cast<qt_qthread_task_host *>(intern->extra_storage),
            std::string(ZSTR_VAL(signal_name), ZSTR_LEN(signal_name)),
            listener,
            &listener_id,
            &task_error
        )) {
            zend_throw_error(NULL, "%s", task_error.c_str());
            RETURN_THROWS();
        }

        RETURN_LONG((zend_long) listener_id);
#endif
    }

    uint64_t sender_token = 0;
    uint64_t listener_id = 0;
    uint64_t generation = 0;
    std::string error;
    QObject *sender_native = static_cast<QObject *>(intern->native_ptr);

    if (method_name == NULL) {
        char *callable_error = NULL;
        zend_fcall_info callable_fci;
        zend_fcall_info_cache callable_fcc;
        if (zend_fcall_info_init(listener, 0, &callable_fci, &callable_fcc, NULL, &callable_error) != SUCCESS) {
            zend_argument_type_error(2, "must be callable or a QObject receiver when method is provided");
            if (callable_error != NULL) {
                efree(callable_error);
            }
            RETURN_THROWS();
        }
        if (callable_error != NULL) {
            efree(callable_error);
        }

        if (!qt_php_signal_register_callable_listener(
            Z_OBJCE_P(ZEND_THIS),
            sender_native,
            signal_name,
            listener,
            &sender_token,
            &listener_id,
            &generation,
            &error
        )) {
            zend_throw_error(NULL, "%s", error.c_str());
            RETURN_THROWS();
        }
    } else {
        if (Z_TYPE_P(listener) != IS_OBJECT || !instanceof_function(Z_OBJCE_P(listener), qt_ce_qobject)) {
            zend_argument_type_error(2, "must be of type Qt\\Core\\QObject when method is provided");
            RETURN_THROWS();
        }

        qt_qobject_object *receiver_intern = qt_qobject_from_obj(Z_OBJ_P(listener));
        QObject *receiver_native = receiver_intern != NULL
            ? static_cast<QObject *>(receiver_intern->native_ptr)
            : NULL;
        if (receiver_native == NULL) {
            zend_throw_error(NULL, "QObject receiver native instance is not initialized");
            RETURN_THROWS();
        }

        if (!qt_php_signal_register_receiver_listener(
            Z_OBJCE_P(ZEND_THIS),
            sender_native,
            signal_name,
            receiver_native,
            Z_OBJ_P(listener),
            method_name,
            &sender_token,
            &listener_id,
            &generation,
            &error
        )) {
            zend_throw_error(NULL, "%s", error.c_str());
            RETURN_THROWS();
        }
    }

    qt_qphpsignalconnection_wrap(return_value, sender_token, listener_id, generation);
}

/* off */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, off)
{
    zval *connection = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_ZVAL(connection)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
@if($ctx->isQObjectDerived)
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "off", true)) {
        RETURN_THROWS();
    }
@endif

    if (Z_TYPE_P(connection) == IS_OBJECT && instanceof_function(Z_OBJCE_P(connection), qt_ce_QPhpSignalConnection)) {
        RETURN_BOOL(qt_qphpsignalconnection_disconnect(Z_QPHPSIGNALCONNECTION_P(connection)));
    }

    const bool _qt_use_task_listener_api =
        qt_ce_qthread != NULL && instanceof_function(Z_OBJCE_P(ZEND_THIS), qt_ce_qthread);

    if (_qt_use_task_listener_api) {
        if (Z_TYPE_P(connection) != IS_LONG) {
            zend_argument_type_error(1, "must be of type int|Qt\\Core\\QPhpSignalConnection");
            RETURN_THROWS();
        }

#if !defined(ZTS)
        zend_throw_exception_ex(
            qt_runtime_exception_ce(),
            0,
            "Qt\\Core\\QThread::off() requires a ZTS PHP build (thread start/management APIs are unavailable on NTS)."
        );
        RETURN_THROWS();
#else
        if (intern->extra_storage == NULL) {
            RETURN_FALSE;
        }

        RETURN_BOOL(qt_qthread_task_host_off(
            static_cast<qt_qthread_task_host *>(intern->extra_storage),
            (uint64_t) zval_get_long(connection)
        ));
#endif
    }

    zend_argument_type_error(1, "must be of type Qt\\Core\\QPhpSignalConnection");
    RETURN_THROWS();
}

/* emit */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, emit)
{
    qt_runtime_owner_safe_point();

    zend_string *signal_name = NULL;
    zval *args = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(signal_name)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY(args)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
@if($ctx->isQObjectDerived)
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "emit", false)) {
        RETURN_THROWS();
    }
@endif
    if (intern->native_ptr == NULL) {
        zend_throw_error(NULL, "QObject native instance is not initialized");
        RETURN_THROWS();
    }
    if (ZSTR_LEN(signal_name) == 0) {
        zend_argument_value_error(1, "must be a non-empty signal name");
        RETURN_THROWS();
    }

    zval local_args;
    if (args != NULL) {
        ZVAL_COPY(&local_args, args);
    } else {
        array_init(&local_args);
    }

    std::string error;
    const bool emitted = qt_php_signal_emit(
        Z_OBJCE_P(ZEND_THIS),
        static_cast<QObject *>(intern->native_ptr),
        signal_name,
        &local_args,
        &error
    );
    zval_ptr_dtor(&local_args);

    if (!emitted) {
        zend_throw_error(NULL, "%s", error.c_str());
        RETURN_THROWS();
    }

    return;
}
@if($ctx->nativeCppType === 'QObject')
/* connect */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, connect)
{
    zval *sender_zv;
    zend_string *signal_signature = NULL;
    zval *receiver_zv;
    zend_string *method_signature = NULL;
    zend_long connection_type = (zend_long) Qt::AutoConnection;

    ZEND_PARSE_PARAMETERS_START(4, 5)
        Z_PARAM_OBJECT_OF_CLASS(sender_zv, {!! $ctx->ceVarName !!})
        Z_PARAM_STR(signal_signature)
        Z_PARAM_OBJECT_OF_CLASS(receiver_zv, {!! $ctx->ceVarName !!})
        Z_PARAM_STR(method_signature)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(connection_type)
    ZEND_PARSE_PARAMETERS_END();

    qt_qobject_object *sender_intern = qt_qobject_from_obj(Z_OBJ_P(sender_zv));
    qt_qobject_object *receiver_intern = qt_qobject_from_obj(Z_OBJ_P(receiver_zv));
    if (sender_intern->native_ptr == NULL) {
        zend_throw_error(NULL, "QObject sender native instance is not initialized");
        RETURN_THROWS();
    }
    if (receiver_intern->native_ptr == NULL) {
        zend_throw_error(NULL, "QObject receiver native instance is not initialized");
        RETURN_THROWS();
    }

    QByteArray _qt_signal_signature;
    std::string _qt_signal_error;
    if (!qt_qobject_normalize_signature(signal_signature, &_qt_signal_signature, &_qt_signal_error, "Signal signature")) {
        zend_throw_error(NULL, "%s", _qt_signal_error.c_str());
        RETURN_THROWS();
    }

    QByteArray _qt_method_signature;
    std::string _qt_method_error;
    if (!qt_qobject_normalize_signature(method_signature, &_qt_method_signature, &_qt_method_error, "Receiver method signature")) {
        zend_throw_error(NULL, "%s", _qt_method_error.c_str());
        RETURN_THROWS();
    }

    QObject *_qt_sender = static_cast<QObject *>(sender_intern->native_ptr);
    QObject *_qt_receiver = static_cast<QObject *>(receiver_intern->native_ptr);

    const QMetaObject *_qt_sender_meta = _qt_sender->metaObject();
    const int _qt_signal_index = _qt_sender_meta->indexOfSignal(_qt_signal_signature.constData());
    if (_qt_signal_index < 0) {
        zend_throw_error(NULL, "Unknown signal signature for QObject::connect(): %s", _qt_signal_signature.constData());
        RETURN_THROWS();
    }

    const QMetaMethod _qt_signal_method = _qt_sender_meta->method(_qt_signal_index);

    const QMetaObject *_qt_receiver_meta = _qt_receiver->metaObject();
    const int _qt_receiver_method_index = _qt_receiver_meta->indexOfMethod(_qt_method_signature.constData());
    if (_qt_receiver_method_index >= 0) {
        const QMetaMethod _qt_receiver_method = _qt_receiver_meta->method(_qt_receiver_method_index);
        if (!QMetaObject::checkConnectArgs(_qt_signal_method, _qt_receiver_method)) {
            zend_throw_error(
                NULL,
                "Incompatible signal/receiver method signatures for QObject::connect(): %s -> %s",
                _qt_signal_signature.constData(),
                _qt_method_signature.constData()
            );
            RETURN_THROWS();
        }

        QMetaObject::Connection _qt_connection = QObject::connect(
            _qt_sender,
            _qt_signal_method,
            _qt_receiver,
            _qt_receiver_method,
            static_cast<Qt::ConnectionType>(connection_type)
        );
        if (!_qt_connection) {
            zend_throw_error(NULL, "Failed to connect %s to native receiver method %s.", _qt_signal_signature.constData(), _qt_method_signature.constData());
            RETURN_THROWS();
        }

        qt_qmetaobjectconnection_wrap(return_value, _qt_connection);
        return;
    }

    std::string _qt_receiver_method_name;
    uint32_t _qt_required_args = 0;
    uint32_t _qt_accepted_args = 0;
    uint32_t _qt_signature_args = 0;
    std::string _qt_php_method_error;
    if (!qt_qobject_php_receiver_method_info(
        &receiver_intern->std,
        _qt_method_signature,
        &_qt_receiver_method_name,
        &_qt_required_args,
        &_qt_accepted_args,
        &_qt_signature_args,
        &_qt_php_method_error
    )) {
        zend_throw_error(NULL, "%s", _qt_php_method_error.c_str());
        RETURN_THROWS();
    }

    const int _qt_signal_parameter_count = _qt_signal_method.parameterCount();
    if (_qt_required_args > (uint32_t) _qt_signal_parameter_count) {
        zend_throw_error(
            NULL,
            "Receiver method %s requires %u argument(s), but signal %s provides %d.",
            _qt_method_signature.constData(),
            (unsigned) _qt_required_args,
            _qt_signal_signature.constData(),
            _qt_signal_parameter_count
        );
        RETURN_THROWS();
    }

    if (_qt_signature_args < _qt_required_args || _qt_signature_args > _qt_accepted_args) {
        zend_throw_error(
            NULL,
            "Receiver method signature %s does not match PHP method arity for %s().",
            _qt_method_signature.constData(),
            _qt_receiver_method_name.c_str()
        );
        RETURN_THROWS();
    }

    if (_qt_signature_args > (uint32_t) _qt_signal_parameter_count) {
        zend_throw_error(
            NULL,
            "Receiver method %s expects %u delivered argument(s), but signal %s provides %d.",
            _qt_method_signature.constData(),
            (unsigned) _qt_signature_args,
            _qt_signal_signature.constData(),
            _qt_signal_parameter_count
        );
        RETURN_THROWS();
    }

    qt_qobject_php_receiver_connect_bridge_t _qt_connect_bridge = qt_qobject_lookup_php_receiver_connect_bridge(
        _qt_sender,
        _qt_signal_signature
    );
    if (_qt_connect_bridge == NULL) {
        zend_throw_error(
            NULL,
            "Signal %s does not have a generated public PHP receiver bridge for sender class %s.",
            _qt_signal_signature.constData(),
            _qt_sender->metaObject()->className()
        );
        RETURN_THROWS();
    }

    QMetaObject::Connection _qt_connection = _qt_connect_bridge(
        _qt_sender,
        _qt_receiver,
        &receiver_intern->std,
        _qt_receiver_method_name,
        _qt_signal_index,
        static_cast<Qt::ConnectionType>(connection_type)
    );
    if (!_qt_connection) {
        zend_throw_error(NULL, "Failed to connect %s to PHP receiver method %s.", _qt_signal_signature.constData(), _qt_method_signature.constData());
        RETURN_THROWS();
    }

    qt_qmetaobjectconnection_wrap(return_value, _qt_connection);
}

/* disconnect */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, disconnect)
{
    zval *connection;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_OBJECT_OF_CLASS(connection, qt_ce_QMetaObjectConnection)
    ZEND_PARSE_PARAMETERS_END();

    qt_qmetaobjectconnection_object *connection_intern = qt_qmetaobjectconnection_from_obj(Z_OBJ_P(connection));
    if (connection_intern->native_ptr == NULL) {
        RETURN_FALSE;
    }

    RETURN_BOOL(qt_qmetaobjectconnection_disconnect(connection_intern));
}
@endif
@endif

@foreach($ctx->signalOverloads as $signal)
/* {!! $signal->phpMethodName !!} */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, {!! $signal->phpMethodName !!})
{
    zval *callback;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_ZVAL(callback)
    ZEND_PARSE_PARAMETERS_END();

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (!{!! $ctx->filePrefix !!}_guard_moved_source_method(intern, "{!! $signal->phpMethodName !!}", true)) {
        RETURN_THROWS();
    }
    if (intern->native_ptr == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

@include('generation.method.signal_bind', ['ctx' => $ctx, 'signal' => $signal])
}

@endforeach
@endif
@if($ctx->nativeCppType === 'QThread')
/* drainEvents */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, drainEvents)
{
    zend_long max_items = -1;
    ZEND_PARSE_PARAMETERS_START(0, 1)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(max_items)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_exception_ex(
        qt_runtime_exception_ce(),
        0,
        "Qt\\Core\\QThread::drainEvents() requires a ZTS PHP build (thread start/management APIs are unavailable on NTS)."
    );
    RETURN_THROWS();
#else
    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (intern->extra_storage == NULL) {
        RETURN_LONG(0);
    }

    RETURN_LONG(qt_qthread_task_host_drain_events(
        static_cast<qt_qthread_task_host *>(intern->extra_storage),
        max_items
    ));
#endif
}

/* send */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, send)
{
    zend_string *event_name = NULL;
    zval *payload = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(event_name)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY(payload)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_exception_ex(
        qt_runtime_exception_ce(),
        0,
        "Qt\\Core\\QThread::send() requires a ZTS PHP build (thread start/management APIs are unavailable on NTS)."
    );
    RETURN_THROWS();
#else
    if (ZSTR_LEN(event_name) == 0) {
        zend_argument_value_error(1, "must be a non-empty event name");
        RETURN_THROWS();
    }

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (intern->extra_storage == NULL) {
        RETURN_FALSE;
    }

    zval _qt_payload;
    if (payload != NULL) {
        ZVAL_COPY(&_qt_payload, payload);
    } else {
        array_init(&_qt_payload);
    }

    std::string error;
    bool ok = qt_qthread_task_host_send(
        static_cast<qt_qthread_task_host *>(intern->extra_storage),
        std::string(ZSTR_VAL(event_name), ZSTR_LEN(event_name)),
        &_qt_payload,
        &error
    );
    zval_ptr_dtor(&_qt_payload);

    if (!ok && !error.empty()) {
        zend_throw_error(NULL, "%s", error.c_str());
        RETURN_THROWS();
    }

    RETURN_BOOL(ok);
#endif
}

/* startFuture */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, startFuture)
{
    qt_runtime_owner_safe_point();

#if !defined(ZTS)
    zend_throw_exception_ex(
        qt_runtime_exception_ce(),
        0,
        "Qt\\Core\\QThread::startFuture() requires a ZTS PHP build (thread start/management APIs are unavailable on NTS)."
    );
    RETURN_THROWS();
#else
    zend_string *callable = NULL;
    zval *args = NULL;
    zval *priority = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 3)
        Z_PARAM_STR(callable)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY(args)
        Z_PARAM_ZVAL(priority)
    ZEND_PARSE_PARAMETERS_END();

    if (ZSTR_LEN(callable) == 0) {
        zend_argument_value_error(1, "must be a non-empty callable string");
        RETURN_THROWS();
    }

    bool has_priority = false;
    int priority_value = 0;
    if (priority != NULL && Z_TYPE_P(priority) != IS_NULL) {
        if (Z_TYPE_P(priority) != IS_LONG) {
            zend_argument_type_error(3, "must be of type ?int when provided");
            RETURN_THROWS();
        }
        has_priority = true;
        priority_value = (int) zval_get_long(priority);
    }

    {!! $ctx->objectStructName !!} *intern = {!! $ctx->zMacro !!}(ZEND_THIS);
    if (intern->native_ptr == NULL) {
        zend_throw_error(NULL, "{!! addslashes($ctx->phpClassName) !!} native instance is not initialized");
        RETURN_THROWS();
    }

    if (!intern->native_is_generated_subclass || intern->native_is_virtual_trampoline) {
        zend_throw_error(NULL, "QThread task mode requires a non-overridden generated QThread instance.");
        RETURN_THROWS();
    }

    if (intern->extra_storage == NULL) {
        zend_throw_error(NULL, "QThread task runtime host is not initialized.");
        RETURN_THROWS();
    }

    zval args_input;
    if (args != NULL) {
        ZVAL_COPY(&args_input, args);
    } else {
        array_init(&args_input);
    }

    std::string args_payload;
    std::string args_error;
    bool args_ok = qt_qthreadruntime_serialize_worker_args(&args_input, &args_payload, &args_error);
    zval_ptr_dtor(&args_input);
    if (!args_ok) {
        zend_argument_value_error(2, "%s", args_error.c_str());
        RETURN_THROWS();
    }

    std::string callable_error;
    if (!qt_qthreadruntime_validate_callable_string(callable, &callable_error)) {
        zend_argument_value_error(1, "%s", callable_error.c_str());
        RETURN_THROWS();
    }

    uint64_t task_token = 0;
    std::string start_error;
    if (!qt_qthread_task_host_start_future(
        static_cast<qt_qthread_task_host *>(intern->extra_storage),
        intern->native_ptr,
        std::string(ZSTR_VAL(callable), ZSTR_LEN(callable)),
        args_payload,
        has_priority,
        priority_value,
        &task_token,
        &start_error
    )) {
        zend_throw_error(NULL, "%s", start_error.c_str());
        RETURN_THROWS();
    }

    qt_qfuture_wrap(return_value, static_cast<qt_qthread_task_host *>(intern->extra_storage), task_token);
#endif
}

/* publish */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, publish)
{
    zend_string *event_name = NULL;
    zval *payload = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(event_name)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY(payload)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_exception_ex(
        qt_runtime_exception_ce(),
        0,
        "Qt\\Core\\QThread::publish() requires a ZTS PHP build (thread start/management APIs are unavailable on NTS)."
    );
    RETURN_THROWS();
#else
    std::string error;
    if (!qt_qthreadruntime_worker_publish_zval(event_name, payload, &error)) {
        if (!error.empty()) {
            zend_throw_error(NULL, "%s", error.c_str());
            RETURN_THROWS();
        }
        RETURN_FALSE;
    }

    RETURN_TRUE;
#endif
}

/* receive */
ZEND_METHOD({!! $ctx->zendClassSymbol !!}, receive)
{
    zend_long timeout_ms = 0;
    ZEND_PARSE_PARAMETERS_START(0, 1)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout_ms)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_exception_ex(
        qt_runtime_exception_ce(),
        0,
        "Qt\\Core\\QThread::receive() requires a ZTS PHP build (thread start/management APIs are unavailable on NTS)."
    );
    RETURN_THROWS();
#else
    bool has_message = false;
    std::string error;
    if (!qt_qthreadruntime_worker_receive_zval(timeout_ms, return_value, &has_message, &error)) {
        if (!error.empty()) {
            zend_throw_error(NULL, "%s", error.c_str());
            RETURN_THROWS();
        }
        RETURN_NULL();
    }

    if (!has_message) {
        RETURN_NULL();
    }
#endif
}

@endif

/* ------------------------------------------------------------------ */
/* Function entry table                                                */
/* ------------------------------------------------------------------ */

static const zend_function_entry {!! $ctx->filePrefix !!}_methods[] = {
@foreach($ctx->methods as $method)
@if($method->isAbstractMethod)
    ZEND_RAW_FENTRY("{!! $method->name !!}", NULL, {!! $method->arginfoName !!}, {!! $method->accessFlags !!} | ZEND_ACC_ABSTRACT, NULL, NULL)
@else
    ZEND_ME({!! $ctx->zendClassSymbol !!}, {!! $method->name !!}, {!! $method->arginfoName !!}, {!! $method->accessFlags !!})
@endif
@endforeach
@if($ctx->nativeCppType === 'QString')
    ZEND_ME({!! $ctx->zendClassSymbol !!}, __toString, {!! $ctx->filePrefix !!}_arginfo___tostring, ZEND_ACC_PUBLIC)
@endif
@if($ctx->isQObjectClass)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, on, {!! $ctx->phpSignalOnArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, off, {!! $ctx->phpSignalOffArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, emit, {!! $ctx->phpSignalEmitArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, property, {!! $ctx->propertyArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, setProperty, {!! $ctx->setPropertyArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, hasProperty, {!! $ctx->hasPropertyArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, propertyNames, {!! $ctx->propertyNamesArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, propertyInfo, {!! $ctx->propertyInfoArginfoName !!}, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, connectPropertyNotify, {!! $ctx->connectPropertyNotifyArginfoName !!}, ZEND_ACC_PUBLIC)
@if($ctx->nativeCppType === 'QObject')
    ZEND_ME({!! $ctx->zendClassSymbol !!}, connect, {!! $ctx->signalConnectArginfoName !!}, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, disconnect, {!! $ctx->signalDisconnectArginfoName !!}, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
@endif
@endif
@if($ctx->hasSignals())
@foreach($ctx->signalOverloads as $signal)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, {!! $signal->phpMethodName !!}, {!! $signal->arginfoName !!}, ZEND_ACC_PUBLIC)
@endforeach
@endif
@if($ctx->nativeCppType === 'QThread')
    ZEND_ME({!! $ctx->zendClassSymbol !!}, drainEvents, arginfo_class_Qt_Core_QThread_drainEvents, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, send, arginfo_class_Qt_Core_QThread_send, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, startFuture, arginfo_class_Qt_Core_QThread_startFuture, ZEND_ACC_PUBLIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, publish, arginfo_class_Qt_Core_QThread_publish, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME({!! $ctx->zendClassSymbol !!}, receive, arginfo_class_Qt_Core_QThread_receive, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
@endif
    ZEND_FE_END
};

/* ------------------------------------------------------------------ */
/* MINIT                                                               */
/* ------------------------------------------------------------------ */

PHP_MINIT_FUNCTION({!! $ctx->minitName !!})
{
    zend_class_entry ce;
    INIT_NS_CLASS_ENTRY(ce, "{!! $ctx->initNsString !!}", "{!! $ctx->phpClassName !!}", {!! $ctx->filePrefix !!}_methods);

    ce.create_object = {!! $ctx->filePrefix !!}_create_object;

@if($ctx->parentCeVarName)
    {!! $ctx->ceVarName !!} = zend_register_internal_class_ex(&ce, {!! $ctx->parentCeVarName !!});
@else
    {!! $ctx->ceVarName !!} = zend_register_internal_class(&ce);
@endif
    {!! $ctx->ceVarName !!}->create_object = {!! $ctx->filePrefix !!}_create_object;
@if($ctx->nativeCppType === 'QString')
    zend_class_implements({!! $ctx->ceVarName !!}, 1, zend_ce_stringable);
@endif

@if($ctx->isFinal)
    {!! $ctx->ceVarName !!}->ce_flags |= ZEND_ACC_FINAL;
@endif
@if($ctx->isAbstract)
    {!! $ctx->ceVarName !!}->ce_flags |= ZEND_ACC_ABSTRACT;
@endif
@if($ctx->hasClassConstants())
@foreach($ctx->classConstants as $constant)
    {
        zval _qt_const_value;
        {!! $constant['cInit'] !!}
        zend_string *_qt_const_name = zend_string_init_interned("{!! addslashes($constant['name']) !!}", sizeof("{!! addslashes($constant['name']) !!}") - 1, 1);
        if (!zend_hash_exists(&{!! $ctx->ceVarName !!}->constants_table, _qt_const_name)) {
            zend_declare_typed_class_constant(
                {!! $ctx->ceVarName !!},
                _qt_const_name,
                &_qt_const_value,
                ZEND_ACC_PUBLIC,
                NULL,
                (zend_type) ZEND_TYPE_INIT_MASK({!! $constant['cTypeMask'] !!})
            );
        }
        zend_string_release(_qt_const_name);
    }
@endforeach
@endif
@if($ctx->hasQObjectPropertySupport())
    {
        const QMetaObject &_qt_meta = {!! $ctx->nativeCppType !!}::staticMetaObject;
        const int _qt_property_offset = _qt_meta.propertyOffset();
        const int _qt_property_count = _qt_meta.propertyCount();
        for (int _qt_i = _qt_property_offset; _qt_i < _qt_property_count; ++_qt_i) {
            auto _qt_property = _qt_meta.property(_qt_i);
            const char *_qt_property_name_cstr = _qt_property.name();
            if (_qt_property_name_cstr == NULL || *_qt_property_name_cstr == '\0') {
                continue;
            }

            zend_string *_qt_property_name = zend_string_init(_qt_property_name_cstr, strlen(_qt_property_name_cstr), 1);
            zval _qt_property_default_value;
            ZVAL_NULL(&_qt_property_default_value);
            zend_declare_typed_property(
                {!! $ctx->ceVarName !!},
                _qt_property_name,
                &_qt_property_default_value,
                ZEND_ACC_PUBLIC | ZEND_ACC_VIRTUAL,
                NULL,
                (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_ANY)
            );
            zend_string_release_ex(_qt_property_name, 1);
        }
    }
@endif
@if($ctx->nativeCppType === 'QObject')
    qt_qobject_register_runtime_wrapper(&QObject::staticMetaObject, qt_qobject_wrap_runtime_adapter);
    qt_qobject_register_native_extract_adapter(&QObject::staticMetaObject, {!! $ctx->filePrefix !!}_extract_native_adapter);
@elseif($ctx->isQObjectDerived && $ctx->wrapNativeFunc)
    qt_qobject_register_runtime_wrapper(&{!! $ctx->nativeCppType !!}::staticMetaObject, {!! $ctx->filePrefix !!}_wrap_runtime_adapter);
    qt_qobject_register_native_extract_adapter(&{!! $ctx->nativeCppType !!}::staticMetaObject, {!! $ctx->filePrefix !!}_extract_native_adapter);
@elseif($ctx->isQObjectDerived)
    qt_qobject_register_native_extract_adapter(&{!! $ctx->nativeCppType !!}::staticMetaObject, {!! $ctx->filePrefix !!}_extract_native_adapter);
@endif
@if($ctx->hasSignals() && $ctx->isQObjectDerived)
@foreach($ctx->signalOverloads as $signal)
    qt_qobject_register_php_receiver_connect_bridge(
        &{!! $ctx->nativeCppType !!}::staticMetaObject,
        "{!! $signal->signatureLiteral() !!}",
        {!! sprintf('%s_php_receiver_bridge_%d', $ctx->filePrefix, $loop->index) !!}
    );
@endforeach
@endif

    memcpy(&{!! $ctx->handlersVarName !!}, &std_object_handlers, sizeof(zend_object_handlers));
    {!! $ctx->handlersVarName !!}.offset   = XtOffsetOf({!! $ctx->objectStructName !!}, std);
    {!! $ctx->handlersVarName !!}.free_obj = {!! $ctx->filePrefix !!}_free_object;
@if($ctx->isCloneable)
    {!! $ctx->handlersVarName !!}.clone_obj = {!! $ctx->filePrefix !!}_clone_object;
@else
    {!! $ctx->handlersVarName !!}.clone_obj = NULL;
@endif
    {!! $ctx->handlersVarName !!}.get_gc   = {!! $ctx->filePrefix !!}_get_gc;
@if($ctx->hasQObjectPropertySupport())
    {!! $ctx->handlersVarName !!}.read_property = {!! $ctx->filePrefix !!}_read_property;
    {!! $ctx->handlersVarName !!}.write_property = {!! $ctx->filePrefix !!}_write_property;
    {!! $ctx->handlersVarName !!}.get_property_ptr_ptr = {!! $ctx->filePrefix !!}_get_property_ptr_ptr;
    {!! $ctx->handlersVarName !!}.has_property = {!! $ctx->filePrefix !!}_has_property;
    {!! $ctx->handlersVarName !!}.get_properties_for = {!! $ctx->filePrefix !!}_get_properties_for;
@endif
    {!! $ctx->ceVarName !!}->default_object_handlers = &{!! $ctx->handlersVarName !!};

    return SUCCESS;
}
