@php
/** @var \QtBuilder\CodeGen\ClassContext $ctx */
@endphp
/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP wrapper for {!! $ctx->nativeCppType !!}
 * Namespace: {!! $ctx->phpNamespace !!}\{!! $ctx->phpClassName !!}
 */

#ifndef {!! $ctx->headerGuard !!}
#define {!! $ctx->headerGuard !!}

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#include "zend_exceptions.h"
#ifdef __cplusplus
}
#endif
#include "../qt_php_compat.h"
#include <cstdint>
@foreach($ctx->nativeIncludes as $include)
#include {!! $include !!}
@endforeach
@if($ctx->needsArgvStorage)
#include <vector>
#include <QByteArray>
@endif

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

@if($ctx->nativeAliasOf)
using {!! $ctx->nativeCppType !!} = {!! $ctx->nativeAliasOf !!};

@endif
/* ------------------------------------------------------------------ */
/* Object struct                                                       */
/* ------------------------------------------------------------------ */

@if($ctx->needsArgvStorage)
#ifndef QT_ARGV_STORAGE_DEFINED
#define QT_ARGV_STORAGE_DEFINED
typedef struct _{!! $ctx->argvStorageStructName !!} {
    int argc_value = 0;
    std::vector<QByteArray> argv_storage;
    std::vector<char *> argv_pointers;
} {!! $ctx->argvStorageStructName !!};
#endif

@endif
typedef struct _{!! $ctx->objectStructName !!} {
    {!! $ctx->nativeCppType !!} *native_ptr;
@if($ctx->tracksGeneratedNativeSubclass)
    bool native_is_generated_subclass;
@if($ctx->requiresVirtualTrampoline)
    bool native_is_virtual_trampoline;
@endif
@endif
@if($ctx->hasPreventDestroy)
    bool prevent_destroy;
    void *extra_storage;
@endif
@if($ctx->isQObjectDerived)
    bool moved_source;
    uint64_t moved_token;
@endif
    void (*native_rebind_php_object)(void *native_ptr, zend_object *php_object, zend_class_entry *actual_ce);
    zend_object std; /* MUST be last */
} {!! $ctx->objectStructName !!};

/* ------------------------------------------------------------------ */
/* Globals                                                             */
/* ------------------------------------------------------------------ */

extern PHP_QT_API zend_class_entry *{!! $ctx->ceVarName !!};
extern zend_object_handlers {!! $ctx->handlersVarName !!};

/* ------------------------------------------------------------------ */
/* from_obj / Z_*_P macro                                              */
/* ------------------------------------------------------------------ */

static inline {!! $ctx->objectStructName !!} *{!! $ctx->fromObjFunc !!}(zend_object *obj) {
    return ({!! $ctx->objectStructName !!} *)((char *)(obj) - XtOffsetOf({!! $ctx->objectStructName !!}, std));
}

#define {!! $ctx->zMacro !!}(zv) {!! $ctx->fromObjFunc !!}(Z_OBJ_P(zv))

@if($ctx->wrapNativeFunc)
/* ------------------------------------------------------------------ */
/* wrap_native — wrap an existing C++ pointer in a PHP object          */
/* ------------------------------------------------------------------ */

PHP_QT_API void {!! $ctx->wrapNativeFunc !!}(zval *return_value, {!! $ctx->nativeCppType !!} *native,
    zend_class_entry *ce, bool prevent_destroy);

@endif
/* ------------------------------------------------------------------ */
/* MINIT                                                               */
/* ------------------------------------------------------------------ */

PHP_MINIT_FUNCTION({!! $ctx->minitName !!});

#endif /* {!! $ctx->headerGuard !!} */
