@php
/** @var \QtBuilder\CodeGen\ClassContext $ctx */
@endphp
/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP wrapper for {!! $ctx->nativeCppType !!}
 * Namespace: {!! $ctx->phpNamespace !!}\{!! $ctx->phpClassName !!}
 */

#ifndef {!! $ctx->headerGuard !!}
#define {!! $ctx->headerGuard !!}

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "zend_exceptions.h"
#include {!! $ctx->qtInclude !!}
@if($ctx->parentCeVarName)
#include "{!! $ctx->filePrefix !!}_parent.h"
@endif
@foreach($ctx->requiredIncludes as $include)
#include "{!! $include !!}"
@endforeach

/* ------------------------------------------------------------------ */
/* Object struct                                                       */
/* ------------------------------------------------------------------ */

typedef struct _{!! $ctx->objectStructName !!} {
    {!! $ctx->nativeCppType !!} *native_ptr;
@if($ctx->hasPreventDestroy)
    bool prevent_destroy;
@endif
    zend_object std; /* MUST be last */
} {!! $ctx->objectStructName !!};

/* ------------------------------------------------------------------ */
/* Globals                                                             */
/* ------------------------------------------------------------------ */

extern PHP_QT_API zend_class_entry *{!! $ctx->ceVarName !!};
extern zend_object_handlers {!! $ctx->handlersVarName !!};

/* ------------------------------------------------------------------ */
/* from_obj / Z_*_P macro                                              */
/* ------------------------------------------------------------------ */

static inline {!! $ctx->objectStructName !!} *{!! $ctx->fromObjFunc !!}(zend_object *obj) {
    return ({!! $ctx->objectStructName !!} *)((char *)(obj) - XtOffsetOf({!! $ctx->objectStructName !!}, std));
}

#define {!! $ctx->zMacro !!}(zv) {!! $ctx->fromObjFunc !!}(Z_OBJ_P(zv))

@if($ctx->wrapNativeFunc)
/* ------------------------------------------------------------------ */
/* wrap_native — wrap an existing C++ pointer in a PHP object          */
/* ------------------------------------------------------------------ */

void {!! $ctx->wrapNativeFunc !!}(zval *return_value, {!! $ctx->nativeCppType !!} *native,
    zend_class_entry *ce, bool prevent_destroy);

@endif
/* ------------------------------------------------------------------ */
/* MINIT                                                               */
/* ------------------------------------------------------------------ */

PHP_MINIT_FUNCTION({!! $ctx->minitName !!});

#endif /* {!! $ctx->headerGuard !!} */
