dnl Autogenerated config.m4 for the {!! $ctx->extensionName !!} extension

PHP_ARG_ENABLE([{!! $ctx->extensionName !!}],
  [whether to enable {!! $ctx->extensionName !!} support],
  [AS_HELP_STRING([--enable-{!! $ctx->extensionName !!}],
    [Enable {!! $ctx->extensionName !!} support])],
  [no])

AS_VAR_IF([PHP_{!! strtoupper($ctx->extensionName) !!}], [no],, [
  PHP_REQUIRE_CXX()
@foreach($ctx->installation->includeRoots as $includeRoot)
@if(str_starts_with($includeRoot, '-'))
  PHP_EVAL_INCLINE([{!! $includeRoot !!}])
@else
  PHP_ADD_INCLUDE([{!! $includeRoot !!}])
@endif
@endforeach
@if($ctx->installation->libraryRoots !== [])
@if($ctx->installation->isDarwin())
  PHP_EVAL_LIBLINE([-F{!! $ctx->installation->libraryRoots[0] !!} -framework {!! $ctx->moduleLibraryName() !!}], [{!! strtoupper($ctx->extensionName) !!}_SHARED_LIBADD])
@else
  PHP_EVAL_LIBLINE([-L{!! $ctx->installation->libraryRoots[0] !!} -l{!! $ctx->moduleLibraryName() !!}], [{!! strtoupper($ctx->extensionName) !!}_SHARED_LIBADD])
@endif
  PHP_SUBST([{!! strtoupper($ctx->extensionName) !!}_SHARED_LIBADD])
@endif

  AC_DEFINE([HAVE_{!! strtoupper($ctx->extensionName) !!}], [1],
    [Define to 1 if the PHP extension '{!! $ctx->extensionName !!}' is available.])

  PHP_NEW_EXTENSION([{!! $ctx->extensionName !!}],
    [{!! implode(' ', array_merge([$ctx->moduleSourceFilename()], $ctx->classSources())) !!}],
    [$ext_shared],,
    [-std=c++17 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1])
])
