dnl Autogenerated config.m4 for the {!! $ctx->extensionName !!} extension

PHP_ARG_ENABLE([{!! $ctx->extensionName !!}],
  [whether to enable {!! $ctx->extensionName !!} support],
  [AS_HELP_STRING([--enable-{!! $ctx->extensionName !!}],
    [Enable {!! $ctx->extensionName !!} support])],
  [no])

AS_VAR_IF([PHP_{!! strtoupper($ctx->extensionName) !!}], [no],, [
  PHP_REQUIRE_CXX()
@php($sharedLibAdd = strtoupper($ctx->extensionName) . '_SHARED_LIBADD')
@foreach($ctx->compileIncludeRoots() as $includeRoot)
@if(str_starts_with($includeRoot, '-F'))
  CPPFLAGS="$CPPFLAGS {!! $includeRoot !!}"
@elseif(str_starts_with($includeRoot, '-'))
  PHP_EVAL_INCLINE([{!! $includeRoot !!}])
@else
  PHP_ADD_INCLUDE([{!! $includeRoot !!}])
@endif
@endforeach
@if($ctx->installation->moduleLinkFlags !== null && $ctx->installation->moduleLinkFlags !== '')
@if($ctx->installation->isDarwin())
  {!! $sharedLibAdd !!}="{!! '$' . $sharedLibAdd !!} {!! $ctx->installation->moduleLinkFlags !!}"
@else
  PHP_EVAL_LIBLINE([{!! $ctx->installation->moduleLinkFlags !!}], [{!! strtoupper($ctx->extensionName) !!}_SHARED_LIBADD])
@endif
  PHP_SUBST([{!! strtoupper($ctx->extensionName) !!}_SHARED_LIBADD])
@elseif($ctx->installation->libraryRoots !== [])
@if($ctx->installation->isDarwin())
  {!! $sharedLibAdd !!}="{!! '$' . $sharedLibAdd !!} -F{!! $ctx->installation->libraryRoots[0] !!}@foreach($ctx->moduleLibraryNames() as $libraryName) -framework {!! $libraryName !!}@endforeach"
@else
  PHP_EVAL_LIBLINE([-L{!! $ctx->installation->libraryRoots[0] !!}@foreach($ctx->moduleLibraryNames() as $libraryName) -l{!! $libraryName !!}@endforeach], [{!! strtoupper($ctx->extensionName) !!}_SHARED_LIBADD])
@endif
  PHP_SUBST([{!! strtoupper($ctx->extensionName) !!}_SHARED_LIBADD])
@endif

  AC_DEFINE([HAVE_{!! strtoupper($ctx->extensionName) !!}], [1],
    [Define to 1 if the PHP extension '{!! $ctx->extensionName !!}' is available.])

  PHP_NEW_EXTENSION([{!! $ctx->extensionName !!}],
    [{!! implode(' ', array_merge([$ctx->moduleSourceFilename()], $ctx->classSources())) !!}],
    [$ext_shared],,
    [-std=c++17 -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DPHP_SKIP_COMPAT_LOOKUP_MACRO=1])
])
