/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP/Windows compatibility cleanup for generated Qt wrappers.
 */

#ifndef QT_PHP_COMPAT_H
#define QT_PHP_COMPAT_H

#ifdef PHP_WIN32
# ifdef mkdir
#  undef mkdir
# endif
# ifdef rmdir
#  undef rmdir
# endif
# ifdef asprintf
#  undef asprintf
# endif
# ifdef free
#  undef free
# endif
# ifdef lookup
#  undef lookup
# endif
#endif

#endif /* QT_PHP_COMPAT_H */
