@php
/** @var \QtBuilder\Build\ExtensionBuildContext $ctx */
@endphp
/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Runtime build metadata registry and Qt\BuildInfo support.
 */

#ifndef QT_BUILDINFO_H
#define QT_BUILDINFO_H

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#ifdef PHP_WIN32
# ifdef mkdir
#  undef mkdir
# endif
# ifdef rmdir
#  undef rmdir
# endif
#endif

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

typedef struct _qt_buildinfo_module_descriptor {
    const char *module_name;
    const char *extension_name;
    const char *qt_version;
    const char *builder_abi_version;
    const char *const *dependencies;
    size_t dependency_count;
    const char *const *namespaces;
    size_t namespace_count;
    size_t class_count;
    bool includes_signal_connection_support;
    bool loaded;
} qt_buildinfo_module_descriptor;

extern PHP_QT_API zend_class_entry *qt_ce_BuildInfo;

PHP_QT_API zend_string *qt_buildinfo_join_built_modules(void);
PHP_QT_API zend_string *qt_buildinfo_join_loaded_modules(void);

PHP_QT_API zend_result qt_buildinfo_register_module(
    const char *module_name,
    const char *extension_name,
    const char *qt_version,
    const char *builder_abi_version
);

PHP_MINIT_FUNCTION(qt_buildinfo);

#endif /* QT_BUILDINFO_H */
