@php
/** @var \QtBuilder\Build\ExtensionBuildContext $ctx */
$manifest = $ctx->runtimeManifest;
$currentModule = $ctx->currentModuleMetadata();
if (!$manifest instanceof \QtBuilder\Build\RuntimeManifest) {
    throw new \RuntimeException('Qt\\BuildInfo support requires a runtime manifest.');
}
@endphp
/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Runtime build metadata registry and Qt\BuildInfo support.
 */

#include "qt_buildinfo.h"
#include "qt_buildinfo_arginfo.h"

#include <string.h>

zend_class_entry *qt_ce_BuildInfo = NULL;

@foreach($manifest->modules as $moduleName => $module)
@php($dependencies = $module->dependencies)
@php($namespaces = $module->namespaces)
@if($dependencies !== [])
static const char *qt_buildinfo_{{ strtolower($moduleName) }}_dependencies[] = {
@foreach($dependencies as $dependency)
    "{{ $dependency }}",
@endforeach
};
@endif
@if($namespaces !== [])
static const char *qt_buildinfo_{{ strtolower($moduleName) }}_namespaces[] = {
@foreach($namespaces as $namespace)
    "{{ addslashes($namespace) }}",
@endforeach
};
@endif
@endforeach

static const char *qt_buildinfo_built_modules[] = {
@foreach($manifest->builtModules as $module)
    "{{ $module }}",
@endforeach
};

static const char *qt_buildinfo_build_order[] = {
@foreach($manifest->buildOrder as $module)
    "{{ $module }}",
@endforeach
};

static qt_buildinfo_module_descriptor qt_buildinfo_modules[] = {
@foreach($manifest->modules as $moduleName => $module)
    {
        "{{ $module->module }}",
        "{{ $module->extensionName }}",
        "{{ $manifest->qtVersion }}",
        "{{ $manifest->builderAbiVersion }}",
@if($module->dependencies !== [])
        qt_buildinfo_{{ strtolower($moduleName) }}_dependencies,
        sizeof(qt_buildinfo_{{ strtolower($moduleName) }}_dependencies) / sizeof(qt_buildinfo_{{ strtolower($moduleName) }}_dependencies[0]),
@else
        NULL,
        0,
@endif
@if($module->namespaces !== [])
        qt_buildinfo_{{ strtolower($moduleName) }}_namespaces,
        sizeof(qt_buildinfo_{{ strtolower($moduleName) }}_namespaces) / sizeof(qt_buildinfo_{{ strtolower($moduleName) }}_namespaces[0]),
@else
        NULL,
        0,
@endif
        {{ $module->classCount }},
        {{ $module->includesSignalConnectionSupport ? 'true' : 'false' }},
        false
    },
@endforeach
};

static const size_t qt_buildinfo_module_count = sizeof(qt_buildinfo_modules) / sizeof(qt_buildinfo_modules[0]);

static qt_buildinfo_module_descriptor *qt_buildinfo_find_module(const char *module_name, size_t module_name_len)
{
    for (size_t index = 0; index < qt_buildinfo_module_count; index++) {
        qt_buildinfo_module_descriptor *entry = &qt_buildinfo_modules[index];
        if (strlen(entry->module_name) != module_name_len) {
            continue;
        }

        if (strncmp(entry->module_name, module_name, module_name_len) == 0) {
            return entry;
        }
    }

    return NULL;
}

static void qt_buildinfo_append_string_list(zval *return_value, const char *const *items, size_t item_count)
{
    array_init_size(return_value, item_count);

    for (size_t index = 0; index < item_count; index++) {
        add_next_index_string(return_value, (char *) items[index]);
    }
}

static void qt_buildinfo_add_module_info(zval *return_value, const qt_buildinfo_module_descriptor *entry)
{
    zval dependencies;
    zval namespaces;

    array_init(return_value);
    add_assoc_string(return_value, "module", (char *) entry->module_name);
    add_assoc_string(return_value, "extension_name", (char *) entry->extension_name);

    qt_buildinfo_append_string_list(&dependencies, entry->dependencies, entry->dependency_count);
    add_assoc_zval(return_value, "dependencies", &dependencies);

    add_assoc_bool(return_value, "loaded", entry->loaded);

    qt_buildinfo_append_string_list(&namespaces, entry->namespaces, entry->namespace_count);
    add_assoc_zval(return_value, "namespaces", &namespaces);

    add_assoc_long(return_value, "class_count", (zend_long) entry->class_count);
    add_assoc_bool(return_value, "includes_signal_connection_support", entry->includes_signal_connection_support);
}

static void qt_buildinfo_add_loaded_modules(zval *return_value)
{
    size_t count = 0;
    for (size_t index = 0; index < qt_buildinfo_module_count; index++) {
        if (qt_buildinfo_modules[index].loaded) {
            count++;
        }
    }

    array_init_size(return_value, count);
    for (size_t index = 0; index < qt_buildinfo_module_count; index++) {
        if (!qt_buildinfo_modules[index].loaded) {
            continue;
        }

        add_next_index_string(return_value, (char *) qt_buildinfo_modules[index].module_name);
    }
}

PHP_QT_API zend_result qt_buildinfo_register_module(
    const char *module_name,
    const char *extension_name,
    const char *qt_version,
    const char *builder_abi_version
)
{
    qt_buildinfo_module_descriptor *entry = qt_buildinfo_find_module(module_name, strlen(module_name));
    if (entry == NULL) {
        php_error_docref(NULL, E_WARNING, "Unknown Qt module registration attempted: %s", module_name);
        return FAILURE;
    }

    if (strcmp(entry->extension_name, extension_name) != 0) {
        php_error_docref(
            NULL,
            E_WARNING,
            "Qt module %s expected extension %s but %s attempted to register",
            module_name,
            entry->extension_name,
            extension_name
        );
        return FAILURE;
    }

    if (strcmp(entry->qt_version, qt_version) != 0) {
        php_error_docref(
            NULL,
            E_WARNING,
            "%s was built against Qt %s, but the active build set expects Qt %s",
            extension_name,
            qt_version,
            entry->qt_version
        );
        return FAILURE;
    }

    if (strcmp(entry->builder_abi_version, builder_abi_version) != 0) {
        php_error_docref(
            NULL,
            E_WARNING,
            "%s was built with builder ABI %s, but the active build set expects %s",
            extension_name,
            builder_abi_version,
            entry->builder_abi_version
        );
        return FAILURE;
    }

    entry->loaded = true;

    return SUCCESS;
}

PHP_METHOD(BuildInfo, buildMode)
{
    ZEND_PARSE_PARAMETERS_NONE();

    RETURN_STRING("{{ $manifest->buildMode }}");
}

PHP_METHOD(BuildInfo, qtVersion)
{
    ZEND_PARSE_PARAMETERS_NONE();

    RETURN_STRING("{{ $manifest->qtVersion }}");
}

PHP_METHOD(BuildInfo, extensionVersion)
{
    ZEND_PARSE_PARAMETERS_NONE();

    RETURN_STRING("{{ $manifest->extensionVersion }}");
}

PHP_METHOD(BuildInfo, builtModules)
{
    ZEND_PARSE_PARAMETERS_NONE();

    qt_buildinfo_append_string_list(
        return_value,
        qt_buildinfo_built_modules,
        sizeof(qt_buildinfo_built_modules) / sizeof(qt_buildinfo_built_modules[0])
    );
}

PHP_METHOD(BuildInfo, loadedModules)
{
    ZEND_PARSE_PARAMETERS_NONE();

    qt_buildinfo_add_loaded_modules(return_value);
}

PHP_METHOD(BuildInfo, hasModule)
{
    char *module_name = NULL;
    size_t module_name_len = 0;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STRING(module_name, module_name_len)
    ZEND_PARSE_PARAMETERS_END();

    RETURN_BOOL(qt_buildinfo_find_module(module_name, module_name_len) != NULL);
}

PHP_METHOD(BuildInfo, isLoaded)
{
    char *module_name = NULL;
    size_t module_name_len = 0;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STRING(module_name, module_name_len)
    ZEND_PARSE_PARAMETERS_END();

    qt_buildinfo_module_descriptor *entry = qt_buildinfo_find_module(module_name, module_name_len);
    RETURN_BOOL(entry != NULL && entry->loaded);
}

PHP_METHOD(BuildInfo, moduleInfo)
{
    char *module_name = NULL;
    size_t module_name_len = 0;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STRING(module_name, module_name_len)
    ZEND_PARSE_PARAMETERS_END();

    qt_buildinfo_module_descriptor *entry = qt_buildinfo_find_module(module_name, module_name_len);
    if (entry == NULL) {
        RETURN_NULL();
    }

    qt_buildinfo_add_module_info(return_value, entry);
}

PHP_METHOD(BuildInfo, manifest)
{
    zval built_modules;
    zval build_order;
    zval loaded_modules;
    zval modules;

    ZEND_PARSE_PARAMETERS_NONE();

    array_init(return_value);
    add_assoc_long(return_value, "schema_version", {{ \QtBuilder\Build\RuntimeManifest::SCHEMA_VERSION }});
    add_assoc_string(return_value, "build_mode", "{{ $manifest->buildMode }}");
    add_assoc_string(return_value, "qt_version", "{{ $manifest->qtVersion }}");
    add_assoc_long(return_value, "qt_version_major", {{ $manifest->qtVersionMajor }});
    add_assoc_long(return_value, "qt_version_minor", {{ $manifest->qtVersionMinor }});
    add_assoc_long(return_value, "qt_version_patch", {{ $manifest->qtVersionPatch }});
    add_assoc_string(return_value, "extension_version", "{{ $manifest->extensionVersion }}");
    add_assoc_string(return_value, "builder_abi_version", "{{ $manifest->builderAbiVersion }}");

    qt_buildinfo_append_string_list(
        &built_modules,
        qt_buildinfo_built_modules,
        sizeof(qt_buildinfo_built_modules) / sizeof(qt_buildinfo_built_modules[0])
    );
    add_assoc_zval(return_value, "built_modules", &built_modules);

    qt_buildinfo_append_string_list(
        &build_order,
        qt_buildinfo_build_order,
        sizeof(qt_buildinfo_build_order) / sizeof(qt_buildinfo_build_order[0])
    );
    add_assoc_zval(return_value, "build_order", &build_order);

    qt_buildinfo_add_loaded_modules(&loaded_modules);
    add_assoc_zval(return_value, "loaded_modules", &loaded_modules);

    array_init_size(&modules, qt_buildinfo_module_count);
    for (size_t index = 0; index < qt_buildinfo_module_count; index++) {
        zval module_info;
        qt_buildinfo_add_module_info(&module_info, &qt_buildinfo_modules[index]);
        add_assoc_zval(&modules, qt_buildinfo_modules[index].module_name, &module_info);
    }
    add_assoc_zval(return_value, "modules", &modules);
}

static const zend_function_entry qt_buildinfo_methods[] = {
    ZEND_ME(BuildInfo, buildMode, arginfo_class_Qt_BuildInfo_buildMode, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, qtVersion, arginfo_class_Qt_BuildInfo_qtVersion, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, extensionVersion, arginfo_class_Qt_BuildInfo_extensionVersion, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, builtModules, arginfo_class_Qt_BuildInfo_builtModules, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, loadedModules, arginfo_class_Qt_BuildInfo_loadedModules, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, hasModule, arginfo_class_Qt_BuildInfo_hasModule, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, isLoaded, arginfo_class_Qt_BuildInfo_isLoaded, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, moduleInfo, arginfo_class_Qt_BuildInfo_moduleInfo, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(BuildInfo, manifest, arginfo_class_Qt_BuildInfo_manifest, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_FE_END
};

PHP_MINIT_FUNCTION(qt_buildinfo)
{
    zend_class_entry ce;

    INIT_NS_CLASS_ENTRY(ce, "Qt", "BuildInfo", qt_buildinfo_methods);
    qt_ce_BuildInfo = zend_register_internal_class(&ce);
    qt_ce_BuildInfo->ce_flags |= ZEND_ACC_FINAL;

    zend_declare_class_constant_string(qt_ce_BuildInfo, "MODE_MONOLITHIC", sizeof("MODE_MONOLITHIC") - 1, "{{ \QtBuilder\Build\RuntimeManifest::MODE_MONOLITHIC }}");
    zend_declare_class_constant_string(qt_ce_BuildInfo, "MODE_MODULAR", sizeof("MODE_MODULAR") - 1, "{{ \QtBuilder\Build\RuntimeManifest::MODE_MODULAR }}");

    for (size_t index = 0; index < qt_buildinfo_module_count; index++) {
        qt_buildinfo_modules[index].loaded = false;
    }

@if($manifest->buildMode === \QtBuilder\Build\RuntimeManifest::MODE_MONOLITHIC)
    for (size_t index = 0; index < qt_buildinfo_module_count; index++) {
        qt_buildinfo_modules[index].loaded = true;
    }
@elseif($currentModule instanceof \QtBuilder\Build\RuntimeModuleMetadata)
    if (qt_buildinfo_register_module("{{ $currentModule->module }}", "{{ $currentModule->extensionName }}", "{{ $manifest->qtVersion }}", "{{ $manifest->builderAbiVersion }}") != SUCCESS) {
        return FAILURE;
    }
@endif

    return SUCCESS;
}
