/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP enum-holder support for {!! $ctx->phpNamespace !!}\{!! $ctx->phpClassName !!}.
 */

#include "{!! $ctx->filePrefix !!}.h"

zend_class_entry *{!! $ctx->ceVarName !!} = NULL;

static const zend_function_entry {!! $ctx->filePrefix !!}_methods[] = {
    ZEND_FE_END
};

PHP_MINIT_FUNCTION({!! $ctx->minitName !!})
{
    zend_class_entry ce;
    INIT_NS_CLASS_ENTRY(ce, "{!! $ctx->phpNamespace !!}", "{!! $ctx->phpClassName !!}", {!! $ctx->filePrefix !!}_methods);

    {!! $ctx->ceVarName !!} = zend_register_internal_class(&ce);
    {!! $ctx->ceVarName !!}->ce_flags |= ZEND_ACC_FINAL;

@foreach($ctx->constants as $constant)
    {!! sprintf($constant['cDecl'], $ctx->ceVarName) !!}
@endforeach

    return SUCCESS;
}
