/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP enum-holder support for {!! $ctx->phpNamespace !!}\{!! $ctx->phpClassName !!}.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#ifdef __cplusplus
}
#endif
#ifdef PHP_WIN32
# ifdef mkdir
#  undef mkdir
# endif
# ifdef rmdir
#  undef rmdir
# endif
# ifdef asprintf
#  undef asprintf
# endif
#endif
#include "php_qt.h"

extern zend_class_entry *{!! $ctx->ceVarName !!};
PHP_MINIT_FUNCTION({!! $ctx->minitName !!});
