/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP enum-holder support for {!! $ctx->phpNamespace !!}\{!! $ctx->phpClassName !!}.
 */

#pragma once

#include "php.h"
#include "php_qt.h"

extern zend_class_entry *{!! $ctx->ceVarName !!};
PHP_MINIT_FUNCTION({!! $ctx->minitName !!});
