/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * PHP enum-holder support for {!! $ctx->phpNamespace !!}\{!! $ctx->phpClassName !!}.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#ifdef __cplusplus
}
#endif
#include "qt_php_compat.h"
#include "php_qt.h"

extern zend_class_entry *{!! $ctx->ceVarName !!};
PHP_MINIT_FUNCTION({!! $ctx->minitName !!});
