/**
 * Auto-generated by phpqt-builder -- DO NOT EDIT.
 *
 * Shared ownership helpers for generated Qt wrapper classes.
 */

#ifndef QT_OWNERSHIP_HELPERS_H
#define QT_OWNERSHIP_HELPERS_H

#include "qt_class_helpers.h"
#include <QCoreApplication>
#include <QObject>
#include <mutex>
#include <type_traits>
#include <unordered_set>

template <typename T>
static zend_always_inline bool qt_native_has_qobject_parent(T *ptr)
{
    if (ptr == NULL) {
        return false;
    }

    if constexpr (std::is_base_of_v<QObject, T>) {
        return ptr->parent() != NULL;
    }

    return false;
}

template <typename T>
static inline typename std::enable_if<std::is_base_of<QObject, T>::value, bool>::type
qt_should_delete_native(T *ptr, bool prevent_destroy);

template <typename T>
static inline std::unordered_set<void *> &qt_native_registry()
{
    static std::unordered_set<void *> registry;
    return registry;
}

template <typename T>
static inline std::mutex &qt_native_registry_mutex()
{
    static std::mutex registryMutex;
    return registryMutex;
}

template <typename T>
static inline typename std::enable_if<std::is_base_of<QObject, T>::value, void>::type
qt_track_native_instance(T *ptr)
{
    if (ptr == NULL) {
        return;
    }

    {
        std::lock_guard<std::mutex> lock(qt_native_registry_mutex<T>());
        qt_native_registry<T>().insert(static_cast<void *>(ptr));
    }

    QObject::connect(ptr, &QObject::destroyed, [ptr]() {
        std::lock_guard<std::mutex> lock(qt_native_registry_mutex<T>());
        qt_native_registry<T>().erase(static_cast<void *>(ptr));
    });
}

template <typename T>
static inline typename std::enable_if<!std::is_base_of<QObject, T>::value, void>::type
qt_track_native_instance(T *ptr)
{
    (void) ptr;
}

template <typename T>
static inline typename std::enable_if<std::is_base_of<QObject, T>::value, bool>::type
qt_should_delete_native(T *ptr, bool prevent_destroy)
{
    if (ptr == NULL || prevent_destroy) {
        return false;
    }

    if (QCoreApplication::closingDown()) {
        return false;
    }

#ifdef EG_FLAGS_IN_SHUTDOWN
    if ((EG(flags) & EG_FLAGS_IN_SHUTDOWN) != 0) {
        return false;
    }
#endif

    if (qt_runtime_is_shutdown_in_progress()) {
        return false;
    }

    {
        std::lock_guard<std::mutex> lock(qt_native_registry_mutex<T>());
        if (qt_native_registry<T>().find(static_cast<void *>(ptr)) == qt_native_registry<T>().end()) {
            return false;
        }
    }

    return static_cast<QObject *>(ptr)->parent() == NULL;
}

template <typename T>
static inline typename std::enable_if<!std::is_base_of<QObject, T>::value, bool>::type
qt_should_delete_native(T *ptr, bool prevent_destroy)
{
    return ptr != NULL && !prevent_destroy;
}

#endif /* QT_OWNERSHIP_HELPERS_H */
