/**
 * Auto-generated by phpqt-builder -- DO NOT EDIT.
 *
 * Shared helpers for extension-managed PHP signals.
 */

#ifndef QT_PHP_SIGNAL_HELPERS_H
#define QT_PHP_SIGNAL_HELPERS_H

#include "qt_qobject_helpers.h"
#include "qt_qthreadruntime.h"

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

#include "zend_attributes.h"
#include <QCoreApplication>
#include <QEvent>
#include <QObject>
#include <QPointer>
#include <QThread>
#include <algorithm>
#include <atomic>
#include <cctype>
#include <cstring>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

extern zend_class_entry *qt_ce_qobject;

static constexpr const char *QT_PHP_SIGNAL_ATTRIBUTE_LCNAME = "qt\\core\\attributes\\signal";
static constexpr int QT_PHP_SIGNAL_ATTRIBUTE_LCNAME_LEN = sizeof("qt\\core\\attributes\\signal") - 1;

static inline std::string qt_php_signal_lower(std::string value)
{
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char ch) -> char {
        return (char) std::tolower(ch);
    });
    return value;
}

static inline std::string qt_php_signal_lower(const char *value, size_t length)
{
    if (value == NULL || length == 0) {
        return std::string();
    }

    return qt_php_signal_lower(std::string(value, length));
}

static inline std::string qt_php_signal_lower(zend_string *value)
{
    if (value == NULL) {
        return std::string();
    }

    return qt_php_signal_lower(ZSTR_VAL(value), ZSTR_LEN(value));
}

static inline bool qt_php_signal_debug_enabled()
{
    static int enabled = -1;
    if (enabled >= 0) {
        return enabled == 1;
    }

    const char *raw = getenv("QT_PHP_SIGNAL_DEBUG");
    enabled = (raw != NULL && *raw != '\0' && strcmp(raw, "0") != 0) ? 1 : 0;
    return enabled == 1;
}

static inline void qt_php_signal_debug_log(const char *message)
{
    if (!qt_php_signal_debug_enabled() || message == NULL) {
        return;
    }

    fprintf(
        stderr,
        "[qt-php-signal] %s current_thread=%p zend=%d owner=%d\n",
        message,
        (void *) QThread::currentThread(),
        qt_runtime_can_call_zend() ? 1 : 0,
        qt_runtime_is_owner_thread() ? 1 : 0
    );
}

static inline zend_attribute *qt_php_signal_attribute_for_function(zend_function *func)
{
    if (func == NULL) {
        return NULL;
    }

    return zend_get_attribute_str(
        func->common.attributes,
        QT_PHP_SIGNAL_ATTRIBUTE_LCNAME,
        QT_PHP_SIGNAL_ATTRIBUTE_LCNAME_LEN
    );
}

static inline bool qt_php_signal_function_is_declaration(zend_function *func)
{
    return qt_php_signal_attribute_for_function(func) != NULL;
}

struct qt_php_signal_declared_signal
{
    std::string name;
    std::string lookup_name;
    std::vector<std::string> types;
};

struct qt_php_signal_class_metadata
{
    bool valid{false};
    std::string error;
    std::unordered_map<std::string, qt_php_signal_declared_signal> signals_by_lookup;
};

PHP_QT_API std::unordered_map<zend_class_entry *, std::shared_ptr<qt_php_signal_class_metadata>> &qt_php_signal_class_metadata_registry();
PHP_QT_API std::mutex &qt_php_signal_class_metadata_registry_mutex();

static inline bool qt_php_signal_type_token_is_valid(const std::string &token)
{
    if (token.empty()) {
        return false;
    }

    const std::string lowered = qt_php_signal_lower(token);
    if (lowered == "bool"
        || lowered == "int"
        || lowered == "float"
        || lowered == "string"
        || lowered == "array"
        || lowered == "mixed"
        || lowered == "qobject") {
        return true;
    }

    for (char ch : token) {
        if ((ch >= 'a' && ch <= 'z')
            || (ch >= 'A' && ch <= 'Z')
            || (ch >= '0' && ch <= '9')
            || ch == '_'
            || ch == '\\') {
            continue;
        }
        return false;
    }

    return true;
}

static inline std::shared_ptr<qt_php_signal_class_metadata> qt_php_signal_build_class_metadata(zend_class_entry *ce)
{
    auto metadata = std::make_shared<qt_php_signal_class_metadata>();
    if (ce == NULL) {
        metadata->error = "Missing class entry for PHP signal metadata.";
        return metadata;
    }

    if (qt_ce_qobject != NULL && !instanceof_function(ce, qt_ce_qobject)) {
        metadata->valid = true;
        return metadata;
    }

    zend_string *name = NULL;
    zval *func_zv = NULL;
    ZEND_HASH_FOREACH_STR_KEY_VAL(&ce->function_table, name, func_zv) {
        if (name == NULL || func_zv == NULL) {
            continue;
        }

        zend_function *func = (zend_function *) Z_PTR_P(func_zv);
        if (func == NULL) {
            continue;
        }

        zend_attribute *attribute = qt_php_signal_attribute_for_function(func);
        if (attribute == NULL) {
            continue;
        }

        if ((func->common.fn_flags & ZEND_ACC_PUBLIC) != 0) {
            metadata->error = std::string("Signal declaration method ")
                + ZSTR_VAL(name)
                + " must be protected or private.";
            return metadata;
        }

        if ((func->common.fn_flags & ZEND_ACC_STATIC) != 0) {
            metadata->error = std::string("Signal declaration method ")
                + ZSTR_VAL(name)
                + " must be an instance method.";
            return metadata;
        }

        qt_php_signal_declared_signal signal;
        signal.name.assign(ZSTR_VAL(name), ZSTR_LEN(name));
        signal.lookup_name = qt_php_signal_lower(name);

        if (attribute->argc > 1) {
            metadata->error = std::string("Signal declaration method ")
                + signal.name
                + " accepts only one attribute argument.";
            return metadata;
        }

        if (attribute->argc == 1) {
            zval attribute_value;
            ZVAL_UNDEF(&attribute_value);
            if (zend_get_attribute_value(&attribute_value, attribute, 0, ce) != SUCCESS) {
                if (!Z_ISUNDEF(attribute_value)) {
                    zval_ptr_dtor(&attribute_value);
                }
                metadata->error = std::string("Signal declaration method ")
                    + signal.name
                    + " has an invalid attribute payload.";
                return metadata;
            }

            if (Z_TYPE(attribute_value) != IS_ARRAY) {
                zval_ptr_dtor(&attribute_value);
                metadata->error = std::string("Signal declaration method ")
                    + signal.name
                    + " requires an array payload for #[Signal].";
                return metadata;
            }

            zval *entry = NULL;
            ZEND_HASH_FOREACH_VAL(Z_ARRVAL(attribute_value), entry) {
                if (entry == NULL) {
                    continue;
                }

                zend_string *type_string = zval_get_string(entry);
                if (type_string == NULL) {
                    zval_ptr_dtor(&attribute_value);
                    metadata->error = std::string("Signal declaration method ")
                        + signal.name
                        + " has an invalid type token.";
                    return metadata;
                }

                std::string type_token(ZSTR_VAL(type_string), ZSTR_LEN(type_string));
                zend_string_release(type_string);
                if (!qt_php_signal_type_token_is_valid(type_token)) {
                    zval_ptr_dtor(&attribute_value);
                    metadata->error = std::string("Signal declaration method ")
                        + signal.name
                        + " has an unsupported type token "
                        + type_token
                        + ".";
                    return metadata;
                }

                signal.types.push_back(type_token);
            } ZEND_HASH_FOREACH_END();

            zval_ptr_dtor(&attribute_value);
        }

        metadata->signals_by_lookup[signal.lookup_name] = std::move(signal);
    } ZEND_HASH_FOREACH_END();

    metadata->valid = true;
    return metadata;
}

static inline std::shared_ptr<const qt_php_signal_class_metadata> qt_php_signal_class_metadata_for_ce(
    zend_class_entry *ce,
    std::string *error
)
{
    if (ce == NULL) {
        if (error != NULL) {
            *error = "Missing class entry for PHP signal metadata.";
        }
        return nullptr;
    }

    {
        std::lock_guard<std::mutex> lock(qt_php_signal_class_metadata_registry_mutex());
        auto it = qt_php_signal_class_metadata_registry().find(ce);
        if (it != qt_php_signal_class_metadata_registry().end()) {
            if (!it->second->valid && error != NULL) {
                *error = it->second->error;
            }
            return it->second;
        }
    }

    auto metadata = qt_php_signal_build_class_metadata(ce);
    {
        std::lock_guard<std::mutex> lock(qt_php_signal_class_metadata_registry_mutex());
        qt_php_signal_class_metadata_registry()[ce] = metadata;
    }

    if (!metadata->valid && error != NULL) {
        *error = metadata->error;
    }

    return metadata;
}

static inline const qt_php_signal_declared_signal *qt_php_signal_find_declared_signal(
    zend_class_entry *ce,
    zend_string *signal_name,
    std::string *error
)
{
    auto metadata = qt_php_signal_class_metadata_for_ce(ce, error);
    if (!metadata || !metadata->valid) {
        return nullptr;
    }

    std::string lookup_name = qt_php_signal_lower(signal_name);
    auto it = metadata->signals_by_lookup.find(lookup_name);
    if (it == metadata->signals_by_lookup.end()) {
        if (error != NULL) {
            *error = std::string("Unknown PHP signal ") + ZSTR_VAL(signal_name) + ".";
        }
        return nullptr;
    }

    return &it->second;
}

static inline bool qt_php_signal_has_declared_signal(zend_class_entry *ce, zend_string *signal_name)
{
    std::string error;
    return qt_php_signal_find_declared_signal(ce, signal_name, &error) != nullptr;
}

struct qt_php_signal_live_wrapper_entry
{
    zend_object *wrapper{nullptr};
    QPointer<QThread> owner_thread;
};

PHP_QT_API std::unordered_map<QObject *, qt_php_signal_live_wrapper_entry> &qt_php_signal_live_wrapper_registry();
PHP_QT_API std::mutex &qt_php_signal_live_wrapper_registry_mutex();

static inline void qt_php_signal_register_live_wrapper(QObject *native, zend_object *wrapper)
{
    if (native == NULL || wrapper == NULL) {
        return;
    }

    {
        std::lock_guard<std::mutex> lock(qt_php_signal_live_wrapper_registry_mutex());
        qt_php_signal_live_wrapper_registry()[native] = qt_php_signal_live_wrapper_entry{
            wrapper,
            QThread::currentThread(),
        };
    }

    QObject::connect(native, &QObject::destroyed, [native]() {
        std::lock_guard<std::mutex> lock(qt_php_signal_live_wrapper_registry_mutex());
        qt_php_signal_live_wrapper_registry().erase(native);
    });
}

static inline void qt_php_signal_unregister_live_wrapper(QObject *native, zend_object *wrapper)
{
    if (native == NULL || wrapper == NULL) {
        return;
    }

    std::lock_guard<std::mutex> lock(qt_php_signal_live_wrapper_registry_mutex());
    auto it = qt_php_signal_live_wrapper_registry().find(native);
    if (it == qt_php_signal_live_wrapper_registry().end()) {
        return;
    }

    if (it->second.wrapper == wrapper) {
        qt_php_signal_live_wrapper_registry().erase(it);
    }
}

static inline zend_object *qt_php_signal_resolve_current_thread_live_wrapper(QObject *native)
{
    if (native == NULL) {
        return NULL;
    }

    std::lock_guard<std::mutex> lock(qt_php_signal_live_wrapper_registry_mutex());
    auto it = qt_php_signal_live_wrapper_registry().find(native);
    if (it == qt_php_signal_live_wrapper_registry().end()) {
        return NULL;
    }

    QThread *current_thread = QThread::currentThread();
    if (it->second.owner_thread.isNull() || it->second.owner_thread.data() != current_thread) {
        return qt_qthreadruntime_resolve_current_thread_live_php_object(native);
    }

    if (it->second.wrapper != NULL) {
        return it->second.wrapper;
    }

    return qt_qthreadruntime_resolve_current_thread_live_php_object(native);
}

enum class qt_php_signal_value_type : uint8_t
{
    null_value = 0,
    bool_value,
    long_value,
    double_value,
    string_value,
    array_value,
    qobject_value,
};

struct qt_php_signal_value
{
    qt_php_signal_value_type type{qt_php_signal_value_type::null_value};
    bool bool_data{false};
    zend_long long_data{0};
    double double_data{0.0};
    std::string string_data;
    std::vector<qt_php_signal_value> array_values;
    QPointer<QObject> qobject_data;
};

static inline bool qt_php_signal_value_to_zval(const qt_php_signal_value &value, zval *out);

static inline bool qt_php_signal_zval_to_value(zval *value, qt_php_signal_value *out, std::string *error)
{
    if (value == NULL || out == NULL) {
        return false;
    }

    if (Z_ISREF_P(value)) {
        if (error != NULL) {
            *error = "PHP signal payload references are not supported.";
        }
        return false;
    }

    switch (Z_TYPE_P(value)) {
        case IS_NULL:
            out->type = qt_php_signal_value_type::null_value;
            return true;
        case IS_FALSE:
        case IS_TRUE:
            out->type = qt_php_signal_value_type::bool_value;
            out->bool_data = Z_TYPE_P(value) == IS_TRUE;
            return true;
        case IS_LONG:
            out->type = qt_php_signal_value_type::long_value;
            out->long_data = Z_LVAL_P(value);
            return true;
        case IS_DOUBLE:
            out->type = qt_php_signal_value_type::double_value;
            out->double_data = Z_DVAL_P(value);
            return true;
        case IS_STRING:
            out->type = qt_php_signal_value_type::string_value;
            out->string_data.assign(Z_STRVAL_P(value), Z_STRLEN_P(value));
            return true;
        case IS_ARRAY: {
            out->type = qt_php_signal_value_type::array_value;
            out->array_values.reserve(zend_hash_num_elements(Z_ARRVAL_P(value)));
            zval *entry = NULL;
            ZEND_HASH_FOREACH_VAL(Z_ARRVAL_P(value), entry) {
                qt_php_signal_value child;
                if (!qt_php_signal_zval_to_value(entry, &child, error)) {
                    return false;
                }
                out->array_values.push_back(std::move(child));
            } ZEND_HASH_FOREACH_END();
            return true;
        }
        case IS_OBJECT: {
            QObject *native = qt_qobject_extract_native_from_zval(value);
            if (native == NULL) {
                if (error != NULL) {
                    *error = "PHP signal payload objects must be Qt QObject wrappers.";
                }
                return false;
            }
            out->type = qt_php_signal_value_type::qobject_value;
            out->qobject_data = native;
            return true;
        }
        default:
            if (error != NULL) {
                *error = "PHP signal payload supports only null/bool/int/float/string/array/QObject values.";
            }
            return false;
    }
}

static inline bool qt_php_signal_value_to_zval(const qt_php_signal_value &value, zval *out)
{
    if (out == NULL) {
        return false;
    }

    switch (value.type) {
        case qt_php_signal_value_type::null_value:
            ZVAL_NULL(out);
            return true;
        case qt_php_signal_value_type::bool_value:
            ZVAL_BOOL(out, value.bool_data);
            return true;
        case qt_php_signal_value_type::long_value:
            ZVAL_LONG(out, value.long_data);
            return true;
        case qt_php_signal_value_type::double_value:
            ZVAL_DOUBLE(out, value.double_data);
            return true;
        case qt_php_signal_value_type::string_value:
            ZVAL_STRINGL(out, value.string_data.data(), value.string_data.size());
            return true;
        case qt_php_signal_value_type::array_value: {
            array_init_size(out, (uint32_t) value.array_values.size());
            for (const qt_php_signal_value &child : value.array_values) {
                zval entry;
                ZVAL_NULL(&entry);
                if (!qt_php_signal_value_to_zval(child, &entry)) {
                    zval_ptr_dtor(out);
                    ZVAL_NULL(out);
                    return false;
                }
                add_next_index_zval(out, &entry);
            }
            return true;
        }
        case qt_php_signal_value_type::qobject_value: {
            QObject *native = value.qobject_data.data();
            if (native == NULL) {
                ZVAL_NULL(out);
                return true;
            }
            zend_object *live = qt_php_signal_resolve_current_thread_live_wrapper(native);
            if (live != NULL) {
                ZVAL_OBJ_COPY(out, live);
                return true;
            }
            return qt_qobject_wrap_runtime_instance(out, native, true);
        }
    }

    ZVAL_NULL(out);
    return true;
}

static inline bool qt_php_signal_validate_typed_value(zval *value, const std::string &type_token, std::string *error)
{
    const std::string lowered = qt_php_signal_lower(type_token);
    if (lowered == "mixed") {
        qt_php_signal_value snapshot;
        return qt_php_signal_zval_to_value(value, &snapshot, error);
    }
    if (lowered == "bool") {
        if (Z_TYPE_P(value) == IS_TRUE || Z_TYPE_P(value) == IS_FALSE) {
            return true;
        }
    } else if (lowered == "int") {
        if (Z_TYPE_P(value) == IS_LONG) {
            return true;
        }
    } else if (lowered == "float") {
        if (Z_TYPE_P(value) == IS_DOUBLE) {
            return true;
        }
    } else if (lowered == "string") {
        if (Z_TYPE_P(value) == IS_STRING) {
            return true;
        }
    } else if (lowered == "array") {
        if (Z_TYPE_P(value) == IS_ARRAY) {
            qt_php_signal_value snapshot;
            return qt_php_signal_zval_to_value(value, &snapshot, error);
        }
    } else {
        if (Z_TYPE_P(value) != IS_OBJECT) {
            if (error != NULL) {
                *error = std::string("PHP signal argument must be an object of type ") + type_token + ".";
            }
            return false;
        }

        QObject *native = qt_qobject_extract_native_from_zval(value);
        if (native == NULL) {
            if (error != NULL) {
                *error = std::string("PHP signal argument must be a Qt QObject wrapper for type ") + type_token + ".";
            }
            return false;
        }

        if (lowered == "qobject") {
            return true;
        }

        zend_string *ce_name = zend_string_init(type_token.c_str(), type_token.size(), 0);
        zend_class_entry *expected_ce = zend_lookup_class_ex(ce_name, NULL, ZEND_FETCH_CLASS_NO_AUTOLOAD);
        zend_string_release(ce_name);
        if (expected_ce == NULL) {
            if (error != NULL) {
                *error = std::string("Unknown PHP signal type token ") + type_token + ".";
            }
            return false;
        }

        if (Z_TYPE_P(value) == IS_OBJECT && instanceof_function(Z_OBJCE_P(value), expected_ce)) {
            return true;
        }
    }

    if (error != NULL) {
        *error = std::string("PHP signal argument does not match declared type ") + type_token + ".";
    }
    return false;
}

enum class qt_php_signal_listener_target_type : uint8_t
{
    callable_target = 0,
    receiver_method_target,
};

struct qt_php_signal_callable_target
{
    zend_fcall_info fci;
    zend_fcall_info_cache fci_cache;
    QPointer<QThread> owner_thread;

    qt_php_signal_callable_target()
    {
        memset(&fci, 0, sizeof(fci));
        memset(&fci_cache, 0, sizeof(fci_cache));
        ZVAL_UNDEF(&fci.function_name);
    }
};

struct qt_php_signal_receiver_target
{
    QPointer<QObject> receiver_native;
    QPointer<QThread> owner_thread;
    std::string method_name;
};

struct qt_php_signal_listener
{
    uint64_t id{0};
    uint64_t sender_token{0};
    std::string signal_name;
    std::atomic_uint64_t generation{1};
    std::atomic_bool active{true};
    qt_php_signal_listener_target_type target_type{qt_php_signal_listener_target_type::callable_target};
    qt_php_signal_callable_target callable;
    qt_php_signal_receiver_target receiver;
};

struct qt_php_signal_sender_state
{
    uint64_t token{0};
    QPointer<QObject> native;
    std::unordered_map<std::string, std::vector<uint64_t>> listener_ids_by_signal;
};

PHP_QT_API std::atomic_uint64_t &qt_php_signal_next_sender_token();
PHP_QT_API std::atomic_uint64_t &qt_php_signal_next_listener_id();
PHP_QT_API std::unordered_map<uint64_t, qt_php_signal_sender_state> &qt_php_signal_sender_registry();
PHP_QT_API std::unordered_map<QObject *, uint64_t> &qt_php_signal_sender_native_index();
PHP_QT_API std::unordered_map<uint64_t, std::shared_ptr<qt_php_signal_listener>> &qt_php_signal_listener_registry();
PHP_QT_API std::unordered_map<QObject *, std::unordered_set<uint64_t>> &qt_php_signal_receiver_index();
PHP_QT_API std::mutex &qt_php_signal_registry_mutex();
PHP_QT_API int qt_php_signal_dispatch_event_type(void);

class qt_php_signal_dispatch_event final : public QEvent
{
public:
    enum class kind : uint8_t
    {
        delivery = 0,
        cleanup,
    };

    struct delivery_record
    {
        uint64_t sender_token{0};
        uint64_t listener_id{0};
        uint64_t generation{0};
        uint8_t retry_count{0};
        std::vector<qt_php_signal_value> args;
    };

    explicit qt_php_signal_dispatch_event(delivery_record record_value)
        : QEvent((QEvent::Type) qt_php_signal_dispatch_event::event_type())
        , event_kind(kind::delivery)
        , delivery(std::move(record_value))
    {
    }

    explicit qt_php_signal_dispatch_event(std::shared_ptr<qt_php_signal_listener> cleanup_listener)
        : QEvent((QEvent::Type) qt_php_signal_dispatch_event::event_type())
        , event_kind(kind::cleanup)
        , cleanup_target(std::move(cleanup_listener))
    {
    }

    static int event_type()
    {
        return qt_php_signal_dispatch_event_type();
    }

    kind event_kind{kind::delivery};
    delivery_record delivery;
    std::shared_ptr<qt_php_signal_listener> cleanup_target;
};

static inline void qt_php_signal_cleanup_listener(const std::shared_ptr<qt_php_signal_listener> &listener);
static inline void qt_php_signal_dispatch_delivery(const qt_php_signal_dispatch_event::delivery_record &delivery);

class qt_php_signal_dispatcher final : public QObject
{
public:
    bool event(QEvent *event) override
    {
        if (event == NULL || event->type() != qt_php_signal_dispatch_event::event_type()) {
            return QObject::event(event);
        }

        auto *dispatch_event = static_cast<qt_php_signal_dispatch_event *>(event);
        if (dispatch_event->event_kind == qt_php_signal_dispatch_event::kind::cleanup) {
            qt_php_signal_cleanup_listener(dispatch_event->cleanup_target);
            return true;
        }

        qt_php_signal_dispatch_delivery(dispatch_event->delivery);
        return true;
    }
};

PHP_QT_API std::unordered_map<QThread *, QPointer<qt_php_signal_dispatcher>> &qt_php_signal_dispatcher_registry();
PHP_QT_API std::mutex &qt_php_signal_dispatcher_registry_mutex();
PHP_QT_API std::unordered_map<QThread *, std::vector<qt_php_signal_dispatch_event::delivery_record>> &qt_php_signal_pending_delivery_registry();
PHP_QT_API std::mutex &qt_php_signal_pending_delivery_registry_mutex();

static inline qt_php_signal_dispatcher *qt_php_signal_dispatcher_for_thread(QThread *thread)
{
    if (thread == NULL) {
        return NULL;
    }

    std::lock_guard<std::mutex> lock(qt_php_signal_dispatcher_registry_mutex());
    auto it = qt_php_signal_dispatcher_registry().find(thread);
    if (it == qt_php_signal_dispatcher_registry().end()) {
        return NULL;
    }

    return it->second.data();
}

static inline qt_php_signal_dispatcher *qt_php_signal_ensure_current_thread_dispatcher(void)
{
    QThread *thread = QThread::currentThread();
    QThread *bound_thread = qt_qthreadruntime_current_bound_thread();
    if (thread == NULL) {
        return NULL;
    }

    {
        std::lock_guard<std::mutex> lock(qt_php_signal_dispatcher_registry_mutex());
        auto it = qt_php_signal_dispatcher_registry().find(thread);
        if (it != qt_php_signal_dispatcher_registry().end() && !it->second.isNull()) {
            return it->second.data();
        }
        if (bound_thread != NULL && bound_thread != thread) {
            auto bound_it = qt_php_signal_dispatcher_registry().find(bound_thread);
            if (bound_it != qt_php_signal_dispatcher_registry().end() && !bound_it->second.isNull()) {
                qt_php_signal_dispatcher_registry()[thread] = bound_it->second;
                return bound_it->second.data();
            }
        }
    }

    auto *dispatcher = new qt_php_signal_dispatcher();
    {
        std::lock_guard<std::mutex> lock(qt_php_signal_dispatcher_registry_mutex());
        qt_php_signal_dispatcher_registry()[thread] = dispatcher;
        if (bound_thread != NULL && bound_thread != thread) {
            qt_php_signal_dispatcher_registry()[bound_thread] = dispatcher;
        }
    }

    {
        std::vector<qt_php_signal_dispatch_event::delivery_record> pending;
        {
            std::lock_guard<std::mutex> lock(qt_php_signal_pending_delivery_registry_mutex());
            for (auto registry_it = qt_php_signal_pending_delivery_registry().begin();
                 registry_it != qt_php_signal_pending_delivery_registry().end();) {
                auto &bucket = registry_it->second;
                auto bucket_it = bucket.begin();
                while (bucket_it != bucket.end()) {
                    QThread *listener_thread = NULL;
                    {
                        std::lock_guard<std::mutex> listener_lock(qt_php_signal_registry_mutex());
                        auto listener_it = qt_php_signal_listener_registry().find(bucket_it->listener_id);
                        if (listener_it != qt_php_signal_listener_registry().end()) {
                            auto listener = listener_it->second;
                            if (listener && listener->target_type == qt_php_signal_listener_target_type::receiver_method_target) {
                                listener_thread = listener->receiver.owner_thread.data();
                            }
                        }
                    }

                    if (listener_thread == thread || (bound_thread != NULL && listener_thread == bound_thread)) {
                        pending.push_back(std::move(*bucket_it));
                        bucket_it = bucket.erase(bucket_it);
                        continue;
                    }

                    ++bucket_it;
                }

                if (bucket.empty()) {
                    registry_it = qt_php_signal_pending_delivery_registry().erase(registry_it);
                } else {
                    ++registry_it;
                }
            }
        }

        for (auto &delivery : pending) {
            qt_php_signal_debug_log("flush-pending-delivery");
            QCoreApplication::postEvent(dispatcher, new qt_php_signal_dispatch_event(std::move(delivery)));
        }
    }

    QObject::connect(thread, &QObject::destroyed, [thread]() {
        std::lock_guard<std::mutex> lock(qt_php_signal_dispatcher_registry_mutex());
        qt_php_signal_dispatcher_registry().erase(thread);
        std::lock_guard<std::mutex> pending_lock(qt_php_signal_pending_delivery_registry_mutex());
        qt_php_signal_pending_delivery_registry().erase(thread);
    });

    return dispatcher;
}

static inline void qt_php_signal_cleanup_listener(const std::shared_ptr<qt_php_signal_listener> &listener)
{
    if (!listener || listener->target_type != qt_php_signal_listener_target_type::callable_target) {
        return;
    }

    if (!qt_runtime_can_call_zend()) {
        return;
    }

    listener->callable.fci.params = NULL;
    listener->callable.fci.param_count = 0;
    listener->callable.fci.retval = NULL;
    if (!Z_ISUNDEF(listener->callable.fci.function_name)) {
        zval_ptr_dtor(&listener->callable.fci.function_name);
        ZVAL_UNDEF(&listener->callable.fci.function_name);
    }
}

static inline void qt_php_signal_schedule_listener_cleanup(const std::shared_ptr<qt_php_signal_listener> &listener)
{
    if (!listener || listener->target_type != qt_php_signal_listener_target_type::callable_target) {
        return;
    }

    QThread *owner_thread = listener->callable.owner_thread.data();
    if (owner_thread == NULL) {
        return;
    }

    qt_php_signal_dispatcher *dispatcher = owner_thread == QThread::currentThread()
        ? qt_php_signal_ensure_current_thread_dispatcher()
        : qt_php_signal_dispatcher_for_thread(owner_thread);
    if (dispatcher == NULL) {
        return;
    }

    QCoreApplication::postEvent(dispatcher, new qt_php_signal_dispatch_event(listener));
}

static inline uint64_t qt_php_signal_ensure_sender_token(QObject *native)
{
    if (native == NULL) {
        return 0;
    }

    {
        std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
        auto it = qt_php_signal_sender_native_index().find(native);
        if (it != qt_php_signal_sender_native_index().end()) {
            return it->second;
        }
    }

    const uint64_t token = qt_php_signal_next_sender_token().fetch_add(1, std::memory_order_acq_rel);
    {
        std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
        auto existing = qt_php_signal_sender_native_index().find(native);
        if (existing != qt_php_signal_sender_native_index().end()) {
            return existing->second;
        }

        qt_php_signal_sender_native_index()[native] = token;
        qt_php_signal_sender_registry()[token] = qt_php_signal_sender_state{
            token,
            native,
            {},
        };
    }

    QObject::connect(native, &QObject::destroyed, [native]() {
        std::vector<std::shared_ptr<qt_php_signal_listener>> cleanup_listeners;
        {
            std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
            auto token_it = qt_php_signal_sender_native_index().find(native);
            if (token_it == qt_php_signal_sender_native_index().end()) {
                return;
            }

            const uint64_t token = token_it->second;
            qt_php_signal_sender_native_index().erase(token_it);
            auto sender_it = qt_php_signal_sender_registry().find(token);
            if (sender_it != qt_php_signal_sender_registry().end()) {
                for (auto &[signal_name, listener_ids] : sender_it->second.listener_ids_by_signal) {
                    (void) signal_name;
                    for (uint64_t listener_id : listener_ids) {
                        auto listener_it = qt_php_signal_listener_registry().find(listener_id);
                        if (listener_it == qt_php_signal_listener_registry().end()) {
                            continue;
                        }
                        auto listener = listener_it->second;
                        listener->active.store(false, std::memory_order_release);
                        if (listener->target_type == qt_php_signal_listener_target_type::receiver_method_target) {
                            QObject *receiver_native = listener->receiver.receiver_native.data();
                            if (receiver_native != NULL) {
                                auto receiver_it = qt_php_signal_receiver_index().find(receiver_native);
                                if (receiver_it != qt_php_signal_receiver_index().end()) {
                                    receiver_it->second.erase(listener_id);
                                    if (receiver_it->second.empty()) {
                                        qt_php_signal_receiver_index().erase(receiver_it);
                                    }
                                }
                            }
                        } else {
                            cleanup_listeners.push_back(listener);
                        }
                        qt_php_signal_listener_registry().erase(listener_it);
                    }
                }
                qt_php_signal_sender_registry().erase(sender_it);
            }
        }

        for (const auto &listener : cleanup_listeners) {
            qt_php_signal_schedule_listener_cleanup(listener);
        }
    });

    return token;
}

static inline void qt_php_signal_register_receiver_destroy_hook(QObject *receiver_native)
{
    if (receiver_native == NULL) {
        return;
    }

    QObject::connect(receiver_native, &QObject::destroyed, [receiver_native]() {
        std::vector<std::shared_ptr<qt_php_signal_listener>> cleanup_listeners;
        {
            std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
            auto receiver_it = qt_php_signal_receiver_index().find(receiver_native);
            if (receiver_it == qt_php_signal_receiver_index().end()) {
                return;
            }

            std::vector<uint64_t> listener_ids(receiver_it->second.begin(), receiver_it->second.end());
            qt_php_signal_receiver_index().erase(receiver_it);

            for (uint64_t listener_id : listener_ids) {
                auto listener_it = qt_php_signal_listener_registry().find(listener_id);
                if (listener_it == qt_php_signal_listener_registry().end()) {
                    continue;
                }

                auto listener = listener_it->second;
                listener->active.store(false, std::memory_order_release);
                auto sender_it = qt_php_signal_sender_registry().find(listener->sender_token);
                if (sender_it != qt_php_signal_sender_registry().end()) {
                    auto vector_it = sender_it->second.listener_ids_by_signal.find(listener->signal_name);
                    if (vector_it != sender_it->second.listener_ids_by_signal.end()) {
                        vector_it->second.erase(
                            std::remove(vector_it->second.begin(), vector_it->second.end(), listener_id),
                            vector_it->second.end()
                        );
                        if (vector_it->second.empty()) {
                            sender_it->second.listener_ids_by_signal.erase(vector_it);
                        }
                    }
                }

                if (listener->target_type == qt_php_signal_listener_target_type::callable_target) {
                    cleanup_listeners.push_back(listener);
                }
                qt_php_signal_listener_registry().erase(listener_it);
            }
        }

        for (const auto &listener : cleanup_listeners) {
            qt_php_signal_schedule_listener_cleanup(listener);
        }
    });
}

static inline bool qt_php_signal_disconnect_listener_impl(
    uint64_t sender_token,
    uint64_t listener_id,
    uint64_t generation,
    std::shared_ptr<qt_php_signal_listener> *cleanup_listener_out
)
{
    std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
    auto sender_it = qt_php_signal_sender_registry().find(sender_token);
    auto listener_it = qt_php_signal_listener_registry().find(listener_id);
    if (sender_it == qt_php_signal_sender_registry().end() || listener_it == qt_php_signal_listener_registry().end()) {
        return false;
    }

    auto listener = listener_it->second;
    if (listener->sender_token != sender_token) {
        return false;
    }

    if (generation != 0 && listener->generation.load(std::memory_order_acquire) != generation) {
        return false;
    }

    listener->active.store(false, std::memory_order_release);

    auto vector_it = sender_it->second.listener_ids_by_signal.find(listener->signal_name);
    if (vector_it != sender_it->second.listener_ids_by_signal.end()) {
        vector_it->second.erase(
            std::remove(vector_it->second.begin(), vector_it->second.end(), listener_id),
            vector_it->second.end()
        );
        if (vector_it->second.empty()) {
            sender_it->second.listener_ids_by_signal.erase(vector_it);
        }
    }

    if (listener->target_type == qt_php_signal_listener_target_type::receiver_method_target) {
        QObject *receiver_native = listener->receiver.receiver_native.data();
        if (receiver_native != NULL) {
            auto receiver_it = qt_php_signal_receiver_index().find(receiver_native);
            if (receiver_it != qt_php_signal_receiver_index().end()) {
                receiver_it->second.erase(listener_id);
                if (receiver_it->second.empty()) {
                    qt_php_signal_receiver_index().erase(receiver_it);
                }
            }
        }
    }

    qt_php_signal_listener_registry().erase(listener_it);
    if (cleanup_listener_out != NULL && listener->target_type == qt_php_signal_listener_target_type::callable_target) {
        *cleanup_listener_out = listener;
    }

    return true;
}

PHP_QT_API bool qt_php_signal_disconnect_listener(
    uint64_t sender_token,
    uint64_t listener_id,
    uint64_t generation
);

static inline void qt_php_signal_on_object_moved(QObject *native_object, QThread *target_thread)
{
    if (native_object == NULL || target_thread == NULL) {
        return;
    }

    std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
    auto receiver_it = qt_php_signal_receiver_index().find(native_object);
    if (receiver_it == qt_php_signal_receiver_index().end()) {
        return;
    }

    for (uint64_t listener_id : receiver_it->second) {
        auto listener_it = qt_php_signal_listener_registry().find(listener_id);
        if (listener_it == qt_php_signal_listener_registry().end()) {
            continue;
        }
        auto listener = listener_it->second;
        if (listener->target_type != qt_php_signal_listener_target_type::receiver_method_target) {
            continue;
        }
        listener->receiver.owner_thread = target_thread;
        listener->generation.fetch_add(1, std::memory_order_acq_rel);
    }
}

static inline bool qt_php_signal_invoke_callable(
    const std::shared_ptr<qt_php_signal_listener> &listener,
    const std::vector<qt_php_signal_value> &args
)
{
    if (!listener || listener->target_type != qt_php_signal_listener_target_type::callable_target || !qt_runtime_can_call_zend()) {
        return false;
    }

    std::vector<zval> params;
    params.reserve(args.size());
    for (const qt_php_signal_value &arg : args) {
        zval param;
        ZVAL_NULL(&param);
        if (!qt_php_signal_value_to_zval(arg, &param)) {
            for (zval &cleanup : params) {
                zval_ptr_dtor(&cleanup);
            }
            return false;
        }
        params.push_back(param);
    }

    zval retval;
    ZVAL_NULL(&retval);
    zval *previous_params = listener->callable.fci.params;
    uint32_t previous_param_count = listener->callable.fci.param_count;
    zval *previous_retval = listener->callable.fci.retval;

    listener->callable.fci.params = params.empty() ? NULL : params.data();
    listener->callable.fci.param_count = (uint32_t) params.size();
    listener->callable.fci.retval = &retval;

    const bool ok = zend_call_function(&listener->callable.fci, &listener->callable.fci_cache) == SUCCESS;
    listener->callable.fci.params = previous_params;
    listener->callable.fci.param_count = previous_param_count;
    listener->callable.fci.retval = previous_retval;
    zval_ptr_dtor(&retval);

    for (zval &cleanup : params) {
        zval_ptr_dtor(&cleanup);
    }

    return ok;
}

enum class qt_php_signal_receiver_invoke_result : uint8_t
{
    invoked = 0,
    unavailable,
    failed,
};

static inline qt_php_signal_receiver_invoke_result qt_php_signal_invoke_receiver(
    const std::shared_ptr<qt_php_signal_listener> &listener,
    QObject *sender_native,
    const std::vector<qt_php_signal_value> &args
)
{
    if (!listener || listener->target_type != qt_php_signal_listener_target_type::receiver_method_target || !qt_runtime_can_call_zend()) {
        return qt_php_signal_receiver_invoke_result::failed;
    }

    QObject *receiver_native = listener->receiver.receiver_native.data();
    if (receiver_native == NULL) {
        return qt_php_signal_receiver_invoke_result::failed;
    }

    zend_object *target_object = qt_php_signal_resolve_current_thread_live_wrapper(receiver_native);
    if (target_object == NULL) {
        if (qt_qthreadruntime_has_moved_object(receiver_native) && receiver_native->thread() == QThread::currentThread()) {
            qt_php_signal_debug_log("receiver-live-wrapper-unavailable");
            return qt_php_signal_receiver_invoke_result::unavailable;
        }
        qt_php_signal_debug_log("receiver-live-wrapper-missing");
        return qt_php_signal_receiver_invoke_result::failed;
    }

    std::vector<zval> params;
    params.reserve(args.size());
    for (const qt_php_signal_value &arg : args) {
        zval param;
        ZVAL_NULL(&param);
        if (!qt_php_signal_value_to_zval(arg, &param)) {
            for (zval &cleanup : params) {
                zval_ptr_dtor(&cleanup);
            }
            return qt_php_signal_receiver_invoke_result::failed;
        }
        params.push_back(param);
    }

    qt_qobject_sender_override_scope sender_scope(sender_native, -1);
    zval retval;
    ZVAL_NULL(&retval);
    const bool ok = qt_call_php_method(
        target_object,
        listener->receiver.method_name.c_str(),
        &retval,
        (uint32_t) params.size(),
        params.empty() ? NULL : params.data()
    );
    if (!ok) {
        qt_php_signal_debug_log("receiver-method-call-failed");
    }
    zval_ptr_dtor(&retval);
    for (zval &cleanup : params) {
        zval_ptr_dtor(&cleanup);
    }

    return ok
        ? qt_php_signal_receiver_invoke_result::invoked
        : qt_php_signal_receiver_invoke_result::failed;
}

static inline void qt_php_signal_dispatch_delivery(const qt_php_signal_dispatch_event::delivery_record &delivery)
{
    std::shared_ptr<qt_php_signal_listener> listener;
    QObject *sender_native = NULL;
    {
        std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
        auto sender_it = qt_php_signal_sender_registry().find(delivery.sender_token);
        if (sender_it == qt_php_signal_sender_registry().end() || sender_it->second.native.isNull()) {
            return;
        }
        sender_native = sender_it->second.native.data();

        auto listener_it = qt_php_signal_listener_registry().find(delivery.listener_id);
        if (listener_it == qt_php_signal_listener_registry().end()) {
            return;
        }
        listener = listener_it->second;
    }

    if (!listener || !listener->active.load(std::memory_order_acquire)) {
        return;
    }

    if (listener->generation.load(std::memory_order_acquire) != delivery.generation) {
        return;
    }

    if (listener->target_type == qt_php_signal_listener_target_type::callable_target) {
        (void) qt_php_signal_invoke_callable(listener, delivery.args);
        return;
    }

    qt_php_signal_receiver_invoke_result receiver_result = qt_php_signal_invoke_receiver(listener, sender_native, delivery.args);
    if (receiver_result == qt_php_signal_receiver_invoke_result::unavailable && delivery.retry_count < 8) {
        qt_php_signal_dispatcher *dispatcher = qt_php_signal_ensure_current_thread_dispatcher();
        if (dispatcher != NULL) {
            qt_php_signal_dispatch_event::delivery_record retry = delivery;
            retry.retry_count++;
            qt_php_signal_debug_log("receiver-delivery-retry");
            QCoreApplication::postEvent(dispatcher, new qt_php_signal_dispatch_event(std::move(retry)));
        }
    }
}

static inline bool qt_php_signal_enqueue_delivery(
    const std::shared_ptr<qt_php_signal_listener> &listener,
    uint64_t sender_token,
    std::vector<qt_php_signal_value> args,
    std::string *error
)
{
    if (!listener) {
        return false;
    }

    QThread *target_thread = listener->target_type == qt_php_signal_listener_target_type::callable_target
        ? listener->callable.owner_thread.data()
        : listener->receiver.owner_thread.data();
    if (target_thread == NULL) {
        if (error != NULL) {
            *error = "Target thread is unavailable for PHP signal delivery.";
        }
        return false;
    }

    qt_php_signal_dispatcher *dispatcher = target_thread == QThread::currentThread()
        ? qt_php_signal_ensure_current_thread_dispatcher()
        : qt_php_signal_dispatcher_for_thread(target_thread);
    qt_php_signal_dispatch_event::delivery_record delivery;
    delivery.sender_token = sender_token;
    delivery.listener_id = listener->id;
    delivery.generation = listener->generation.load(std::memory_order_acquire);
    delivery.args = std::move(args);

    if (dispatcher == NULL) {
        if (target_thread != QThread::currentThread()) {
            qt_php_signal_debug_log("queue-pending-delivery");
            std::lock_guard<std::mutex> lock(qt_php_signal_pending_delivery_registry_mutex());
            qt_php_signal_pending_delivery_registry()[target_thread].push_back(std::move(delivery));
            return true;
        }

        if (error != NULL) {
            *error = "Target dispatcher is unavailable for PHP signal delivery.";
        }
        return false;
    }
    QCoreApplication::postEvent(dispatcher, new qt_php_signal_dispatch_event(std::move(delivery)));
    return true;
}

static inline bool qt_php_signal_register_callable_listener(
    zend_class_entry *sender_ce,
    QObject *sender_native,
    zend_string *signal_name,
    zval *listener_zv,
    uint64_t *sender_token_out,
    uint64_t *listener_id_out,
    uint64_t *generation_out,
    std::string *error
)
{
    const qt_php_signal_declared_signal *signal = qt_php_signal_find_declared_signal(sender_ce, signal_name, error);
    if (signal == NULL) {
        return false;
    }

    if (qt_php_signal_ensure_current_thread_dispatcher() == NULL) {
        if (error != NULL) {
            *error = "Current thread does not have a PHP signal dispatcher.";
        }
        return false;
    }

    auto listener = std::make_shared<qt_php_signal_listener>();
    listener->id = qt_php_signal_next_listener_id().fetch_add(1, std::memory_order_acq_rel);
    listener->sender_token = qt_php_signal_ensure_sender_token(sender_native);
    listener->signal_name = signal->lookup_name;
    listener->target_type = qt_php_signal_listener_target_type::callable_target;
    listener->callable.owner_thread = QThread::currentThread();

    char *callable_error = NULL;
    if (zend_fcall_info_init(listener_zv, 0, &listener->callable.fci, &listener->callable.fci_cache, NULL, &callable_error) != SUCCESS) {
        if (error != NULL) {
            *error = callable_error != NULL ? callable_error : "Listener is not callable.";
        }
        if (callable_error != NULL) {
            efree(callable_error);
        }
        return false;
    }
    if (callable_error != NULL) {
        efree(callable_error);
    }
    Z_TRY_ADDREF(listener->callable.fci.function_name);

    {
        std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
        qt_php_signal_listener_registry()[listener->id] = listener;
        qt_php_signal_sender_registry()[listener->sender_token].listener_ids_by_signal[signal->lookup_name].push_back(listener->id);
    }

    if (sender_token_out != NULL) {
        *sender_token_out = listener->sender_token;
    }
    if (listener_id_out != NULL) {
        *listener_id_out = listener->id;
    }
    if (generation_out != NULL) {
        *generation_out = listener->generation.load(std::memory_order_acquire);
    }

    return true;
}

static inline bool qt_php_signal_register_receiver_listener(
    zend_class_entry *sender_ce,
    QObject *sender_native,
    zend_string *signal_name,
    QObject *receiver_native,
    zend_object *receiver_object,
    zend_string *method_name,
    uint64_t *sender_token_out,
    uint64_t *listener_id_out,
    uint64_t *generation_out,
    std::string *error
)
{
    const qt_php_signal_declared_signal *signal = qt_php_signal_find_declared_signal(sender_ce, signal_name, error);
    if (signal == NULL) {
        return false;
    }

    if (receiver_native == NULL || receiver_object == NULL || method_name == NULL) {
        if (error != NULL) {
            *error = "Receiver target is not initialized for PHP signal registration.";
        }
        return false;
    }

    zend_function *method = qt_lookup_method(receiver_object->ce, ZSTR_VAL(method_name));
    if (method == NULL) {
        if (error != NULL) {
            *error = std::string("Unknown receiver method ") + ZSTR_VAL(method_name) + ".";
        }
        return false;
    }
    if ((method->common.fn_flags & ZEND_ACC_STATIC) != 0) {
        if (error != NULL) {
            *error = std::string("Receiver method ") + ZSTR_VAL(method_name) + " must be an instance method.";
        }
        return false;
    }
    if (method->common.required_num_args > signal->types.size()) {
        if (error != NULL) {
            *error = std::string("Receiver method ") + ZSTR_VAL(method_name) + " requires more arguments than PHP signal " + signal->name + ".";
        }
        return false;
    }

    QThread *owner_thread = receiver_native->thread();
    if (owner_thread == QThread::currentThread() && qt_php_signal_ensure_current_thread_dispatcher() == NULL) {
        if (error != NULL) {
            *error = "Current receiver thread does not have a PHP signal dispatcher.";
        }
        return false;
    }

    auto listener = std::make_shared<qt_php_signal_listener>();
    listener->id = qt_php_signal_next_listener_id().fetch_add(1, std::memory_order_acq_rel);
    listener->sender_token = qt_php_signal_ensure_sender_token(sender_native);
    listener->signal_name = signal->lookup_name;
    listener->target_type = qt_php_signal_listener_target_type::receiver_method_target;
    listener->receiver.receiver_native = receiver_native;
    listener->receiver.owner_thread = owner_thread;
    listener->receiver.method_name.assign(ZSTR_VAL(method_name), ZSTR_LEN(method_name));

    {
        std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
        qt_php_signal_listener_registry()[listener->id] = listener;
        qt_php_signal_sender_registry()[listener->sender_token].listener_ids_by_signal[signal->lookup_name].push_back(listener->id);
        qt_php_signal_receiver_index()[receiver_native].insert(listener->id);
    }
    qt_php_signal_register_receiver_destroy_hook(receiver_native);

    if (sender_token_out != NULL) {
        *sender_token_out = listener->sender_token;
    }
    if (listener_id_out != NULL) {
        *listener_id_out = listener->id;
    }
    if (generation_out != NULL) {
        *generation_out = listener->generation.load(std::memory_order_acquire);
    }

    return true;
}

static inline bool qt_php_signal_emit(
    zend_class_entry *sender_ce,
    QObject *sender_native,
    zend_string *signal_name,
    zval *args,
    std::string *error
)
{
    const qt_php_signal_declared_signal *signal = qt_php_signal_find_declared_signal(sender_ce, signal_name, error);
    if (signal == NULL) {
        return false;
    }

    if (args == NULL || Z_TYPE_P(args) != IS_ARRAY) {
        if (error != NULL) {
            *error = "PHP signal emit() requires an array payload.";
        }
        return false;
    }

    const uint32_t arg_count = (uint32_t) zend_hash_num_elements(Z_ARRVAL_P(args));
    if (arg_count != signal->types.size()) {
        if (error != NULL) {
            *error = std::string("PHP signal ")
                + signal->name
                + " expects "
                + std::to_string(signal->types.size())
                + " argument(s), "
                + std::to_string(arg_count)
                + " provided.";
        }
        return false;
    }

    std::vector<qt_php_signal_value> snapshot_args;
    snapshot_args.reserve(signal->types.size());
    uint32_t arg_index = 0;
    zval *entry = NULL;
    ZEND_HASH_FOREACH_VAL(Z_ARRVAL_P(args), entry) {
        if (entry == NULL) {
            if (error != NULL) {
                *error = "PHP signal payload contains an invalid argument.";
            }
            return false;
        }

        if (!qt_php_signal_validate_typed_value(entry, signal->types[arg_index], error)) {
            return false;
        }

        qt_php_signal_value snapshot;
        if (!qt_php_signal_zval_to_value(entry, &snapshot, error)) {
            return false;
        }
        snapshot_args.push_back(std::move(snapshot));
        arg_index++;
    } ZEND_HASH_FOREACH_END();

    const uint64_t sender_token = qt_php_signal_ensure_sender_token(sender_native);
    std::vector<uint64_t> listener_ids;
    {
        std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
        auto sender_it = qt_php_signal_sender_registry().find(sender_token);
        if (sender_it == qt_php_signal_sender_registry().end()) {
            return true;
        }
        auto vector_it = sender_it->second.listener_ids_by_signal.find(signal->lookup_name);
        if (vector_it == sender_it->second.listener_ids_by_signal.end()) {
            return true;
        }
        listener_ids = vector_it->second;
    }

    for (uint64_t listener_id : listener_ids) {
        std::shared_ptr<qt_php_signal_listener> listener;
        {
            std::lock_guard<std::mutex> lock(qt_php_signal_registry_mutex());
            auto listener_it = qt_php_signal_listener_registry().find(listener_id);
            if (listener_it == qt_php_signal_listener_registry().end()) {
                continue;
            }
            listener = listener_it->second;
        }

        if (!listener || !listener->active.load(std::memory_order_acquire)) {
            continue;
        }

        std::vector<qt_php_signal_value> delivery_args = snapshot_args;
        std::string delivery_error;
        (void) qt_php_signal_enqueue_delivery(listener, sender_token, std::move(delivery_args), &delivery_error);
    }

    return true;
}

#endif /* QT_PHP_SIGNAL_HELPERS_H */
