/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Qt\Core\QFuture support declarations.
 */

#ifndef QT_QFUTURE_H
#define QT_QFUTURE_H

#include "qt_qthreadruntime.h"

#endif /* QT_QFUTURE_H */
