/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Dynamic QMetaObject bridge for PHP QObject subclasses with
 * #[Slot] and #[Signal] attributes.
 *
 * When a PHP class extending Qt\Core\QObject declares methods
 * annotated with #[Slot] or #[Signal], the constructor creates
 * a QtPhpMetaObjectBridge instance instead of a plain QObject.
 * This bridge builds a dynamic QMetaObject containing those
 * methods so they are visible to QML and Qt's meta-object system.
 */

#ifndef QT_METAOBJECT_BRIDGE_H
#define QT_METAOBJECT_BRIDGE_H

#include "qt_php_compat.h"
#include "qt_qobject_helpers.h"

#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#ifdef __cplusplus
}
#endif

#include <QMetaObject>
#include <QMetaMethod>
#include <QObject>
#include <QVariant>
#include <cstring>
#include <string>
#include <vector>
#include <unordered_map>

#include <private/qmetaobjectbuilder_p.h>

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

struct qt_php_metaobject_method_entry
{
    std::string name;
    enum class kind_t : uint8_t
    {
        slot_method = 0,
        signal_method,
    } kind;
    std::vector<std::string> param_types;
    int qt_method_index{-1};
};

struct qt_php_metaobject_class_metadata
{
    bool valid{false};
    std::string error;
    std::vector<qt_php_metaobject_method_entry> methods;
    std::unordered_map<std::string, size_t> method_by_name;
};

PHP_QT_API std::unordered_map<zend_class_entry *, std::shared_ptr<qt_php_metaobject_class_metadata>> &qt_php_metaobject_metadata_registry();
PHP_QT_API std::mutex &qt_php_metaobject_metadata_registry_mutex();
PHP_QT_API std::unordered_map<QObject *, qt_php_metaobject_class_metadata *> &qt_php_metaobject_instance_registry();
PHP_QT_API std::mutex &qt_php_metaobject_instance_registry_mutex();

static inline const char *qt_php_metaobject_type_token_to_qt_type(const std::string &token)
{
    const std::string lowered = [] (const std::string &v) {
        std::string out = v;
        for (char &ch : out) { ch = (char) std::tolower((unsigned char) ch); }
        return out;
    }(token);

    if (lowered == "bool") return "bool";
    if (lowered == "int") return "int";
    if (lowered == "float") return "double";
    if (lowered == "string") return "QString";
    if (lowered == "array" || lowered == "mixed") return "QVariant";
    if (lowered == "qobject") return "QObject*";
    return nullptr;
}

static inline int qt_php_metaobject_type_token_to_qmetatype(const std::string &token)
{
    const std::string lowered = [] (const std::string &v) {
        std::string out = v;
        for (char &ch : out) { ch = (char) std::tolower((unsigned char) ch); }
        return out;
    }(token);

    if (lowered == "bool") return QMetaType::Bool;
    if (lowered == "int") return QMetaType::Int;
    if (lowered == "float") return QMetaType::Double;
    if (lowered == "string") return QMetaType::QString;
    if (lowered == "array" || lowered == "mixed") return QMetaType::QVariant;
    if (lowered == "qobject") return QMetaType::QObjectStar;
    return QMetaType::UnknownType;
}

PHP_QT_API std::shared_ptr<qt_php_metaobject_class_metadata> qt_php_metaobject_build_class_metadata(zend_class_entry *ce);

static inline std::shared_ptr<const qt_php_metaobject_class_metadata> qt_php_metaobject_metadata_for_ce(zend_class_entry *ce, std::string *error)
{
    if (ce == NULL) {
        if (error) *error = "Missing class entry for meta-object metadata.";
        return nullptr;
    }

    {
        std::lock_guard<std::mutex> lock(qt_php_metaobject_metadata_registry_mutex());
        auto it = qt_php_metaobject_metadata_registry().find(ce);
        if (it != qt_php_metaobject_metadata_registry().end()) {
            if (!it->second->valid && error) *error = it->second->error;
            return it->second;
        }
    }

    auto metadata = qt_php_metaobject_build_class_metadata(ce);
    {
        std::lock_guard<std::mutex> lock(qt_php_metaobject_metadata_registry_mutex());
        qt_php_metaobject_metadata_registry()[ce] = metadata;
    }

    if (!metadata->valid && error) *error = metadata->error;
    return metadata;
}

static inline bool qt_php_metaobject_class_needs_bridging(zend_class_entry *ce)
{
    if (ce == NULL) return false;
    auto metadata = qt_php_metaobject_metadata_for_ce(ce, nullptr);
    return metadata && metadata->valid && !metadata->methods.empty();
}

class QtPhpMetaObjectBridge : public QObject
{
public:
    explicit QtPhpMetaObjectBridge(QObject *parent, zend_class_entry *phpCe, zend_object *phpObject);
    ~QtPhpMetaObjectBridge() override;

    const QMetaObject *metaObject() const override;
    int qt_metacall(QMetaObject::Call call, int id, void **args) override;

    void activatePhpSignal(const char *signalName, int argc, void **argv);

    zend_object *phpObject() const { return m_phpObject; }
    qt_php_metaobject_class_metadata *classMetadata() const { return m_classMetadata; }

private:
    void buildDynamicMetaObject();

    zend_class_entry *m_phpCe;
    zend_object *m_phpObject;
    qt_php_metaobject_class_metadata *m_classMetadata;

    QMetaObject *m_dynamicMetaObject;
    bool m_metaObjectBuilt{false};

    std::unordered_map<std::string, int> m_signalIndexByName;
};

PHP_QT_API void qt_php_metaobject_register_bridge(QObject *native, QtPhpMetaObjectBridge *bridge);
PHP_QT_API void qt_php_metaobject_unregister_bridge(QObject *native);
PHP_QT_API QtPhpMetaObjectBridge *qt_php_metaobject_bridge_for_native(QObject *native);

PHP_QT_API zend_function *qt_php_metaobject_get_method(zend_object **object, zend_string *method_name, const zval *key);
PHP_QT_API void qt_php_metaobject_signal_trampoline(INTERNAL_FUNCTION_PARAMETERS);

#endif /* QT_METAOBJECT_BRIDGE_H */
