/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Dynamic QMetaObject bridge implementation.
 */

#include "qt_qmetaobject_bridge.h"
#include "qt_php_signal_helpers.h"
#include "qt_slotattribute.h"

#ifdef __cplusplus
extern "C" {
#endif
#include "zend_interfaces.h"
#ifdef __cplusplus
}
#endif

static constexpr const char *QT_PHP_SLOT_ATTRIBUTE_LCNAME = "qt\\core\\attributes\\slot";
static constexpr int QT_PHP_SLOT_ATTRIBUTE_LCNAME_LEN = sizeof("qt\\core\\attributes\\slot") - 1;

static inline std::string qt_php_metaobject_lower(const char *value, size_t length)
{
    std::string out(value, length);
    for (char &ch : out) { ch = (char) std::tolower((unsigned char) ch); }
    return out;
}

static inline zend_attribute *qt_php_slot_attribute_for_function(zend_function *func)
{
    if (func == NULL) return NULL;
    return zend_get_attribute_str(
        func->common.attributes,
        QT_PHP_SLOT_ATTRIBUTE_LCNAME,
        QT_PHP_SLOT_ATTRIBUTE_LCNAME_LEN
    );
}

static inline bool qt_php_slot_type_token_is_valid(const std::string &token)
{
    if (token.empty()) return false;
    const std::string lowered = qt_php_metaobject_lower(token.c_str(), token.size());
    if (lowered == "bool" || lowered == "int" || lowered == "float"
        || lowered == "string" || lowered == "array" || lowered == "mixed"
        || lowered == "qobject") {
        return true;
    }
    for (char ch : token) {
        if ((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z')
            || (ch >= '0' && ch <= '9') || ch == '_' || ch == '\\') {
            continue;
        }
        return false;
    }
    return true;
}

std::unordered_map<zend_class_entry *, std::shared_ptr<qt_php_metaobject_class_metadata>> &qt_php_metaobject_metadata_registry()
{
    static std::unordered_map<zend_class_entry *, std::shared_ptr<qt_php_metaobject_class_metadata>> registry;
    return registry;
}

std::mutex &qt_php_metaobject_metadata_registry_mutex()
{
    static std::mutex m;
    return m;
}

std::unordered_map<QObject *, qt_php_metaobject_class_metadata *> &qt_php_metaobject_instance_registry()
{
    static std::unordered_map<QObject *, qt_php_metaobject_class_metadata *> registry;
    return registry;
}

std::mutex &qt_php_metaobject_instance_registry_mutex()
{
    static std::mutex m;
    return m;
}

PHP_QT_API std::shared_ptr<qt_php_metaobject_class_metadata> qt_php_metaobject_build_class_metadata(zend_class_entry *ce)
{
    auto metadata = std::make_shared<qt_php_metaobject_class_metadata>();
    if (ce == NULL) {
        metadata->error = "Missing class entry.";
        return metadata;
    }

    zend_string *name = NULL;
    zval *func_zv = NULL;
    ZEND_HASH_FOREACH_STR_KEY_VAL(&ce->function_table, name, func_zv) {
        if (name == NULL || func_zv == NULL) continue;
        zend_function *func = (zend_function *) Z_PTR_P(func_zv);
        if (func == NULL) continue;

        bool is_slot = false;
        bool is_signal = false;
        zend_attribute *slot_attr = qt_php_slot_attribute_for_function(func);
        zend_attribute *signal_attr = qt_php_signal_attribute_for_function(func);

        if (slot_attr != NULL) is_slot = true;
        if (signal_attr != NULL) is_signal = true;
        if (!is_slot && !is_signal) continue;

        qt_php_metaobject_method_entry entry;
        entry.name.assign(ZSTR_VAL(func->common.function_name), ZSTR_LEN(func->common.function_name));

        if (is_slot) {
            if ((func->common.fn_flags & ZEND_ACC_PUBLIC) == 0) {
                metadata->error = std::string("Slot method ") + entry.name + " must be public.";
                return metadata;
            }
            if ((func->common.fn_flags & ZEND_ACC_STATIC) != 0) {
                metadata->error = std::string("Slot method ") + entry.name + " must be an instance method.";
                return metadata;
            }
            entry.kind = qt_php_metaobject_method_entry::kind_t::slot_method;
        } else {
            if ((func->common.fn_flags & ZEND_ACC_PUBLIC) != 0) {
                metadata->error = std::string("Signal declaration method ") + entry.name + " must be protected or private.";
                return metadata;
            }
            if ((func->common.fn_flags & ZEND_ACC_STATIC) != 0) {
                metadata->error = std::string("Signal declaration method ") + entry.name + " must be an instance method.";
                return metadata;
            }
            entry.kind = qt_php_metaobject_method_entry::kind_t::signal_method;
        }

        zend_attribute *attr = is_slot ? slot_attr : signal_attr;
        if (attr != NULL && attr->argc >= 1) {
            zval attr_value;
            ZVAL_UNDEF(&attr_value);
            if (zend_get_attribute_value(&attr_value, attr, 0, ce) != SUCCESS) {
                if (!Z_ISUNDEF(attr_value)) zval_ptr_dtor(&attr_value);
                metadata->error = entry.name + " has an invalid attribute payload.";
                return metadata;
            }
            if (Z_TYPE(attr_value) != IS_ARRAY) {
                zval_ptr_dtor(&attr_value);
                metadata->error = entry.name + " requires an array payload.";
                return metadata;
            }
            zval *type_entry = NULL;
            ZEND_HASH_FOREACH_VAL(Z_ARRVAL(attr_value), type_entry) {
                if (type_entry == NULL) continue;
                zend_string *type_str = zval_get_string(type_entry);
                if (type_str == NULL) {
                    zval_ptr_dtor(&attr_value);
                    metadata->error = entry.name + " has an invalid type token.";
                    return metadata;
                }
                std::string token(ZSTR_VAL(type_str), ZSTR_LEN(type_str));
                zend_string_release(type_str);
                bool valid = is_slot
                    ? qt_php_slot_type_token_is_valid(token)
                    : qt_php_signal_type_token_is_valid(token);
                if (!valid) {
                    zval_ptr_dtor(&attr_value);
                    metadata->error = entry.name + " has unsupported type token " + token + ".";
                    return metadata;
                }
                entry.param_types.push_back(token);
            } ZEND_HASH_FOREACH_END();
            zval_ptr_dtor(&attr_value);
        }

        size_t idx = metadata->methods.size();
        {
            std::string lcKey(entry.name);
            for (char &ch : lcKey) { ch = (char) std::tolower((unsigned char) ch); }
            metadata->method_by_name[lcKey] = idx;
        }
        metadata->methods.push_back(std::move(entry));
    } ZEND_HASH_FOREACH_END();

    metadata->valid = true;
    return metadata;
}

void qt_php_metaobject_register_bridge(QObject *native, QtPhpMetaObjectBridge *bridge)
{
    if (native == NULL || bridge == NULL) return;
    std::lock_guard<std::mutex> lock(qt_php_metaobject_instance_registry_mutex());
    qt_php_metaobject_instance_registry()[native] = bridge->classMetadata();
}

void qt_php_metaobject_unregister_bridge(QObject *native)
{
    if (native == NULL) return;
    std::lock_guard<std::mutex> lock(qt_php_metaobject_instance_registry_mutex());
    qt_php_metaobject_instance_registry().erase(native);
}

static QtPhpMetaObjectBridge *qt_php_metaobject_bridge_cast(QObject *native)
{
    if (native == NULL) return nullptr;
    std::lock_guard<std::mutex> lock(qt_php_metaobject_instance_registry_mutex());
    auto it = qt_php_metaobject_instance_registry().find(native);
    if (it == qt_php_metaobject_instance_registry().end()) return nullptr;
    return static_cast<QtPhpMetaObjectBridge *>(native);
}

QtPhpMetaObjectBridge *qt_php_metaobject_bridge_for_native(QObject *native)
{
    return qt_php_metaobject_bridge_cast(native);
}

QtPhpMetaObjectBridge::QtPhpMetaObjectBridge(QObject *parent, zend_class_entry *phpCe, zend_object *phpObject)
    : QObject(parent)
    , m_phpCe(phpCe)
    , m_phpObject(phpObject)
    , m_classMetadata(nullptr)
    , m_dynamicMetaObject(nullptr)
{
    auto metadata = qt_php_metaobject_metadata_for_ce(phpCe, nullptr);
    if (metadata && metadata->valid) {
        std::lock_guard<std::mutex> lock(qt_php_metaobject_metadata_registry_mutex());
        auto &registry = qt_php_metaobject_metadata_registry();
        m_classMetadata = registry[phpCe].get();
    }

    buildDynamicMetaObject();
    qt_php_metaobject_register_bridge(this, this);
}

QtPhpMetaObjectBridge::~QtPhpMetaObjectBridge()
{
    delete m_dynamicMetaObject;
    m_dynamicMetaObject = nullptr;
    qt_php_metaobject_unregister_bridge(this);
}

void QtPhpMetaObjectBridge::buildDynamicMetaObject()
{
    if (m_metaObjectBuilt || m_classMetadata == nullptr) return;
    if (m_classMetadata->methods.empty()) {
        m_metaObjectBuilt = true;
        return;
    }

    QMetaObjectBuilder builder;
    builder.setClassName(m_phpCe->name->val);
    builder.setSuperClass(&QObject::staticMetaObject);

    for (const auto &method : m_classMetadata->methods) {
        std::string sig = method.name + "(";
        for (size_t i = 0; i < method.param_types.size(); i++) {
            if (i > 0) sig += ",";
            const char *qtType = qt_php_metaobject_type_token_to_qt_type(method.param_types[i]);
            sig += qtType ? qtType : "QVariant";
        }
        sig += ")";

        QMetaMethodBuilder mb = (method.kind == qt_php_metaobject_method_entry::kind_t::signal_method)
            ? builder.addSignal(QByteArray::fromStdString(sig))
            : builder.addSlot(QByteArray::fromStdString(sig));

        mb.setAccess(QMetaMethod::Public);

        QList<QByteArray> paramNames;
        for (size_t i = 0; i < method.param_types.size(); i++) {
            paramNames.append(QByteArray());
        }
        if (!paramNames.isEmpty()) {
            mb.setParameterNames(paramNames);
        }
    }

    m_dynamicMetaObject = builder.toMetaObject();

    m_metaObjectBuilt = true;
}

const QMetaObject *QtPhpMetaObjectBridge::metaObject() const
{
    if (m_metaObjectBuilt && m_dynamicMetaObject) {
        return m_dynamicMetaObject;
    }
    return &QObject::staticMetaObject;
}

static inline bool qt_php_metaobject_qt_arg_to_zval(int metaType, void *arg, zval *out)
{
    if (arg == nullptr) {
        ZVAL_NULL(out);
        return true;
    }

    switch (metaType) {
        case QMetaType::Bool:
            ZVAL_BOOL(out, *static_cast<bool *>(arg));
            return true;
        case QMetaType::Int:
            ZVAL_LONG(out, *static_cast<int *>(arg));
            return true;
        case QMetaType::LongLong:
            ZVAL_LONG(out, *static_cast<qlonglong *>(arg));
            return true;
        case QMetaType::Double:
            ZVAL_DOUBLE(out, *static_cast<double *>(arg));
            return true;
        case QMetaType::QString: {
            auto *qs = static_cast<QString *>(arg);
            QByteArray utf8 = qs->toUtf8();
            ZVAL_STRINGL(out, utf8.constData(), utf8.size());
            return true;
        }
        case QMetaType::QVariant: {
            auto *v = static_cast<QVariant *>(arg);
            if (!v->isValid()) {
                ZVAL_NULL(out);
                return true;
            }
            if (v->canConvert<QString>()) {
                QString qs = v->toString();
                QByteArray utf8 = qs.toUtf8();
                ZVAL_STRINGL(out, utf8.constData(), utf8.size());
                return true;
            }
            if (v->canConvert<int>()) {
                ZVAL_LONG(out, v->toInt());
                return true;
            }
            if (v->canConvert<bool>()) {
                ZVAL_BOOL(out, v->toBool());
                return true;
            }
            if (v->canConvert<double>()) {
                ZVAL_DOUBLE(out, v->toDouble());
                return true;
            }
            ZVAL_NULL(out);
            return true;
        }
        case QMetaType::QObjectStar: {
            QObject *obj = *static_cast<QObject **>(arg);
            if (obj == nullptr) {
                ZVAL_NULL(out);
                return true;
            }
            return qt_qobject_wrap_runtime_instance(out, obj, true);
        }
        default:
            ZVAL_NULL(out);
            return true;
    }
}

static inline void qt_php_metaobject_invoke_slot(
    zend_object *phpObject,
    const std::string &methodName,
    const std::vector<std::string> &paramTypes,
    void **args)
{
    if (!qt_runtime_can_call_zend()) return;

    std::vector<zval> params;
    params.reserve(paramTypes.size());
    for (size_t i = 0; i < paramTypes.size(); i++) {
        zval param;
        ZVAL_NULL(&param);
        int metaType = qt_php_metaobject_type_token_to_qmetatype(paramTypes[i]);
        if (args != nullptr && args[i + 1] != nullptr) {
            qt_php_metaobject_qt_arg_to_zval(metaType, args[i + 1], &param);
        }
        params.push_back(param);
    }

    zval retval;
    ZVAL_NULL(&retval);
    qt_call_php_method(
        phpObject,
        methodName.c_str(),
        &retval,
        (uint32_t) params.size(),
        params.empty() ? nullptr : params.data()
    );
    zval_ptr_dtor(&retval);

    for (auto &p : params) {
        zval_ptr_dtor(&p);
    }
}

int QtPhpMetaObjectBridge::qt_metacall(QMetaObject::Call call, int id, void **args)
{
    id = QObject::qt_metacall(call, id, args);
    if (id < 0) return id;

    if (call == QMetaObject::InvokeMetaMethod) {
        int methodCount = m_classMetadata ? (int) m_classMetadata->methods.size() : 0;
        if (id < methodCount) {
            const auto &method = m_classMetadata->methods[id];
            if (method.kind == qt_php_metaobject_method_entry::kind_t::slot_method) {
                qt_php_metaobject_invoke_slot(m_phpObject, method.name, method.param_types, args);
            }
        }
        id -= methodCount;
        return id;
    }

    return id;
}

void QtPhpMetaObjectBridge::activatePhpSignal(const char *signalName, int argc, void **argv)
{
    if (signalName == nullptr || m_dynamicMetaObject == nullptr) return;
    if (m_classMetadata == nullptr) return;

    QByteArray sig(signalName);
    sig.append('(');

    std::string lowered(signalName);
    for (char &ch : lowered) { ch = (char) std::tolower((unsigned char) ch); }

    auto it = m_classMetadata->method_by_name.find(lowered);
    if (it != m_classMetadata->method_by_name.end()) {
        const auto &entry = m_classMetadata->methods[it->second];
        for (size_t i = 0; i < entry.param_types.size(); i++) {
            if (i > 0) sig.append(',');
            const char *qtType = qt_php_metaobject_type_token_to_qt_type(entry.param_types[i]);
            sig.append(qtType ? qtType : "QVariant");
        }
    }
    sig.append(')');

    sig = QMetaObject::normalizedSignature(sig.constData());

    int signalIndex = m_dynamicMetaObject->indexOfSignal(sig.constData());
    if (signalIndex < 0) {
        int localCount = m_dynamicMetaObject->methodCount() - m_dynamicMetaObject->methodOffset();
        for (int i = 0; i < localCount; i++) {
            QMetaMethod mm = m_dynamicMetaObject->method(m_dynamicMetaObject->methodOffset() + i);
            if (mm.methodType() == QMetaMethod::Signal && mm.name() == QByteArray(signalName)) {
                signalIndex = m_dynamicMetaObject->methodOffset() + i;
                break;
            }
        }
    }
    if (signalIndex < 0) return;

    int localIndex = signalIndex - m_dynamicMetaObject->methodOffset();
    QMetaObject::activate(this, m_dynamicMetaObject, localIndex, argv);
}

PHP_QT_API zend_function *qt_php_metaobject_get_method(
    zend_object **object, zend_string *method_name, const zval *key)
{
    zend_function *fbc = zend_std_get_method(object, method_name, key);
    if (fbc == nullptr) {
        return nullptr;
    }

    if (fbc->common.fn_flags & ZEND_ACC_CALL_VIA_TRAMPOLINE) {
        return fbc;
    }

    zend_class_entry *ce = (*object)->ce;
    auto metadata = qt_php_metaobject_metadata_for_ce(ce, nullptr);
    if (!metadata || !metadata->valid) {
        return fbc;
    }

    std::string lowered(ZSTR_VAL(method_name), ZSTR_LEN(method_name));
    for (char &ch : lowered) { ch = (char) std::tolower((unsigned char) ch); }

    auto it = metadata->method_by_name.find(lowered);
    if (it == metadata->method_by_name.end()) {
        return fbc;
    }

    const auto &entry = metadata->methods[it->second];
    if (entry.kind != qt_php_metaobject_method_entry::kind_t::signal_method) {
        return fbc;
    }

    zend_internal_function *func = (zend_internal_function *) emalloc(sizeof(zend_internal_function));
    memset(func, 0, sizeof(zend_internal_function));
    func->type = ZEND_INTERNAL_FUNCTION;
    func->fn_flags = ZEND_ACC_PUBLIC | ZEND_ACC_CALL_VIA_TRAMPOLINE;
    func->function_name = zend_string_copy(method_name);
    func->scope = fbc->common.scope;
    func->num_args = fbc->common.num_args;
    func->required_num_args = fbc->common.required_num_args;
    func->arg_info = fbc->common.arg_info;
    func->handler = qt_php_metaobject_signal_trampoline;

    return (zend_function *) func;
}

PHP_QT_API void qt_php_metaobject_signal_trampoline(INTERNAL_FUNCTION_PARAMETERS)
{
    zend_object *obj = Z_OBJ(execute_data->This);
    zend_function *fbc = execute_data->func;
    if (fbc == nullptr || obj == nullptr) {
        return;
    }

    zend_string *method_name = fbc->common.function_name;
    if (method_name == nullptr) {
        zend_string_release(method_name);
        zend_free_trampoline(fbc);
        execute_data->func = nullptr;
        return;
    }

    std::string signalName(ZSTR_VAL(method_name), ZSTR_LEN(method_name));
    for (char &ch : signalName) { ch = (char) std::tolower((unsigned char) ch); }

    qt_qobject_object *intern = qt_qobject_from_obj(obj);
    if (intern == nullptr || intern->native_ptr == nullptr) {
        zend_string_release(method_name);
        zend_free_trampoline(fbc);
        execute_data->func = nullptr;
        return;
    }

    QObject *native = static_cast<QObject *>(intern->native_ptr);
    QtPhpMetaObjectBridge *bridge = qt_php_metaobject_bridge_for_native(native);

    if (bridge == nullptr) {
        zend_string_release(method_name);
        zend_free_trampoline(fbc);
        execute_data->func = nullptr;
        php_error_docref(nullptr, E_WARNING, "Cannot emit signal '%s': object is not a meta-object bridge", ZSTR_VAL(method_name));
        return;
    }

    auto metadata = qt_php_metaobject_metadata_for_ce(obj->ce, nullptr);
    if (!metadata || !metadata->valid) {
        zend_string_release(method_name);
        zend_free_trampoline(fbc);
        execute_data->func = nullptr;
        return;
    }

    auto it = metadata->method_by_name.find(signalName);
    if (it == metadata->method_by_name.end()) {
        zend_string_release(method_name);
        zend_free_trampoline(fbc);
        execute_data->func = nullptr;
        return;
    }

    const auto &entry = metadata->methods[it->second];
    uint32_t argc = ZEND_CALL_NUM_ARGS(execute_data);

    std::vector<void *> argvStorage(argc + 1, nullptr);
    std::vector<bool> storage;
    std::vector<int> argMetaTypes;

    for (size_t i = 0; i < entry.param_types.size(); i++) {
        int mt = qt_php_metaobject_type_token_to_qmetatype(entry.param_types[i]);
        argMetaTypes.push_back(mt != QMetaType::UnknownType ? mt : QMetaType::QVariant);
    }

    #define QT_PHP_EMIT_ARG_CASE(mt, php_type, storage_type) \
        case mt: { \
            storage_type typed; \
            ZVAL_UNDEF(&tmp); \
            if (zend_parse_parameter(i + 1, &tmp, php_type) == FAILURE) { \
                typed = storage_type{}; \
            } else { \
                typed = static_cast<storage_type>(zval_get_##php_type(&tmp)); \
                if (!Z_ISUNDEF(tmp)) zval_ptr_dtor(&tmp); \
            } \
            void *heap = emalloc(sizeof(storage_type)); \
            std::memcpy(heap, &typed, sizeof(storage_type)); \
            argvStorage[i + 1] = heap; \
            break; \
        }

    zval tmp;
    for (uint32_t i = 0; i < argc && i < entry.param_types.size(); i++) {
        ZVAL_UNDEF(&tmp);
        int mt = (i < argMetaTypes.size()) ? argMetaTypes[i] : QMetaType::QVariant;
        switch (mt) {
            case QMetaType::Bool: {
                bool val = (i < argc) ? zval_is_true(ZEND_CALL_ARG(execute_data, i + 1)) : false;
                void *heap = emalloc(sizeof(bool));
                std::memcpy(heap, &val, sizeof(bool));
                argvStorage[i + 1] = heap;
                break;
            }
            case QMetaType::Int: {
                zend_long val = (i < argc) ? zval_get_long(ZEND_CALL_ARG(execute_data, i + 1)) : 0;
                void *heap = emalloc(sizeof(int));
                int typed = static_cast<int>(val);
                std::memcpy(heap, &typed, sizeof(int));
                argvStorage[i + 1] = heap;
                break;
            }
            case QMetaType::Double: {
                double val = (i < argc) ? zval_get_double(ZEND_CALL_ARG(execute_data, i + 1)) : 0.0;
                void *heap = emalloc(sizeof(double));
                std::memcpy(heap, &val, sizeof(double));
                argvStorage[i + 1] = heap;
                break;
            }
            case QMetaType::QString: {
                zval *arg = (i < argc) ? ZEND_CALL_ARG(execute_data, i + 1) : &EG(uninitialized_zval);
                zend_string *zs = zval_get_string(arg);
                QString qs = QString::fromUtf8(ZSTR_VAL(zs), static_cast<int>(ZSTR_LEN(zs)));
                void *heap = emalloc(sizeof(QString));
                new (heap) QString(std::move(qs));
                argvStorage[i + 1] = heap;
                zend_string_release(zs);
                break;
            }
            case QMetaType::QVariant: {
                zval *arg = (i < argc) ? ZEND_CALL_ARG(execute_data, i + 1) : &EG(uninitialized_zval);
                void *heap = emalloc(sizeof(QVariant));
                switch (Z_TYPE_P(arg)) {
                    case IS_TRUE:
                    case IS_FALSE:
                        new (heap) QVariant(Z_TYPE_P(arg) == IS_TRUE);
                        break;
                    case IS_LONG:
                        new (heap) QVariant(static_cast<int>(Z_LVAL_P(arg)));
                        break;
                    case IS_DOUBLE:
                        new (heap) QVariant(Z_DVAL_P(arg));
                        break;
                    case IS_STRING:
                        new (heap) QVariant(QString::fromUtf8(Z_STRVAL_P(arg), static_cast<int>(Z_STRLEN_P(arg))));
                        break;
                    default:
                        new (heap) QVariant();
                        break;
                }
                argvStorage[i + 1] = heap;
                break;
            }
            default: {
                argvStorage[i + 1] = nullptr;
                break;
            }
        }
    }

    bridge->activatePhpSignal(entry.name.c_str(), static_cast<int>(argc), argvStorage.data());

    for (size_t i = 0; i < entry.param_types.size() && i + 1 < argvStorage.size(); i++) {
        if (argvStorage[i + 1] != nullptr) {
            int mt = (i < argMetaTypes.size()) ? argMetaTypes[i] : QMetaType::QVariant;
            switch (mt) {
                case QMetaType::QString:
                    static_cast<QString *>(argvStorage[i + 1])->~QString();
                    efree(argvStorage[i + 1]);
                    break;
                case QMetaType::QVariant:
                    static_cast<QVariant *>(argvStorage[i + 1])->~QVariant();
                    efree(argvStorage[i + 1]);
                    break;
                default:
                    efree(argvStorage[i + 1]);
                    break;
            }
        }
    }

    zend_string_release(method_name);
    zend_free_trampoline(fbc);
    execute_data->func = nullptr;
}
