/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Shared PHP wrapper for QMetaObject::Connection handles.
 */

#ifndef QT_QMETAOBJECTCONNECTION_H
#define QT_QMETAOBJECTCONNECTION_H

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include <QObject>

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

typedef struct _qt_qmetaobjectconnection_object {
    QMetaObject::Connection *native_ptr;
    zend_object std; /* MUST be last */
} qt_qmetaobjectconnection_object;

extern PHP_QT_API zend_class_entry *qt_ce_QMetaObjectConnection;
extern zend_object_handlers qt_qmetaobjectconnection_handlers;

static inline qt_qmetaobjectconnection_object *qt_qmetaobjectconnection_from_obj(zend_object *obj)
{
    return (qt_qmetaobjectconnection_object *)((char *)(obj) - XtOffsetOf(qt_qmetaobjectconnection_object, std));
}

#define Z_QMETAOBJECTCONNECTION_P(zv) qt_qmetaobjectconnection_from_obj(Z_OBJ_P(zv))

PHP_QT_API void qt_qmetaobjectconnection_wrap(zval *return_value, const QMetaObject::Connection &connection);
PHP_MINIT_FUNCTION(qt_qmetaobjectconnection);

#endif /* QT_QMETAOBJECTCONNECTION_H */
