/**
 * Auto-generated by phpqt-builder -- DO NOT EDIT.
 *
 * Shared QObject property helpers for generated Qt wrapper classes.
 */

#ifndef QT_QOBJECT_HELPERS_H
#define QT_QOBJECT_HELPERS_H

#include "qt_class_helpers.h"
#include <QMetaMethod>
#include <QMetaProperty>
#include <QObject>
#include <string>
#include <unordered_set>

static zend_always_inline int qt_qobject_meta_property_index(QObject *obj, zend_string *name)
{
    if (obj == NULL || name == NULL) {
        return -1;
    }

    QByteArray _qt_name(ZSTR_VAL(name), (int) ZSTR_LEN(name));
    return obj->metaObject()->indexOfProperty(_qt_name.constData());
}

static zend_always_inline bool qt_qobject_has_dynamic_property(QObject *obj, zend_string *name)
{
    if (obj == NULL || name == NULL) {
        return false;
    }

    QByteArray _qt_name(ZSTR_VAL(name), (int) ZSTR_LEN(name));
    const QList<QByteArray> _qt_names = obj->dynamicPropertyNames();
    for (const QByteArray &_qt_dynamic_name : _qt_names) {
        if (_qt_dynamic_name == _qt_name) {
            return true;
        }
    }

    return false;
}

static inline void qt_qobject_variant_to_property_zval(zval *target, const QVariant &value)
{
    qt_variant_to_zval(target, value);
}

static inline bool qt_qobject_zval_to_property_variant(zval *value, QVariant *out)
{
    return qt_zval_to_variant(value, out);
}

static inline bool qt_qobject_read_property_mixed(QObject *obj, zend_string *name, zval *rv)
{
    if (obj == NULL || name == NULL) {
        return false;
    }

    QByteArray _qt_name(ZSTR_VAL(name), (int) ZSTR_LEN(name));
    const QVariant _qt_value = obj->property(_qt_name.constData());

    if (!_qt_value.isValid() && qt_qobject_meta_property_index(obj, name) < 0 && !qt_qobject_has_dynamic_property(obj, name)) {
        return false;
    }

    qt_qobject_variant_to_property_zval(rv, _qt_value);
    return true;
}

static inline bool qt_qobject_write_property_mixed(QObject *obj, zend_string *name, zval *value, bool *result)
{
    if (obj == NULL || name == NULL || value == NULL) {
        return false;
    }

    QVariant _qt_value;
    if (!qt_qobject_zval_to_property_variant(value, &_qt_value)) {
        return false;
    }

    QByteArray _qt_name(ZSTR_VAL(name), (int) ZSTR_LEN(name));
    const int _qt_property_index = qt_qobject_meta_property_index(obj, name);
    if (_qt_property_index >= 0) {
        auto _qt_property = obj->metaObject()->property(_qt_property_index);
        if (!_qt_property.isWritable()) {
            zend_throw_error(NULL, "Property %s is not writable.", ZSTR_VAL(name));
            return false;
        }

        const bool _qt_result = obj->setProperty(_qt_name.constData(), _qt_value);
        if (result != NULL) {
            *result = _qt_result;
        }

        return true;
    }

    obj->setProperty(_qt_name.constData(), _qt_value);
    if (result != NULL) {
        *result = qt_qobject_has_dynamic_property(obj, name);
    }

    return true;
}

static inline bool qt_qobject_has_property_name(QObject *obj, zend_string *name)
{
    return qt_qobject_meta_property_index(obj, name) >= 0
        || qt_qobject_has_dynamic_property(obj, name);
}

static inline bool qt_qobject_should_delegate_to_std_property(zend_object *object, zend_string *name)
{
    if (object == NULL || name == NULL) {
        return false;
    }

    zend_property_info *_qt_prop_info = zend_get_property_info(object->ce, name, true);
    if (_qt_prop_info == NULL || _qt_prop_info == ZEND_WRONG_PROPERTY_INFO) {
        return false;
    }

    return (_qt_prop_info->flags & ZEND_ACC_VIRTUAL) == 0;
}

static inline void qt_qobject_property_names(QObject *obj, zval *return_value)
{
    array_init(return_value);

    if (obj == NULL) {
        return;
    }

    std::unordered_set<std::string> _qt_seen;
    const QMetaObject *_qt_meta = obj->metaObject();
    const int _qt_meta_count = _qt_meta->propertyCount();
    for (int _qt_i = 0; _qt_i < _qt_meta_count; ++_qt_i) {
        auto _qt_property = _qt_meta->property(_qt_i);
        const char *_qt_name = _qt_property.name();
        if (_qt_name == NULL || *_qt_name == '\0') {
            continue;
        }

        if (_qt_seen.insert(std::string(_qt_name)).second) {
            add_next_index_string(return_value, _qt_name);
        }
    }

    const QList<QByteArray> _qt_dynamic_names = obj->dynamicPropertyNames();
    for (const QByteArray &_qt_name : _qt_dynamic_names) {
        std::string _qt_key(_qt_name.constData(), (size_t) _qt_name.size());
        if (_qt_seen.insert(_qt_key).second) {
            add_next_index_stringl(return_value, _qt_name.constData(), _qt_name.size());
        }
    }
}

static inline bool qt_qobject_property_info(QObject *obj, zend_string *name, zval *return_value)
{
    if (obj == NULL || name == NULL) {
        return false;
    }

    const int _qt_property_index = qt_qobject_meta_property_index(obj, name);
    if (_qt_property_index >= 0) {
        auto _qt_property = obj->metaObject()->property(_qt_property_index);
        array_init(return_value);
        add_assoc_stringl(return_value, "name", ZSTR_VAL(name), ZSTR_LEN(name));

        const char *_qt_type_name = _qt_property.typeName();
        if (_qt_type_name == NULL || *_qt_type_name == '\0') {
            _qt_type_name = _qt_property.metaType().name();
        }
        if (_qt_type_name != NULL && *_qt_type_name != '\0') {
            add_assoc_string(return_value, "type_name", const_cast<char *>(_qt_type_name));
        } else {
            add_assoc_string(return_value, "type_name", "QVariant");
        }

        add_assoc_bool(return_value, "readable", _qt_property.isReadable());
        add_assoc_bool(return_value, "writable", _qt_property.isWritable());
        add_assoc_bool(return_value, "resettable", _qt_property.isResettable());
        add_assoc_bool(return_value, "constant", _qt_property.isConstant());
        add_assoc_bool(return_value, "final", _qt_property.isFinal());
        add_assoc_bool(return_value, "required", _qt_property.isRequired());
        add_assoc_bool(return_value, "designable", _qt_property.isDesignable());
        add_assoc_bool(return_value, "scriptable", _qt_property.isScriptable());
        add_assoc_bool(return_value, "stored", _qt_property.isStored());
        add_assoc_bool(return_value, "user", _qt_property.isUser());
        add_assoc_bool(return_value, "enum", _qt_property.isEnumType());
        add_assoc_bool(return_value, "flag", _qt_property.isFlagType());
        add_assoc_bool(return_value, "dynamic", false);

        auto _qt_notify = _qt_property.notifySignal();
        if (_qt_notify.isValid()) {
            QByteArray _qt_signature = _qt_notify.methodSignature();
            add_assoc_bool(return_value, "has_notify", true);
            add_assoc_stringl(return_value, "notify_signal", _qt_signature.constData(), _qt_signature.size());
        } else {
            add_assoc_bool(return_value, "has_notify", false);
            add_assoc_null(return_value, "notify_signal");
        }

        return true;
    }

    if (!qt_qobject_has_dynamic_property(obj, name)) {
        return false;
    }

    array_init(return_value);
    add_assoc_stringl(return_value, "name", ZSTR_VAL(name), ZSTR_LEN(name));
    QVariant _qt_value = obj->property(QByteArray(ZSTR_VAL(name), (int) ZSTR_LEN(name)).constData());
    const char *_qt_type_name = _qt_value.metaType().name();
    if (_qt_type_name != NULL && *_qt_type_name != '\0') {
        add_assoc_string(return_value, "type_name", const_cast<char *>(_qt_type_name));
    } else {
        add_assoc_string(return_value, "type_name", "QVariant");
    }
    add_assoc_bool(return_value, "readable", true);
    add_assoc_bool(return_value, "writable", true);
    add_assoc_bool(return_value, "resettable", false);
    add_assoc_bool(return_value, "constant", false);
    add_assoc_bool(return_value, "final", false);
    add_assoc_bool(return_value, "required", false);
    add_assoc_bool(return_value, "designable", true);
    add_assoc_bool(return_value, "scriptable", true);
    add_assoc_bool(return_value, "stored", true);
    add_assoc_bool(return_value, "user", false);
    add_assoc_bool(return_value, "enum", false);
    add_assoc_bool(return_value, "flag", false);
    add_assoc_bool(return_value, "has_notify", false);
    add_assoc_null(return_value, "notify_signal");
    add_assoc_bool(return_value, "dynamic", true);

    return true;
}

static inline bool qt_qobject_notify_signature(QObject *obj, zend_string *name, zend_string **out)
{
    if (obj == NULL || name == NULL || out == NULL) {
        return false;
    }

    const int _qt_property_index = qt_qobject_meta_property_index(obj, name);
    if (_qt_property_index < 0) {
        return false;
    }

    auto _qt_property = obj->metaObject()->property(_qt_property_index);
    auto _qt_notify = _qt_property.notifySignal();
    if (!_qt_notify.isValid()) {
        return false;
    }

    QByteArray _qt_signature = _qt_notify.methodSignature();
    if (_qt_signature.isEmpty()) {
        return false;
    }

    *out = zend_string_init(_qt_signature.constData(), _qt_signature.size(), 0);
    return true;
}

#endif /* QT_QOBJECT_HELPERS_H */
