/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Shared PHP wrapper implementation for extension-managed PHP signal connections.
 */

#include "qt_qphpsignalconnection.h"
#include "qt_qphpsignalconnection_arginfo.h"
#include "qt_php_signal_helpers.h"

zend_class_entry *qt_ce_QPhpSignalConnection = NULL;
zend_object_handlers qt_qphpsignalconnection_handlers;

static zend_object *qt_qphpsignalconnection_create_object(zend_class_entry *ce)
{
    qt_qphpsignalconnection_object *intern = (qt_qphpsignalconnection_object *)zend_object_alloc(
        sizeof(qt_qphpsignalconnection_object), ce
    );
    intern->sender_token = 0;
    intern->listener_id = 0;
    intern->generation = 0;

    zend_object_std_init(&intern->std, ce);
    object_properties_init(&intern->std, ce);

    return &intern->std;
}

static void qt_qphpsignalconnection_free_object(zend_object *object)
{
    qt_qphpsignalconnection_object *intern = qt_qphpsignalconnection_from_obj(object);
    intern->sender_token = 0;
    intern->listener_id = 0;
    intern->generation = 0;
    zend_object_std_dtor(&intern->std);
}

static HashTable *qt_qphpsignalconnection_get_gc(zend_object *object, zval **table, int *n)
{
    *table = NULL;
    *n = 0;

    return zend_std_get_properties(object);
}

PHP_QT_API void qt_qphpsignalconnection_wrap(
    zval *return_value,
    uint64_t sender_token,
    uint64_t listener_id,
    uint64_t generation
)
{
    object_init_ex(return_value, qt_ce_QPhpSignalConnection);
    qt_qphpsignalconnection_object *intern = Z_QPHPSIGNALCONNECTION_P(return_value);
    intern->sender_token = sender_token;
    intern->listener_id = listener_id;
    intern->generation = generation;
}

PHP_QT_API bool qt_qphpsignalconnection_disconnect(qt_qphpsignalconnection_object *intern)
{
    if (intern == NULL || intern->sender_token == 0 || intern->listener_id == 0) {
        return false;
    }

    const bool disconnected = qt_php_signal_disconnect_listener(
        intern->sender_token,
        intern->listener_id,
        intern->generation
    );
    intern->sender_token = 0;
    intern->listener_id = 0;
    intern->generation = 0;

    return disconnected;
}

static const zend_function_entry qt_qphpsignalconnection_methods[] = {
    ZEND_FE_END
};

PHP_MINIT_FUNCTION(qt_qphpsignalconnection)
{
    zend_class_entry ce;
    INIT_NS_CLASS_ENTRY(ce, "Qt\\Core", "QPhpSignalConnection", qt_qphpsignalconnection_methods);
    ce.create_object = qt_qphpsignalconnection_create_object;

    qt_ce_QPhpSignalConnection = zend_register_internal_class(&ce);
    qt_ce_QPhpSignalConnection->ce_flags |= ZEND_ACC_FINAL;

    memcpy(&qt_qphpsignalconnection_handlers, &std_object_handlers, sizeof(zend_object_handlers));
    qt_qphpsignalconnection_handlers.offset = XtOffsetOf(qt_qphpsignalconnection_object, std);
    qt_qphpsignalconnection_handlers.free_obj = qt_qphpsignalconnection_free_object;
    qt_qphpsignalconnection_handlers.clone_obj = NULL;
    qt_qphpsignalconnection_handlers.get_gc = qt_qphpsignalconnection_get_gc;

    qt_ce_QPhpSignalConnection->default_object_handlers = &qt_qphpsignalconnection_handlers;

    return SUCCESS;
}
