/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Qt\Test\QTest support implementation.
 */

#include "qt_qtest.h"
#include "qt_qtest_arginfo.h"

#include <QtCore/QByteArray>
#include <QtCore/QPoint>
#include <QtCore/QPointF>
#include <QtCore/QRegularExpression>
#include <QtCore/QSharedPointer>
#include <QtCore/QTemporaryDir>
#include <QtCore/QStringList>
#include <functional>
#include <QtTest/qtestcase.h>

#include "qt_qregularexpression.h"
@if($ctx->includesModule('QtWidgets'))
#include <QtTest/qtest_widgets.h>
#include <QtWidgets/QWidget>
#include "qt_qwidget.h"
@endif
@if($ctx->includesModule('QtGui'))
#include <QtGui/QWindow>
#include <QtTest/qtestkeyboard.h>
#include <QtTest/qtestmouse.h>
#include <QtTest/qtestwheel.h>
#include "qt_qpoint.h"
#include "qt_qpointf.h"
#include "qt_qwindow.h"
@endif
#include "qt_qobject.h"
#include "qt_qtemporarydir.h"

zend_class_entry *qt_ce_QTest = NULL;

static inline QString qt_qtest_string_from_zend(zend_string *string)
{
    return QString::fromUtf8(ZSTR_VAL(string), (int) ZSTR_LEN(string));
}

static inline bool qt_qtest_zval_to_qstring_list(zval *value, QStringList *out)
{
    if (value == NULL || out == NULL || Z_TYPE_P(value) != IS_ARRAY) {
        return false;
    }

    HashTable *ht = Z_ARRVAL_P(value);
    out->clear();
    out->reserve((int) zend_hash_num_elements(ht));

    zval *entry = NULL;
    ZEND_HASH_FOREACH_VAL(ht, entry) {
        zend_string *string = zval_get_string(entry);
        out->append(QString::fromUtf8(ZSTR_VAL(string), (int) ZSTR_LEN(string)));
        zend_string_release(string);
    } ZEND_HASH_FOREACH_END();

    return true;
}

static inline QRegularExpression qt_qtest_pattern_from_zval(zval *value)
{
    if (value != NULL && Z_TYPE_P(value) == IS_OBJECT && instanceof_function(Z_OBJCE_P(value), qt_ce_qregularexpression)) {
        return *qt_qregularexpression_from_obj(Z_OBJ_P(value))->native_ptr;
    }

    if (value != NULL && Z_TYPE_P(value) == IS_STRING) {
        return QRegularExpression(qt_qtest_string_from_zend(Z_STR_P(value)));
    }

    return QRegularExpression();
}

static inline Qt::KeyboardModifiers qt_qtest_keyboard_modifiers_from_zend(zend_long modifier)
{
    return Qt::KeyboardModifiers((int) modifier);
}

@if($ctx->includesModule('QtGui'))
static inline QWindow *qt_qtest_window_from_zval(zval *value)
{
    if (value == NULL || Z_TYPE_P(value) != IS_OBJECT) {
        return NULL;
    }

    if (qt_ce_qwindow != NULL && instanceof_function(Z_OBJCE_P(value), qt_ce_qwindow)) {
        return qt_qwindow_from_obj(Z_OBJ_P(value))->native_ptr;
    }

    return NULL;
}

static inline QWidget *qt_qtest_widget_from_zval(zval *value)
{
    if (value == NULL || Z_TYPE_P(value) != IS_OBJECT) {
        return NULL;
    }

    if (qt_ce_qwidget != NULL && instanceof_function(Z_OBJCE_P(value), qt_ce_qwidget)) {
        return qt_qwidget_from_obj(Z_OBJ_P(value))->native_ptr;
    }

    return NULL;
}

static inline QObject *qt_qtest_object_from_zval(zval *value)
{
    if (value == NULL || Z_TYPE_P(value) != IS_OBJECT) {
        return NULL;
    }

    if (qt_ce_qobject != NULL && instanceof_function(Z_OBJCE_P(value), qt_ce_qobject)) {
        return qt_qobject_from_obj(Z_OBJ_P(value))->native_ptr;
    }

    return NULL;
}

static inline bool qt_qtest_handle_window_or_widget(zval *target, std::function<void(QWindow *)> on_window, std::function<void(QWidget *)> on_widget)
{
    QWindow *window = qt_qtest_window_from_zval(target);
    if (window != NULL) {
        on_window(window);
        return true;
    }

@if($ctx->includesModule('QtWidgets'))
    QWidget *widget = qt_qtest_widget_from_zval(target);
    if (widget != NULL) {
        on_widget(widget);
        return true;
    }
@endif

    return false;
}
@endif

PHP_METHOD(Qt_Test_QTest, qExec)
{
    zval *testObject = NULL;
    HashTable *arguments = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_OBJECT_OF_CLASS(testObject, qt_ce_qobject)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY_HT(arguments)
    ZEND_PARSE_PARAMETERS_END();

    QStringList qArguments;
    if (arguments != NULL) {
        qArguments.reserve((int) zend_hash_num_elements(arguments));
        zval *entry = NULL;
        ZEND_HASH_FOREACH_VAL(arguments, entry) {
            zend_string *string = zval_get_string(entry);
            qArguments.append(QString::fromUtf8(ZSTR_VAL(string), (int) ZSTR_LEN(string)));
            zend_string_release(string);
        } ZEND_HASH_FOREACH_END();
    }

    QObject *testObjectNative = qt_qobject_from_obj(Z_OBJ_P(testObject))->native_ptr;
    RETURN_LONG((zend_long) QTest::qExec(testObjectNative, qArguments));
}

PHP_METHOD(Qt_Test_QTest, qWait)
{
    zend_long msecs = 0;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_LONG(msecs)
    ZEND_PARSE_PARAMETERS_END();

    QTest::qWait((int) msecs);
}

PHP_METHOD(Qt_Test_QTest, setMainSourcePath)
{
    zend_string *file = NULL;
    zend_string *builddir = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(file)
        Z_PARAM_OPTIONAL
        Z_PARAM_STR_OR_NULL(builddir)
    ZEND_PARSE_PARAMETERS_END();

    const QByteArray fileBytes = QByteArray(ZSTR_VAL(file), (int) ZSTR_LEN(file));
    if (builddir != NULL) {
        const QByteArray buildBytes = QByteArray(ZSTR_VAL(builddir), (int) ZSTR_LEN(builddir));
        QTest::setMainSourcePath(fileBytes.constData(), buildBytes.constData());
    } else {
        QTest::setMainSourcePath(fileBytes.constData(), NULL);
    }
}

PHP_METHOD(Qt_Test_QTest, setThrowOnFail)
{
    bool enable = false;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_BOOL(enable)
    ZEND_PARSE_PARAMETERS_END();

    QTest::setThrowOnFail(enable);
}

PHP_METHOD(Qt_Test_QTest, setThrowOnSkip)
{
    bool enable = false;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_BOOL(enable)
    ZEND_PARSE_PARAMETERS_END();

    QTest::setThrowOnSkip(enable);
}

PHP_METHOD(Qt_Test_QTest, qVerify)
{
    bool statement = false;
    zend_string *statementStr = NULL;
    zend_string *description = NULL;
    zend_string *file = NULL;
    zend_long line = 0;

    ZEND_PARSE_PARAMETERS_START(5, 5)
        Z_PARAM_BOOL(statement)
        Z_PARAM_STR(statementStr)
        Z_PARAM_STR(description)
        Z_PARAM_STR(file)
        Z_PARAM_LONG(line)
    ZEND_PARSE_PARAMETERS_END();

    RETURN_BOOL(QTest::qVerify(
        statement,
        ZSTR_VAL(statementStr),
        ZSTR_VAL(description),
        ZSTR_VAL(file),
        (int) line
    ));
}

PHP_METHOD(Qt_Test_QTest, qFail)
{
    zend_string *message = NULL;
    zend_string *file = NULL;
    zend_long line = 0;

    ZEND_PARSE_PARAMETERS_START(3, 3)
        Z_PARAM_STR(message)
        Z_PARAM_STR(file)
        Z_PARAM_LONG(line)
    ZEND_PARSE_PARAMETERS_END();

    QTest::qFail(ZSTR_VAL(message), ZSTR_VAL(file), (int) line);
}

PHP_METHOD(Qt_Test_QTest, qSkip)
{
    zend_string *message = NULL;
    zend_string *file = NULL;
    zend_long line = 0;

    ZEND_PARSE_PARAMETERS_START(3, 3)
        Z_PARAM_STR(message)
        Z_PARAM_STR(file)
        Z_PARAM_LONG(line)
    ZEND_PARSE_PARAMETERS_END();

    QTest::qSkip(ZSTR_VAL(message), ZSTR_VAL(file), (int) line);
}

PHP_METHOD(Qt_Test_QTest, qExpectFail)
{
    zend_string *dataIndex = NULL;
    zend_string *comment = NULL;
    zend_long mode = 0;
    zend_string *file = NULL;
    zend_long line = 0;

    ZEND_PARSE_PARAMETERS_START(5, 5)
        Z_PARAM_STR(dataIndex)
        Z_PARAM_STR(comment)
        Z_PARAM_LONG(mode)
        Z_PARAM_STR(file)
        Z_PARAM_LONG(line)
    ZEND_PARSE_PARAMETERS_END();

    RETURN_BOOL(QTest::qExpectFail(
        ZSTR_VAL(dataIndex),
        ZSTR_VAL(comment),
        (QTest::TestFailMode) mode,
        ZSTR_VAL(file),
        (int) line
    ));
}

PHP_METHOD(Qt_Test_QTest, qCaught)
{
    zend_string *expected = NULL;
    zend_string *file = NULL;
    zend_long line = 0;

    ZEND_PARSE_PARAMETERS_START(0, 3)
        Z_PARAM_OPTIONAL
        Z_PARAM_STR_OR_NULL(expected)
        Z_PARAM_STR_OR_NULL(file)
        Z_PARAM_LONG(line)
    ZEND_PARSE_PARAMETERS_END();

    if (file != NULL) {
        QTest::qCaught(expected != NULL ? ZSTR_VAL(expected) : NULL, ZSTR_VAL(file), (int) line);
        return;
    }

    if (expected != NULL) {
        QTest::qCaught(ZSTR_VAL(expected), NULL, (int) line);
        return;
    }

    QTest::qCaught(NULL, NULL, (int) line);
}

PHP_METHOD(Qt_Test_QTest, ignoreMessage)
{
    zend_long type = 0;
    zval *messagePattern = NULL;

    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_LONG(type)
        Z_PARAM_ZVAL(messagePattern)
    ZEND_PARSE_PARAMETERS_END();

    if (Z_TYPE_P(messagePattern) == IS_OBJECT && qt_ce_qregularexpression != NULL && instanceof_function(Z_OBJCE_P(messagePattern), qt_ce_qregularexpression)) {
        QTest::ignoreMessage((QtMsgType) type, *qt_qregularexpression_from_obj(Z_OBJ_P(messagePattern))->native_ptr);
        return;
    }

    if (Z_TYPE_P(messagePattern) == IS_STRING) {
        QTest::ignoreMessage((QtMsgType) type, Z_STRVAL_P(messagePattern));
        return;
    }

    zend_type_error("QTest::ignoreMessage() expects a string or QRegularExpression pattern.");
}

PHP_METHOD(Qt_Test_QTest, failOnWarning)
{
    zval *messagePattern = NULL;

    ZEND_PARSE_PARAMETERS_START(0, 1)
        Z_PARAM_OPTIONAL
        Z_PARAM_ZVAL(messagePattern)
    ZEND_PARSE_PARAMETERS_END();

    if (messagePattern == NULL || Z_TYPE_P(messagePattern) == IS_NULL) {
        QTest::failOnWarning();
        return;
    }

    if (Z_TYPE_P(messagePattern) == IS_OBJECT && qt_ce_qregularexpression != NULL && instanceof_function(Z_OBJCE_P(messagePattern), qt_ce_qregularexpression)) {
        QTest::failOnWarning(*qt_qregularexpression_from_obj(Z_OBJ_P(messagePattern))->native_ptr);
        return;
    }

    if (Z_TYPE_P(messagePattern) == IS_STRING) {
        QTest::failOnWarning(Z_STRVAL_P(messagePattern));
        return;
    }

    zend_type_error("QTest::failOnWarning() expects a string, QRegularExpression, or null.");
}

PHP_METHOD(Qt_Test_QTest, qExtractTestData)
{
    zend_string *dirName = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(dirName)
    ZEND_PARSE_PARAMETERS_END();

    QSharedPointer<QTemporaryDir> tempDir = QTest::qExtractTestData(qt_qtest_string_from_zend(dirName));
    if (tempDir.isNull()) {
        RETURN_NULL();
    }

    QTemporaryDir *native = new QTemporaryDir(std::move(*tempDir));
    qt_qtemporarydir_wrap_native(return_value, native, qt_ce_qtemporarydir, false);
}

PHP_METHOD(Qt_Test_QTest, qFindTestData)
{
    zend_string *basepath = NULL;
    zend_string *file = NULL;
    zend_string *builddir = NULL;
    zend_string *sourcedir = NULL;
    zend_long line = 0;

    ZEND_PARSE_PARAMETERS_START(1, 5)
        Z_PARAM_STR(basepath)
        Z_PARAM_OPTIONAL
        Z_PARAM_STR_OR_NULL(file)
        Z_PARAM_LONG(line)
        Z_PARAM_STR_OR_NULL(builddir)
        Z_PARAM_STR_OR_NULL(sourcedir)
    ZEND_PARSE_PARAMETERS_END();

    const QByteArray baseBytes = QByteArray(ZSTR_VAL(basepath), (int) ZSTR_LEN(basepath));
    const QByteArray fileBytes = file != NULL ? QByteArray(ZSTR_VAL(file), (int) ZSTR_LEN(file)) : QByteArray();
    const QByteArray buildBytes = builddir != NULL ? QByteArray(ZSTR_VAL(builddir), (int) ZSTR_LEN(builddir)) : QByteArray();
    const QByteArray sourceBytes = sourcedir != NULL ? QByteArray(ZSTR_VAL(sourcedir), (int) ZSTR_LEN(sourcedir)) : QByteArray();

    QString result = QTest::qFindTestData(
        baseBytes.constData(),
        file != NULL ? fileBytes.constData() : NULL,
        (int) line,
        builddir != NULL ? buildBytes.constData() : NULL,
        sourcedir != NULL ? sourceBytes.constData() : NULL
    );

    if (result.isNull()) {
        RETURN_NULL();
    }

    QByteArray utf8 = result.toUtf8();
    RETURN_STRINGL(utf8.constData(), utf8.size());
}

PHP_METHOD(Qt_Test_QTest, qData)
{
    zend_string *tagName = NULL;
    zend_long typeId = 0;

    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_STR(tagName)
        Z_PARAM_LONG(typeId)
    ZEND_PARSE_PARAMETERS_END();

    void *result = QTest::qData(ZSTR_VAL(tagName), (int) typeId);
    if (result == NULL) {
        RETURN_NULL();
    }

    RETURN_LONG((zend_long) (uintptr_t) result);
}

PHP_METHOD(Qt_Test_QTest, qGlobalData)
{
    zend_string *tagName = NULL;
    zend_long typeId = 0;

    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_STR(tagName)
        Z_PARAM_LONG(typeId)
    ZEND_PARSE_PARAMETERS_END();

    void *result = QTest::qGlobalData(ZSTR_VAL(tagName), (int) typeId);
    if (result == NULL) {
        RETURN_NULL();
    }

    RETURN_LONG((zend_long) (uintptr_t) result);
}

PHP_METHOD(Qt_Test_QTest, qElementData)
{
    zend_string *elementName = NULL;
    zend_long metaTypeId = 0;

    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_STR(elementName)
        Z_PARAM_LONG(metaTypeId)
    ZEND_PARSE_PARAMETERS_END();

    void *result = QTest::qElementData(ZSTR_VAL(elementName), (int) metaTypeId);
    if (result == NULL) {
        RETURN_NULL();
    }

    RETURN_LONG((zend_long) (uintptr_t) result);
}

PHP_METHOD(Qt_Test_QTest, testObject)
{
    ZEND_PARSE_PARAMETERS_NONE();

    QObject *testObject = QTest::testObject();
    if (testObject == NULL) {
        RETURN_NULL();
    }

    qt_qobject_wrap_native(return_value, testObject, qt_ce_qobject, true);
}

PHP_METHOD(Qt_Test_QTest, currentAppName)
{
    ZEND_PARSE_PARAMETERS_NONE();

    const char *name = QTest::currentAppName();
    if (name == NULL) {
        RETURN_NULL();
    }

    RETURN_STRING(name);
}

PHP_METHOD(Qt_Test_QTest, currentTestFunction)
{
    ZEND_PARSE_PARAMETERS_NONE();

    const char *name = QTest::currentTestFunction();
    if (name == NULL) {
        RETURN_NULL();
    }

    RETURN_STRING(name);
}

PHP_METHOD(Qt_Test_QTest, currentDataTag)
{
    ZEND_PARSE_PARAMETERS_NONE();

    const char *name = QTest::currentDataTag();
    if (name == NULL) {
        RETURN_NULL();
    }

    RETURN_STRING(name);
}

PHP_METHOD(Qt_Test_QTest, currentGlobalDataTag)
{
    ZEND_PARSE_PARAMETERS_NONE();

    const char *name = QTest::currentGlobalDataTag();
    if (name == NULL) {
        RETURN_NULL();
    }

    RETURN_STRING(name);
}

PHP_METHOD(Qt_Test_QTest, currentTestFailed)
{
    ZEND_PARSE_PARAMETERS_NONE();

    RETURN_BOOL(QTest::currentTestFailed());
}

PHP_METHOD(Qt_Test_QTest, currentTestResolved)
{
    ZEND_PARSE_PARAMETERS_NONE();

    RETURN_BOOL(QTest::currentTestResolved());
}

PHP_METHOD(Qt_Test_QTest, runningTest)
{
    ZEND_PARSE_PARAMETERS_NONE();

    RETURN_BOOL(QTest::runningTest());
}

PHP_METHOD(Qt_Test_QTest, asciiToKey)
{
    zend_string *ascii = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_STR(ascii)
    ZEND_PARSE_PARAMETERS_END();

    const char ch = ZSTR_LEN(ascii) > 0 ? ZSTR_VAL(ascii)[0] : '\0';
    RETURN_LONG((zend_long) QTest::asciiToKey(ch));
}

PHP_METHOD(Qt_Test_QTest, keyToAscii)
{
    zend_long key = 0;

    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_LONG(key)
    ZEND_PARSE_PARAMETERS_END();

    const char ascii = QTest::keyToAscii((Qt::Key) key);
    if (ascii == '\0') {
        RETURN_EMPTY_STRING();
    }

    char buffer[2] = {ascii, '\0'};
    RETURN_STRINGL(buffer, 1);
}

static void qt_qtest_mouse_press_on_window(QWindow *window, Qt::MouseButton button, Qt::KeyboardModifiers stateKey, zval *pos, int delay)
{
    if (pos != NULL && Z_TYPE_P(pos) == IS_OBJECT) {
        QTest::mousePress(window, button, stateKey, *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr, delay);
        return;
    }

    QTest::mousePress(window, button, stateKey, QPoint(), delay);
}

static void qt_qtest_mouse_release_on_window(QWindow *window, Qt::MouseButton button, Qt::KeyboardModifiers stateKey, zval *pos, int delay)
{
    if (pos != NULL && Z_TYPE_P(pos) == IS_OBJECT) {
        QTest::mouseRelease(window, button, stateKey, *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr, delay);
        return;
    }

    QTest::mouseRelease(window, button, stateKey, QPoint(), delay);
}

static void qt_qtest_mouse_click_on_window(QWindow *window, Qt::MouseButton button, Qt::KeyboardModifiers stateKey, zval *pos, int delay)
{
    if (pos != NULL && Z_TYPE_P(pos) == IS_OBJECT) {
        QTest::mouseClick(window, button, stateKey, *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr, delay);
        return;
    }

    QTest::mouseClick(window, button, stateKey, QPoint(), delay);
}

static void qt_qtest_mouse_dclick_on_window(QWindow *window, Qt::MouseButton button, Qt::KeyboardModifiers stateKey, zval *pos, int delay)
{
    if (pos != NULL && Z_TYPE_P(pos) == IS_OBJECT) {
        QTest::mouseDClick(window, button, stateKey, *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr, delay);
        return;
    }

    QTest::mouseDClick(window, button, stateKey, QPoint(), delay);
}

static void qt_qtest_mouse_move_on_window(QWindow *window, zval *pos, int delay)
{
    if (pos != NULL && Z_TYPE_P(pos) == IS_OBJECT) {
        QTest::mouseMove(window, *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr, delay);
        return;
    }

    QTest::mouseMove(window, QPoint(), delay);
}

static void qt_qtest_key_press_on_window(QWindow *window, zend_long key, Qt::KeyboardModifiers modifier, int delay)
{
    QTest::keyPress(window, (Qt::Key) key, modifier, delay);
}

static void qt_qtest_key_release_on_window(QWindow *window, zend_long key, Qt::KeyboardModifiers modifier, int delay)
{
    QTest::keyRelease(window, (Qt::Key) key, modifier, delay);
}

static void qt_qtest_key_click_on_window(QWindow *window, zend_long key, Qt::KeyboardModifiers modifier, int delay)
{
    QTest::keyClick(window, (Qt::Key) key, modifier, delay);
}

static void qt_qtest_key_clicks_on_window(QWindow *window, zend_string *sequence, Qt::KeyboardModifiers modifier, int delay)
{
    QByteArray utf8(ZSTR_VAL(sequence), (int) ZSTR_LEN(sequence));
    for (char ch : utf8) {
        QTest::keyClick(window, ch, modifier, delay);
    }
}

@if($ctx->includesModule('QtGui'))
PHP_METHOD(Qt_Test_QTest, mousePress)
{
    zval *target = NULL;
    zend_long button = 0;
    zend_long stateKey = 0;
    zval *pos = NULL;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 5)
        Z_PARAM_ZVAL(target)
        Z_PARAM_LONG(button)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(stateKey)
        Z_PARAM_ZVAL(pos)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    if (!qt_qtest_handle_window_or_widget(
        target,
        [button, stateKey, pos, delay](QWindow *window) { qt_qtest_mouse_press_on_window(window, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos, (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [button, stateKey, pos, delay](QWidget *widget) {
            QTest::mousePress(widget, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos != NULL && Z_TYPE_P(pos) == IS_OBJECT ? *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr : QPoint(), (int) delay);
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::mousePress() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, mouseRelease)
{
    zval *target = NULL;
    zend_long button = 0;
    zend_long stateKey = 0;
    zval *pos = NULL;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 5)
        Z_PARAM_ZVAL(target)
        Z_PARAM_LONG(button)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(stateKey)
        Z_PARAM_ZVAL(pos)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    if (!qt_qtest_handle_window_or_widget(
        target,
        [button, stateKey, pos, delay](QWindow *window) { qt_qtest_mouse_release_on_window(window, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos, (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [button, stateKey, pos, delay](QWidget *widget) {
            QTest::mouseRelease(widget, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos != NULL && Z_TYPE_P(pos) == IS_OBJECT ? *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr : QPoint(), (int) delay);
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::mouseRelease() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, mouseClick)
{
    zval *target = NULL;
    zend_long button = 0;
    zend_long stateKey = 0;
    zval *pos = NULL;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 5)
        Z_PARAM_ZVAL(target)
        Z_PARAM_LONG(button)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(stateKey)
        Z_PARAM_ZVAL(pos)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    if (!qt_qtest_handle_window_or_widget(
        target,
        [button, stateKey, pos, delay](QWindow *window) { qt_qtest_mouse_click_on_window(window, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos, (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [button, stateKey, pos, delay](QWidget *widget) {
            QTest::mouseClick(widget, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos != NULL && Z_TYPE_P(pos) == IS_OBJECT ? *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr : QPoint(), (int) delay);
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::mouseClick() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, mouseDClick)
{
    zval *target = NULL;
    zend_long button = 0;
    zend_long stateKey = 0;
    zval *pos = NULL;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 5)
        Z_PARAM_ZVAL(target)
        Z_PARAM_LONG(button)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(stateKey)
        Z_PARAM_ZVAL(pos)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    if (!qt_qtest_handle_window_or_widget(
        target,
        [button, stateKey, pos, delay](QWindow *window) { qt_qtest_mouse_dclick_on_window(window, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos, (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [button, stateKey, pos, delay](QWidget *widget) {
            QTest::mouseDClick(widget, (Qt::MouseButton) button, qt_qtest_keyboard_modifiers_from_zend(stateKey), pos != NULL && Z_TYPE_P(pos) == IS_OBJECT ? *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr : QPoint(), (int) delay);
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::mouseDClick() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, mouseMove)
{
    zval *target = NULL;
    zval *pos = NULL;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(1, 3)
        Z_PARAM_ZVAL(target)
        Z_PARAM_OPTIONAL
        Z_PARAM_ZVAL(pos)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    if (!qt_qtest_handle_window_or_widget(
        target,
        [pos, delay](QWindow *window) { qt_qtest_mouse_move_on_window(window, pos, (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [pos, delay](QWidget *widget) {
            QTest::mouseMove(widget, pos != NULL && Z_TYPE_P(pos) == IS_OBJECT ? *qt_qpoint_from_obj(Z_OBJ_P(pos))->native_ptr : QPoint(), (int) delay);
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::mouseMove() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, keyPress)
{
    zval *target = NULL;
    zval *key = NULL;
    zend_long modifier = 0;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 4)
        Z_PARAM_ZVAL(target)
        Z_PARAM_ZVAL(key)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(modifier)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    zend_long keyValue = 0;
    bool keyIsString = false;
    char keyChar = '\0';
    if (Z_TYPE_P(key) == IS_LONG) {
        keyValue = Z_LVAL_P(key);
    } else if (Z_TYPE_P(key) == IS_STRING && Z_STRLEN_P(key) > 0) {
        keyValue = (unsigned char) Z_STRVAL_P(key)[0];
        keyIsString = true;
        keyChar = Z_STRVAL_P(key)[0];
    } else {
        zend_type_error("QTest::keyPress() expects an integer key code or single-character string.");
        return;
    }

    if (!qt_qtest_handle_window_or_widget(
        target,
        [keyValue, modifier, delay](QWindow *window) { qt_qtest_key_press_on_window(window, keyValue, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [keyValue, modifier, delay, keyIsString, keyChar](QWidget *widget) {
            if (keyIsString) {
                QTest::keyPress(widget, keyChar, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay);
            } else {
                QTest::keyPress(widget, (Qt::Key) keyValue, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay);
            }
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::keyPress() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, keyRelease)
{
    zval *target = NULL;
    zval *key = NULL;
    zend_long modifier = 0;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 4)
        Z_PARAM_ZVAL(target)
        Z_PARAM_ZVAL(key)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(modifier)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    zend_long keyValue = 0;
    bool keyIsString = false;
    char keyChar = '\0';
    if (Z_TYPE_P(key) == IS_LONG) {
        keyValue = Z_LVAL_P(key);
    } else if (Z_TYPE_P(key) == IS_STRING && Z_STRLEN_P(key) > 0) {
        keyValue = (unsigned char) Z_STRVAL_P(key)[0];
        keyIsString = true;
        keyChar = Z_STRVAL_P(key)[0];
    } else {
        zend_type_error("QTest::keyRelease() expects an integer key code or single-character string.");
        return;
    }

    if (!qt_qtest_handle_window_or_widget(
        target,
        [keyValue, modifier, delay](QWindow *window) { qt_qtest_key_release_on_window(window, keyValue, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [keyValue, modifier, delay, keyIsString, keyChar](QWidget *widget) {
            if (keyIsString) {
                QTest::keyRelease(widget, keyChar, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay);
            } else {
                QTest::keyRelease(widget, (Qt::Key) keyValue, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay);
            }
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::keyRelease() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, keyClick)
{
    zval *target = NULL;
    zval *key = NULL;
    zend_long modifier = 0;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 4)
        Z_PARAM_ZVAL(target)
        Z_PARAM_ZVAL(key)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(modifier)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    zend_long keyValue = 0;
    bool keyIsString = false;
    char keyChar = '\0';
    if (Z_TYPE_P(key) == IS_LONG) {
        keyValue = Z_LVAL_P(key);
    } else if (Z_TYPE_P(key) == IS_STRING && Z_STRLEN_P(key) > 0) {
        keyValue = (unsigned char) Z_STRVAL_P(key)[0];
        keyIsString = true;
        keyChar = Z_STRVAL_P(key)[0];
    } else {
        zend_type_error("QTest::keyClick() expects an integer key code or single-character string.");
        return;
    }

    if (!qt_qtest_handle_window_or_widget(
        target,
        [keyValue, modifier, delay](QWindow *window) { qt_qtest_key_click_on_window(window, keyValue, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [keyValue, modifier, delay, keyIsString, keyChar](QWidget *widget) {
            if (keyIsString) {
                QTest::keyClick(widget, keyChar, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay);
            } else {
                QTest::keyClick(widget, (Qt::Key) keyValue, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay);
            }
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::keyClick() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, keyClicks)
{
    zval *target = NULL;
    zend_string *sequence = NULL;
    zend_long modifier = 0;
    zend_long delay = -1;

    ZEND_PARSE_PARAMETERS_START(2, 4)
        Z_PARAM_ZVAL(target)
        Z_PARAM_STR(sequence)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(modifier)
        Z_PARAM_LONG(delay)
    ZEND_PARSE_PARAMETERS_END();

    if (!qt_qtest_handle_window_or_widget(
        target,
        [sequence, modifier, delay](QWindow *window) { qt_qtest_key_clicks_on_window(window, sequence, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay); },
@if($ctx->includesModule('QtWidgets'))
        [sequence, modifier, delay](QWidget *widget) {
            QString text = qt_qtest_string_from_zend(sequence);
            QTest::keyClicks(widget, text, qt_qtest_keyboard_modifiers_from_zend(modifier), (int) delay);
        }
@else
        [](QWidget *) {}
@endif
    )) {
        zend_type_error("QTest::keyClicks() expects a QWindow or QWidget target.");
    }
}

PHP_METHOD(Qt_Test_QTest, wheelEvent)
{
    zval *windowValue = NULL;
    zval *pos = NULL;
    zval *angleDelta = NULL;
    zval *pixelDelta = NULL;
    zend_long stateKey = 0;
    zend_long phase = 0;

    ZEND_PARSE_PARAMETERS_START(3, 6)
        Z_PARAM_ZVAL(windowValue)
        Z_PARAM_ZVAL(pos)
        Z_PARAM_ZVAL(angleDelta)
        Z_PARAM_OPTIONAL
        Z_PARAM_ZVAL(pixelDelta)
        Z_PARAM_LONG(stateKey)
        Z_PARAM_LONG(phase)
    ZEND_PARSE_PARAMETERS_END();

    QWindow *window = qt_qtest_window_from_zval(windowValue);
    if (window == NULL) {
        zend_type_error("QTest::wheelEvent() expects a QWindow target.");
        return;
    }

    if (pos == NULL || Z_TYPE_P(pos) != IS_OBJECT || angleDelta == NULL || Z_TYPE_P(angleDelta) != IS_OBJECT) {
        zend_type_error("QTest::wheelEvent() expects QPointF pos and QPoint angleDelta objects.");
        return;
    }

    QPointF pointPos = *qt_qpointf_from_obj(Z_OBJ_P(pos))->native_ptr;
    QPoint angle = *qt_qpoint_from_obj(Z_OBJ_P(angleDelta))->native_ptr;
    QPoint pixel = pixelDelta != NULL && Z_TYPE_P(pixelDelta) == IS_OBJECT
        ? *qt_qpoint_from_obj(Z_OBJ_P(pixelDelta))->native_ptr
        : QPoint(0, 0);

    QTest::wheelEvent(
        window,
        pointPos,
        angle,
        pixel,
        qt_qtest_keyboard_modifiers_from_zend(stateKey),
        (Qt::ScrollPhase) phase
    );
}
@endif

static const zend_function_entry qt_qtest_methods[] = {
    ZEND_ME(Qt_Test_QTest, qExec, arginfo_class_Qt_Test_QTest_qExec, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qWait, arginfo_class_Qt_Test_QTest_qWait, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, setMainSourcePath, arginfo_class_Qt_Test_QTest_setMainSourcePath, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, setThrowOnFail, arginfo_class_Qt_Test_QTest_setThrowOnFail, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, setThrowOnSkip, arginfo_class_Qt_Test_QTest_setThrowOnSkip, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qVerify, arginfo_class_Qt_Test_QTest_qVerify, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qFail, arginfo_class_Qt_Test_QTest_qFail, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qSkip, arginfo_class_Qt_Test_QTest_qSkip, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qExpectFail, arginfo_class_Qt_Test_QTest_qExpectFail, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qCaught, arginfo_class_Qt_Test_QTest_qCaught, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, ignoreMessage, arginfo_class_Qt_Test_QTest_ignoreMessage, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, failOnWarning, arginfo_class_Qt_Test_QTest_failOnWarning, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qExtractTestData, arginfo_class_Qt_Test_QTest_qExtractTestData, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qFindTestData, arginfo_class_Qt_Test_QTest_qFindTestData, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qData, arginfo_class_Qt_Test_QTest_qData, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qGlobalData, arginfo_class_Qt_Test_QTest_qGlobalData, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, qElementData, arginfo_class_Qt_Test_QTest_qElementData, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, testObject, arginfo_class_Qt_Test_QTest_testObject, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, currentAppName, arginfo_class_Qt_Test_QTest_currentAppName, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, currentTestFunction, arginfo_class_Qt_Test_QTest_currentTestFunction, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, currentDataTag, arginfo_class_Qt_Test_QTest_currentDataTag, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, currentGlobalDataTag, arginfo_class_Qt_Test_QTest_currentGlobalDataTag, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, currentTestFailed, arginfo_class_Qt_Test_QTest_currentTestFailed, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, currentTestResolved, arginfo_class_Qt_Test_QTest_currentTestResolved, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, runningTest, arginfo_class_Qt_Test_QTest_runningTest, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, asciiToKey, arginfo_class_Qt_Test_QTest_asciiToKey, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, keyToAscii, arginfo_class_Qt_Test_QTest_keyToAscii, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
@if($ctx->includesModule('QtGui'))
    ZEND_ME(Qt_Test_QTest, mousePress, arginfo_class_Qt_Test_QTest_mousePress, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, mouseRelease, arginfo_class_Qt_Test_QTest_mouseRelease, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, mouseClick, arginfo_class_Qt_Test_QTest_mouseClick, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, mouseDClick, arginfo_class_Qt_Test_QTest_mouseDClick, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, mouseMove, arginfo_class_Qt_Test_QTest_mouseMove, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, keyPress, arginfo_class_Qt_Test_QTest_keyPress, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, keyRelease, arginfo_class_Qt_Test_QTest_keyRelease, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, keyClick, arginfo_class_Qt_Test_QTest_keyClick, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, keyClicks, arginfo_class_Qt_Test_QTest_keyClicks, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
    ZEND_ME(Qt_Test_QTest, wheelEvent, arginfo_class_Qt_Test_QTest_wheelEvent, ZEND_ACC_PUBLIC | ZEND_ACC_STATIC)
@endif
    ZEND_FE_END
};

PHP_MINIT_FUNCTION(qt_qtest)
{
    zend_class_entry ce;
    INIT_NS_CLASS_ENTRY(ce, "Qt\\Test", "QTest", qt_qtest_methods);

    qt_ce_QTest = zend_register_internal_class(&ce);
    qt_ce_QTest->ce_flags |= ZEND_ACC_ABSTRACT;

    return SUCCESS;
}
