/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Qt\Test\QTest support declarations.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#ifdef __cplusplus
}
#endif

#include "qt_php_compat.h"
#include "php_qt.h"

PHP_MINIT_FUNCTION(qt_qtest);
