/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Isolated PHP worker runtime support for Qt\Core\QThreadRuntime.
 */

#include "qt_qthreadruntime.h"
#include "qt_qthreadruntime_arginfo.h"

#include <QtCore/QThread>
#include <TSRM.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_smart_str.h>
#include <ext/standard/php_var.h>
#include <main/php_main.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <deque>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

zend_class_entry *qt_ce_QThreadRuntime = NULL;
zend_object_handlers qt_qthreadruntime_handlers;
static thread_local bool qt_qthreadruntime_tls_worker_request = false;

struct qt_qthreadruntime_error {
    bool is_fatal{false};
    zend_long code{0};
    std::string class_name;
    std::string message;
};

struct qt_qthreadruntime_result {
    bool ready{false};
    bool success{false};
    bool canceled{false};
    std::string payload;
    qt_qthreadruntime_error error;
};

struct qt_qthreadruntime_job {
    uint64_t id{0};
    std::string callable;
    std::string args_payload;
    std::atomic_bool canceled{false};
};

enum class qt_qthreadruntime_await_status {
    ready,
    timeout,
    unknown,
};

class qt_qthreadruntime_state;

class qt_qthreadruntime_worker_thread final : public QThread {
public:
    explicit qt_qthreadruntime_worker_thread(std::weak_ptr<qt_qthreadruntime_state> state)
        : state_(std::move(state))
    {
    }

    void run() override;

private:
    std::weak_ptr<qt_qthreadruntime_state> state_;
};

class qt_qthreadruntime_state final : public std::enable_shared_from_this<qt_qthreadruntime_state> {
public:
    bool start()
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (running_) {
            return true;
        }

#if !defined(ZTS)
        return false;
#else
        stopping_ = false;
        worker_bootstrap_failed_ = false;
        worker_thread_ = std::make_unique<qt_qthreadruntime_worker_thread>(shared_from_this());
        worker_thread_->start();
        running_ = true;
        return true;
#endif
    }

    bool stop(zend_long timeout_ms)
    {
        std::unique_lock<std::mutex> lock(mutex_);
        if (!running_) {
            return true;
        }

        stopping_ = true;
        job_cv_.notify_all();
        lock.unlock();

        bool stopped = true;
        if (worker_thread_ != nullptr && worker_thread_->isRunning()) {
            unsigned long wait_ms = timeout_ms > 0 ? (unsigned long) timeout_ms : 0UL;
            if (!worker_thread_->wait(wait_ms)) {
                worker_thread_->requestInterruption();
                job_cv_.notify_all();
                stopped = worker_thread_->wait(500);
            }
        }

        lock.lock();
        running_ = false;
        worker_thread_.reset();
        lock.unlock();

        return stopped;
    }

    bool isRunning() const
    {
        std::lock_guard<std::mutex> lock(mutex_);
        return running_;
    }

    bool submit(std::string callable, std::string args_payload, uint64_t *job_id, std::string *error)
    {
        if (job_id == nullptr || error == nullptr) {
            return false;
        }

        std::lock_guard<std::mutex> lock(mutex_);
        if (!running_) {
            *error = "Worker runtime is not started.";
            return false;
        }

        if (stopping_) {
            *error = "Worker runtime is stopping.";
            return false;
        }

        auto job = std::make_shared<qt_qthreadruntime_job>();
        job->id = next_job_id_++;
        job->callable = std::move(callable);
        job->args_payload = std::move(args_payload);

        jobs_[job->id] = job;
        queue_.push_back(job);
        stats_enqueued_++;
        *job_id = job->id;

        job_cv_.notify_one();
        return true;
    }

    bool cancel(uint64_t job_id)
    {
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = jobs_.find(job_id);
        if (it == jobs_.end()) {
            return false;
        }

        it->second->canceled.store(true, std::memory_order_release);
        stats_canceled_++;
        return true;
    }

    qt_qthreadruntime_await_status await(uint64_t job_id, zend_long timeout_ms, qt_qthreadruntime_result *result)
    {
        if (result == nullptr) {
            return qt_qthreadruntime_await_status::unknown;
        }

        std::unique_lock<std::mutex> lock(mutex_);
        auto done = [this, job_id]() -> bool {
            return results_.find(job_id) != results_.end();
        };

        if (timeout_ms <= 0) {
            result_cv_.wait(lock, done);
        } else if (!result_cv_.wait_for(lock, std::chrono::milliseconds(timeout_ms), done)) {
            stats_timeouts_++;
            return qt_qthreadruntime_await_status::timeout;
        }

        auto result_it = results_.find(job_id);
        if (result_it == results_.end()) {
            return qt_qthreadruntime_await_status::unknown;
        }

        *result = std::move(result_it->second);
        results_.erase(result_it);
        return qt_qthreadruntime_await_status::ready;
    }

    void fillStats(zval *return_value) const
    {
        std::lock_guard<std::mutex> lock(mutex_);

        array_init(return_value);
        add_assoc_bool(return_value, "running", running_);
        add_assoc_long(return_value, "queued", (zend_long) queue_.size());
        add_assoc_long(return_value, "pending_results", (zend_long) results_.size());
        add_assoc_long(return_value, "enqueued", (zend_long) stats_enqueued_);
        add_assoc_long(return_value, "drained", (zend_long) stats_drained_);
        add_assoc_long(return_value, "canceled", (zend_long) stats_canceled_);
        add_assoc_long(return_value, "timeouts", (zend_long) stats_timeouts_);
        add_assoc_long(return_value, "worker_crash", (zend_long) stats_worker_crash_);
        add_assoc_bool(return_value, "worker_bootstrap_failed", worker_bootstrap_failed_);
    }

    void workerMain()
    {
#if !defined(ZTS)
        return;
#else
        qt_qthreadruntime_tls_worker_request = true;
        ts_resource(0);
        TSRMLS_CACHE_UPDATE();

        if (php_request_startup() != SUCCESS) {
            std::lock_guard<std::mutex> lock(mutex_);
            worker_bootstrap_failed_ = true;
            running_ = false;
            stopping_ = true;
            return;
        }

        while (true) {
            std::shared_ptr<qt_qthreadruntime_job> job;
            {
                std::unique_lock<std::mutex> lock(mutex_);
                job_cv_.wait(lock, [this]() {
                    return stopping_ || !queue_.empty();
                });

                if (stopping_ && queue_.empty()) {
                    break;
                }

                job = queue_.front();
                queue_.pop_front();
            }

            if (!job) {
                continue;
            }

            qt_qthreadruntime_result result = executeJob(job);

            {
                std::lock_guard<std::mutex> lock(mutex_);
                jobs_.erase(job->id);
                result.ready = true;
                results_[job->id] = std::move(result);
                stats_drained_++;
            }
            result_cv_.notify_all();
        }

        gc_collect_cycles();
        php_request_shutdown(NULL);
        ts_free_thread();
        qt_qthreadruntime_tls_worker_request = false;
#endif
    }

    static bool serializeValue(zval *value, std::string *out)
    {
        if (out == nullptr) {
            return false;
        }

        smart_str buffer = {0};
        php_serialize_data_t var_hash;
        PHP_VAR_SERIALIZE_INIT(var_hash);
        php_var_serialize(&buffer, value, &var_hash);
        PHP_VAR_SERIALIZE_DESTROY(var_hash);
        smart_str_0(&buffer);

        if (buffer.s == NULL) {
            return false;
        }

        out->assign(ZSTR_VAL(buffer.s), ZSTR_LEN(buffer.s));
        smart_str_free(&buffer);
        return true;
    }

    static bool unserializeValue(const std::string &payload, zval *out)
    {
        if (out == nullptr) {
            return false;
        }

        const unsigned char *ptr = (const unsigned char *) payload.data();
        const unsigned char *max = ptr + payload.size();
        php_unserialize_data_t var_hash;
        PHP_VAR_UNSERIALIZE_INIT(var_hash);
        ZVAL_NULL(out);
        bool ok = php_var_unserialize(out, &ptr, max, &var_hash) != 0;
        PHP_VAR_UNSERIALIZE_DESTROY(var_hash);

        return ok && ptr == max;
    }

    static qt_qthreadruntime_result makeErrorResult(std::string class_name, std::string message, zend_long code = 0, bool fatal = false)
    {
        qt_qthreadruntime_result result;
        result.success = false;
        result.canceled = false;
        result.error.class_name = std::move(class_name);
        result.error.message = std::move(message);
        result.error.code = code;
        result.error.is_fatal = fatal;
        return result;
    }

    qt_qthreadruntime_result executeJob(const std::shared_ptr<qt_qthreadruntime_job> &job)
    {
        if (job->canceled.load(std::memory_order_acquire)) {
            qt_qthreadruntime_result result;
            result.success = false;
            result.canceled = true;
            return result;
        }

        qt_qthreadruntime_result result;
        bool bailed_out = false;

        zend_first_try {
            zval args_zv;
            if (!unserializeValue(job->args_payload, &args_zv) || Z_TYPE(args_zv) != IS_ARRAY) {
                if (Z_TYPE(args_zv) != IS_UNDEF) {
                    zval_ptr_dtor(&args_zv);
                }
                return makeErrorResult("RuntimeException", "Failed to unserialize worker arguments.");
            }

            zval callable_zv;
            ZVAL_STRINGL(&callable_zv, job->callable.c_str(), job->callable.size());

            uint32_t argc = (uint32_t) zend_hash_num_elements(Z_ARRVAL(args_zv));
            std::vector<zval> params;
            params.reserve(argc);
            zval *entry = NULL;
            ZEND_HASH_FOREACH_VAL(Z_ARRVAL(args_zv), entry) {
                zval param;
                ZVAL_COPY(&param, entry);
                params.push_back(param);
            } ZEND_HASH_FOREACH_END();

            zval retval;
            ZVAL_UNDEF(&retval);

            zend_fcall_info fci;
            zend_fcall_info_cache fcc;
            if (zend_fcall_info_init(&callable_zv, 0, &fci, &fcc, NULL, NULL) != SUCCESS) {
                for (zval &param : params) {
                    zval_ptr_dtor(&param);
                }
                zval_ptr_dtor(&callable_zv);
                zval_ptr_dtor(&args_zv);
                return makeErrorResult("RuntimeException", "Worker callable is not invokable.");
            }

            fci.retval = &retval;
            fci.param_count = argc;
            fci.params = argc > 0 ? params.data() : NULL;

            int call_status = zend_call_function(&fci, &fcc);

            for (zval &param : params) {
                zval_ptr_dtor(&param);
            }
            zval_ptr_dtor(&callable_zv);
            zval_ptr_dtor(&args_zv);

            if (call_status != SUCCESS) {
                if (!Z_ISUNDEF(retval)) {
                    zval_ptr_dtor(&retval);
                }
                return makeErrorResult("RuntimeException", "zend_call_function() failed in worker runtime.");
            }

            if (EG(exception) != NULL) {
                zval ex_zv;
                ZVAL_OBJ_COPY(&ex_zv, EG(exception));
                zend_clear_exception();

                zend_object *ex_obj = Z_OBJ(ex_zv);
                zend_long error_code = 0;
                std::string class_name = ex_obj != NULL && ex_obj->ce != NULL
                    ? std::string(ZSTR_VAL(ex_obj->ce->name), ZSTR_LEN(ex_obj->ce->name))
                    : std::string("RuntimeException");
                std::string message = "Worker exception.";
                if (ex_obj != NULL) {
                    zval rv;
                    zval *message_prop = zend_read_property_ex(ex_obj->ce, ex_obj, ZSTR_KNOWN(ZEND_STR_MESSAGE), 1, &rv);
                    if (message_prop != NULL) {
                        zend_string *msg = zval_get_string(message_prop);
                        if (msg != NULL) {
                            message.assign(ZSTR_VAL(msg), ZSTR_LEN(msg));
                            zend_string_release(msg);
                        }
                    }

                    zval *code_prop = zend_read_property_ex(ex_obj->ce, ex_obj, ZSTR_KNOWN(ZEND_STR_CODE), 1, &rv);
                    if (code_prop != NULL) {
                        error_code = zval_get_long(code_prop);
                    }
                }

                zval_ptr_dtor(&ex_zv);
                if (!Z_ISUNDEF(retval)) {
                    zval_ptr_dtor(&retval);
                }
                return makeErrorResult(class_name, message, error_code, false);
            }

            if (!serializeValue(&retval, &result.payload)) {
                zval_ptr_dtor(&retval);
                return makeErrorResult("RuntimeException", "Failed to serialize worker result.");
            }

            zval_ptr_dtor(&retval);
            result.success = true;
            result.canceled = false;
        } zend_catch {
            bailed_out = true;
        } zend_end_try();

        if (bailed_out) {
            std::lock_guard<std::mutex> lock(mutex_);
            stats_worker_crash_++;
            return makeErrorResult("RuntimeException", "Worker bailed out while executing the job.", 0, true);
        }

        return result;
    }

private:
    mutable std::mutex mutex_;
    std::condition_variable job_cv_;
    std::condition_variable result_cv_;
    std::deque<std::shared_ptr<qt_qthreadruntime_job>> queue_;
    std::unordered_map<uint64_t, std::shared_ptr<qt_qthreadruntime_job>> jobs_;
    std::unordered_map<uint64_t, qt_qthreadruntime_result> results_;
    std::unique_ptr<qt_qthreadruntime_worker_thread> worker_thread_;
    uint64_t next_job_id_{1};
    uint64_t stats_enqueued_{0};
    uint64_t stats_drained_{0};
    uint64_t stats_canceled_{0};
    uint64_t stats_timeouts_{0};
    uint64_t stats_worker_crash_{0};
    bool running_{false};
    bool stopping_{false};
    bool worker_bootstrap_failed_{false};
};

void qt_qthreadruntime_worker_thread::run()
{
    std::shared_ptr<qt_qthreadruntime_state> state = state_.lock();
    if (!state) {
        return;
    }

    state->workerMain();
}

static std::mutex qt_qthreadruntime_registry_mutex;
static std::vector<std::weak_ptr<qt_qthreadruntime_state>> qt_qthreadruntime_registry;

void qt_qthreadruntime_register(const std::shared_ptr<qt_qthreadruntime_state> &state)
{
    std::lock_guard<std::mutex> lock(qt_qthreadruntime_registry_mutex);
    qt_qthreadruntime_registry.erase(
        std::remove_if(
            qt_qthreadruntime_registry.begin(),
            qt_qthreadruntime_registry.end(),
            [](const std::weak_ptr<qt_qthreadruntime_state> &entry) {
                return entry.expired();
            }
        ),
        qt_qthreadruntime_registry.end()
    );
    qt_qthreadruntime_registry.emplace_back(state);
}

void qt_qthreadruntime_unregister(const std::shared_ptr<qt_qthreadruntime_state> &state)
{
    std::lock_guard<std::mutex> lock(qt_qthreadruntime_registry_mutex);
    qt_qthreadruntime_registry.erase(
        std::remove_if(
            qt_qthreadruntime_registry.begin(),
            qt_qthreadruntime_registry.end(),
            [&state](const std::weak_ptr<qt_qthreadruntime_state> &entry) {
                std::shared_ptr<qt_qthreadruntime_state> resolved = entry.lock();
                return !resolved || resolved.get() == state.get();
            }
        ),
        qt_qthreadruntime_registry.end()
    );
}

PHP_QT_API void qt_qthreadruntime_shutdown_all(zend_long timeout_ms)
{
    if (qt_qthreadruntime_tls_worker_request) {
        return;
    }

    std::vector<std::shared_ptr<qt_qthreadruntime_state>> runtimes;
    {
        std::lock_guard<std::mutex> lock(qt_qthreadruntime_registry_mutex);
        runtimes.reserve(qt_qthreadruntime_registry.size());
        for (const std::weak_ptr<qt_qthreadruntime_state> &entry : qt_qthreadruntime_registry) {
            std::shared_ptr<qt_qthreadruntime_state> runtime = entry.lock();
            if (runtime) {
                runtimes.push_back(runtime);
            }
        }
    }

    for (const std::shared_ptr<qt_qthreadruntime_state> &runtime : runtimes) {
        runtime->stop(timeout_ms);
    }
}

PHP_QT_API bool qt_qthreadruntime_is_worker_request_context(void)
{
    return qt_qthreadruntime_tls_worker_request;
}

static inline qt_qthreadruntime_state *qt_qthreadruntime_fetch_state(zval *zv)
{
    qt_qthreadruntime_object *intern = Z_QTHREADRUNTIME_P(zv);
    if (intern->state == NULL || intern->state->get() == NULL) {
        return NULL;
    }

    return intern->state->get();
}

static zend_object *qt_qthreadruntime_create_object(zend_class_entry *ce)
{
    qt_qthreadruntime_object *intern = (qt_qthreadruntime_object *) zend_object_alloc(
        sizeof(qt_qthreadruntime_object), ce
    );
    std::shared_ptr<qt_qthreadruntime_state> state = std::make_shared<qt_qthreadruntime_state>();
    intern->state = new std::shared_ptr<qt_qthreadruntime_state>(state);
    qt_qthreadruntime_register(state);

    zend_object_std_init(&intern->std, ce);
    object_properties_init(&intern->std, ce);

    return &intern->std;
}

static void qt_qthreadruntime_free_object(zend_object *object)
{
    qt_qthreadruntime_object *intern = qt_qthreadruntime_from_obj(object);

    if (intern->state != NULL) {
        std::shared_ptr<qt_qthreadruntime_state> state = *intern->state;
        if (state) {
            state->stop(2000);
            qt_qthreadruntime_unregister(state);
        }
        delete intern->state;
        intern->state = NULL;
    }

    zend_object_std_dtor(&intern->std);
}

static HashTable *qt_qthreadruntime_get_gc(zend_object *object, zval **table, int *n)
{
    *table = NULL;
    *n = 0;
    return zend_std_get_properties(object);
}

PHP_METHOD(QThreadRuntime, __construct)
{
    ZEND_PARSE_PARAMETERS_NONE();
}

PHP_METHOD(QThreadRuntime, start)
{
    ZEND_PARSE_PARAMETERS_NONE();

#if !defined(ZTS)
    zend_throw_error(NULL, "Qt\\Core\\QThreadRuntime requires a ZTS PHP build.");
    RETURN_THROWS();
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        zend_throw_error(NULL, "Invalid QThreadRuntime state.");
        RETURN_THROWS();
    }

    if (!state->start()) {
        zend_throw_error(NULL, "Failed to start worker runtime.");
        RETURN_THROWS();
    }
#endif
}

PHP_METHOD(QThreadRuntime, submit)
{
    zend_string *callable = NULL;
    zval *args = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_STR(callable)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY(args)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_error(NULL, "Qt\\Core\\QThreadRuntime requires a ZTS PHP build.");
    RETURN_THROWS();
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        zend_throw_error(NULL, "Invalid QThreadRuntime state.");
        RETURN_THROWS();
    }

    if (ZSTR_LEN(callable) == 0) {
        zend_argument_value_error(1, "must not be empty");
        RETURN_THROWS();
    }

    if (strstr(ZSTR_VAL(callable), "::") != NULL) {
        zend_argument_value_error(1, "must be a global function name in phase 3A");
        RETURN_THROWS();
    }

    if (!state->start()) {
        zend_throw_error(NULL, "Failed to start worker runtime.");
        RETURN_THROWS();
    }

    zval serialized_args_input;
    if (args != NULL) {
        ZVAL_COPY(&serialized_args_input, args);
    } else {
        array_init(&serialized_args_input);
    }

    std::string args_payload;
    if (!qt_qthreadruntime_state::serializeValue(&serialized_args_input, &args_payload)) {
        zval_ptr_dtor(&serialized_args_input);
        zend_throw_error(NULL, "Failed to serialize worker arguments.");
        RETURN_THROWS();
    }
    zval_ptr_dtor(&serialized_args_input);

    uint64_t job_id = 0;
    std::string submit_error;
    if (!state->submit(
        std::string(ZSTR_VAL(callable), ZSTR_LEN(callable)),
        std::move(args_payload),
        &job_id,
        &submit_error
    )) {
        zend_throw_error(NULL, "%s", submit_error.c_str());
        RETURN_THROWS();
    }

    RETURN_LONG((zend_long) job_id);
#endif
}

PHP_METHOD(QThreadRuntime, await)
{
    zend_long job_id = 0;
    zend_long timeout_ms = 0;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_LONG(job_id)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout_ms)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_error(NULL, "Qt\\Core\\QThreadRuntime requires a ZTS PHP build.");
    RETURN_THROWS();
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        zend_throw_error(NULL, "Invalid QThreadRuntime state.");
        RETURN_THROWS();
    }

    qt_qthreadruntime_result result;
    qt_qthreadruntime_await_status status = state->await((uint64_t) job_id, timeout_ms, &result);
    if (status == qt_qthreadruntime_await_status::timeout) {
        RETURN_NULL();
    }
    if (status == qt_qthreadruntime_await_status::unknown) {
        zend_throw_error(NULL, "Unknown job id %ld.", job_id);
        RETURN_THROWS();
    }

    if (result.canceled) {
        RETURN_FALSE;
    }

    if (!result.success) {
        zend_class_entry *exception_ce = zend_exception_get_default();
        if (!result.error.class_name.empty()) {
            zend_string *class_name = zend_string_init(result.error.class_name.c_str(), result.error.class_name.size(), 0);
            zend_class_entry *resolved_ce = zend_lookup_class_ex(class_name, NULL, 0);
            zend_string_release(class_name);
            if (resolved_ce != NULL && instanceof_function(resolved_ce, zend_ce_throwable)) {
                exception_ce = resolved_ce;
            }
        }

        const std::string &message = result.error.message.empty()
            ? std::string("Worker runtime execution failed.")
            : result.error.message;
        zend_throw_exception(exception_ce, message.c_str(), result.error.code);
        RETURN_THROWS();
    }

    zval payload;
    if (!qt_qthreadruntime_state::unserializeValue(result.payload, &payload)) {
        zend_throw_error(NULL, "Failed to unserialize worker result payload.");
        RETURN_THROWS();
    }

    ZVAL_COPY_VALUE(return_value, &payload);
#endif
}

PHP_METHOD(QThreadRuntime, cancel)
{
    zend_long job_id = 0;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_LONG(job_id)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    RETURN_FALSE;
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        RETURN_FALSE;
    }

    RETURN_BOOL(state->cancel((uint64_t) job_id));
#endif
}

PHP_METHOD(QThreadRuntime, stop)
{
    zend_long timeout_ms = 5000;
    ZEND_PARSE_PARAMETERS_START(0, 1)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout_ms)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    RETURN_FALSE;
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        RETURN_FALSE;
    }

    RETURN_BOOL(state->stop(timeout_ms));
#endif
}

PHP_METHOD(QThreadRuntime, isRunning)
{
    ZEND_PARSE_PARAMETERS_NONE();

#if !defined(ZTS)
    RETURN_FALSE;
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        RETURN_FALSE;
    }

    RETURN_BOOL(state->isRunning());
#endif
}

PHP_METHOD(QThreadRuntime, stats)
{
    ZEND_PARSE_PARAMETERS_NONE();

#if !defined(ZTS)
    array_init(return_value);
    add_assoc_bool(return_value, "running", false);
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        array_init(return_value);
        add_assoc_bool(return_value, "running", false);
        return;
    }

    state->fillStats(return_value);
#endif
}

static const zend_function_entry qt_qthreadruntime_methods[] = {
    ZEND_ME(QThreadRuntime, __construct, arginfo_class_Qt_Core_QThreadRuntime___construct, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, start, arginfo_class_Qt_Core_QThreadRuntime_start, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, submit, arginfo_class_Qt_Core_QThreadRuntime_submit, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, await, arginfo_class_Qt_Core_QThreadRuntime_await, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, cancel, arginfo_class_Qt_Core_QThreadRuntime_cancel, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, stop, arginfo_class_Qt_Core_QThreadRuntime_stop, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, isRunning, arginfo_class_Qt_Core_QThreadRuntime_isRunning, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, stats, arginfo_class_Qt_Core_QThreadRuntime_stats, ZEND_ACC_PUBLIC)
    ZEND_FE_END
};

PHP_MINIT_FUNCTION(qt_qthreadruntime)
{
    zend_class_entry ce;
    INIT_NS_CLASS_ENTRY(ce, "Qt\\Core", "QThreadRuntime", qt_qthreadruntime_methods);
    ce.create_object = qt_qthreadruntime_create_object;

    qt_ce_QThreadRuntime = zend_register_internal_class(&ce);
    qt_ce_QThreadRuntime->ce_flags |= ZEND_ACC_FINAL;

    memcpy(&qt_qthreadruntime_handlers, &std_object_handlers, sizeof(zend_object_handlers));
    qt_qthreadruntime_handlers.offset = XtOffsetOf(qt_qthreadruntime_object, std);
    qt_qthreadruntime_handlers.free_obj = qt_qthreadruntime_free_object;
    qt_qthreadruntime_handlers.clone_obj = NULL;
    qt_qthreadruntime_handlers.get_gc = qt_qthreadruntime_get_gc;
    qt_ce_QThreadRuntime->default_object_handlers = &qt_qthreadruntime_handlers;

    return SUCCESS;
}
