/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Isolated PHP worker runtime support for Qt\Core\QThreadRuntime.
 */

#ifndef QT_QTHREADRUNTIME_H
#define QT_QTHREADRUNTIME_H

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include <memory>

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

class qt_qthreadruntime_state;

typedef struct _qt_qthreadruntime_object {
    std::shared_ptr<qt_qthreadruntime_state> *state;
    zend_object std; /* MUST be last */
} qt_qthreadruntime_object;

extern PHP_QT_API zend_class_entry *qt_ce_QThreadRuntime;
extern zend_object_handlers qt_qthreadruntime_handlers;

static inline qt_qthreadruntime_object *qt_qthreadruntime_from_obj(zend_object *obj)
{
    return (qt_qthreadruntime_object *)((char *)(obj) - XtOffsetOf(qt_qthreadruntime_object, std));
}

#define Z_QTHREADRUNTIME_P(zv) qt_qthreadruntime_from_obj(Z_OBJ_P(zv))

PHP_MINIT_FUNCTION(qt_qthreadruntime);
PHP_QT_API void qt_qthreadruntime_shutdown_all(zend_long timeout_ms);
PHP_QT_API bool qt_qthreadruntime_is_worker_request_context(void);

#endif /* QT_QTHREADRUNTIME_H */
