/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Isolated PHP worker runtime support for Qt\Core\QThreadRuntime.
 */

#include "qt_qthreadruntime.h"
#include "qt_qthreadruntime_arginfo.h"

#include <QtCore/QThread>
#include <TSRM.h>
#include <Zend/zend_closures.h>
#include <Zend/zend_compile.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_stream.h>
#include <ext/standard/info.h>
#include <main/php_main.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstdlib>
#include <cstdint>
#include <cstring>
#include <deque>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

zend_class_entry *qt_ce_QThreadRuntime = NULL;
zend_object_handlers qt_qthreadruntime_handlers;
static thread_local bool qt_qthreadruntime_tls_worker_request = false;
static constexpr size_t QT_QTHREADRUNTIME_MAX_QUEUE_DEPTH_DEFAULT = 4096;
static std::atomic_uint64_t qt_qthreadruntime_total_enqueued{0};
static std::atomic_uint64_t qt_qthreadruntime_total_drained{0};
static std::atomic_uint64_t qt_qthreadruntime_total_canceled{0};
static std::atomic_uint64_t qt_qthreadruntime_total_rejected_full{0};
static std::atomic_uint64_t qt_qthreadruntime_total_rejected_stopping{0};
static std::atomic_uint64_t qt_qthreadruntime_total_timeouts{0};
static std::atomic_uint64_t qt_qthreadruntime_total_worker_crash{0};

static size_t qt_qthreadruntime_env_queue_depth()
{
    const char *raw = getenv("QT_QTHREADRUNTIME_MAX_QUEUE_DEPTH");
    if (raw == NULL || *raw == '\0') {
        return QT_QTHREADRUNTIME_MAX_QUEUE_DEPTH_DEFAULT;
    }

    char *end = NULL;
    long parsed = strtol(raw, &end, 10);
    if (end == raw || parsed <= 0) {
        return QT_QTHREADRUNTIME_MAX_QUEUE_DEPTH_DEFAULT;
    }

    return (size_t) parsed;
}

struct qt_qthreadruntime_error {
    bool is_fatal{false};
    zend_long code{0};
    std::string class_name;
    std::string message;
};

struct qt_qthreadruntime_result {
    bool ready{false};
    bool success{false};
    bool canceled{false};
    std::string payload;
    qt_qthreadruntime_error error;
};

struct qt_qthreadruntime_job {
    uint64_t id{0};
    std::string callable_payload;
    std::string args_payload;
    std::atomic_bool canceled{false};
};

enum class qt_qthreadruntime_await_status {
    ready,
    timeout,
    unknown,
};

class qt_qthreadruntime_state;

class qt_qthreadruntime_worker_thread final : public QThread {
public:
    explicit qt_qthreadruntime_worker_thread(std::weak_ptr<qt_qthreadruntime_state> state)
        : state_(std::move(state))
    {
    }

    void run() override;

private:
    std::weak_ptr<qt_qthreadruntime_state> state_;
};

class qt_qthreadruntime_state final : public std::enable_shared_from_this<qt_qthreadruntime_state> {
public:
    bool setBootstrapScript(const std::string &path, std::string *error)
    {
        if (error == nullptr) {
            return false;
        }

        std::lock_guard<std::mutex> lock(mutex_);
        if (running_) {
            *error = "Cannot change bootstrap script while worker runtime is running.";
            return false;
        }

        bootstrap_script_ = path;
        return true;
    }

    bool start()
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (running_) {
            return true;
        }

#if !defined(ZTS)
        return false;
#else
        stopping_ = false;
        worker_bootstrap_failed_ = false;
        worker_thread_ = std::make_unique<qt_qthreadruntime_worker_thread>(shared_from_this());
        worker_thread_->start();
        running_ = true;
        return true;
#endif
    }

    bool stop(zend_long timeout_ms)
    {
        std::unique_lock<std::mutex> lock(mutex_);
        if (!running_) {
            return true;
        }

        stopping_ = true;
        while (!queue_.empty()) {
            std::shared_ptr<qt_qthreadruntime_job> job = queue_.front();
            queue_.pop_front();
            if (!job) {
                continue;
            }

            job->canceled.store(true, std::memory_order_release);
            jobs_.erase(job->id);
            qt_qthreadruntime_result canceled_result;
            canceled_result.ready = true;
            canceled_result.success = false;
            canceled_result.canceled = true;
            results_[job->id] = std::move(canceled_result);
            stats_canceled_++;
            qt_qthreadruntime_total_canceled.fetch_add(1, std::memory_order_acq_rel);
        }

        result_cv_.notify_all();
        job_cv_.notify_all();
        lock.unlock();

        bool stopped = true;
        if (worker_thread_ != nullptr && worker_thread_->isRunning()) {
            unsigned long wait_ms = timeout_ms > 0 ? (unsigned long) timeout_ms : 0UL;
            if (!worker_thread_->wait(wait_ms)) {
                worker_thread_->requestInterruption();
                job_cv_.notify_all();
                stopped = worker_thread_->wait(500);
            }
        }

        lock.lock();
        running_ = false;
        worker_thread_.reset();
        lock.unlock();

        return stopped;
    }

    bool isRunning() const
    {
        std::lock_guard<std::mutex> lock(mutex_);
        return running_;
    }

    bool submit(std::string callable_payload, std::string args_payload, uint64_t *job_id, std::string *error)
    {
        if (job_id == nullptr || error == nullptr) {
            return false;
        }

        std::lock_guard<std::mutex> lock(mutex_);
        if (!running_) {
            *error = "Worker runtime is not started.";
            return false;
        }

        if (stopping_) {
            stats_rejected_stopping_++;
            qt_qthreadruntime_total_rejected_stopping.fetch_add(1, std::memory_order_acq_rel);
            *error = "Worker runtime is stopping.";
            return false;
        }

        if (queue_.size() >= max_queue_depth_) {
            stats_rejected_full_++;
            qt_qthreadruntime_total_rejected_full.fetch_add(1, std::memory_order_acq_rel);
            *error = "Worker runtime queue is full.";
            return false;
        }

        auto job = std::make_shared<qt_qthreadruntime_job>();
        job->id = next_job_id_++;
        job->callable_payload = std::move(callable_payload);
        job->args_payload = std::move(args_payload);

        jobs_[job->id] = job;
        queue_.push_back(job);
        stats_enqueued_++;
        qt_qthreadruntime_total_enqueued.fetch_add(1, std::memory_order_acq_rel);
        *job_id = job->id;

        job_cv_.notify_one();
        return true;
    }

    bool cancel(uint64_t job_id)
    {
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = jobs_.find(job_id);
        if (it == jobs_.end()) {
            return false;
        }

        it->second->canceled.store(true, std::memory_order_release);
        stats_canceled_++;
        return true;
    }

    qt_qthreadruntime_await_status await(uint64_t job_id, zend_long timeout_ms, qt_qthreadruntime_result *result)
    {
        if (result == nullptr) {
            return qt_qthreadruntime_await_status::unknown;
        }

        std::unique_lock<std::mutex> lock(mutex_);
        auto done = [this, job_id]() -> bool {
            return results_.find(job_id) != results_.end();
        };

        if (timeout_ms <= 0) {
            result_cv_.wait(lock, done);
        } else if (!result_cv_.wait_for(lock, std::chrono::milliseconds(timeout_ms), done)) {
            stats_timeouts_++;
            qt_qthreadruntime_total_timeouts.fetch_add(1, std::memory_order_acq_rel);
            return qt_qthreadruntime_await_status::timeout;
        }

        auto result_it = results_.find(job_id);
        if (result_it == results_.end()) {
            return qt_qthreadruntime_await_status::unknown;
        }

        *result = std::move(result_it->second);
        results_.erase(result_it);
        return qt_qthreadruntime_await_status::ready;
    }

    void fillStats(zval *return_value) const
    {
        std::lock_guard<std::mutex> lock(mutex_);

        array_init(return_value);
        add_assoc_bool(return_value, "running", running_);
        add_assoc_long(return_value, "queued", (zend_long) queue_.size());
        add_assoc_long(return_value, "queue_max_depth", (zend_long) max_queue_depth_);
        add_assoc_long(return_value, "pending_results", (zend_long) results_.size());
        add_assoc_long(return_value, "enqueued", (zend_long) stats_enqueued_);
        add_assoc_long(return_value, "drained", (zend_long) stats_drained_);
        add_assoc_long(return_value, "canceled", (zend_long) stats_canceled_);
        add_assoc_long(return_value, "rejected_full", (zend_long) stats_rejected_full_);
        add_assoc_long(return_value, "rejected_stopping", (zend_long) stats_rejected_stopping_);
        add_assoc_long(return_value, "timeouts", (zend_long) stats_timeouts_);
        add_assoc_long(return_value, "worker_crash", (zend_long) stats_worker_crash_);
        add_assoc_bool(return_value, "worker_bootstrap_failed", worker_bootstrap_failed_);
    }

    void workerMain()
    {
#if !defined(ZTS)
        return;
#else
        qt_qthreadruntime_tls_worker_request = true;
        ts_resource(0);
        TSRMLS_CACHE_UPDATE();

        if (php_request_startup() != SUCCESS) {
            std::lock_guard<std::mutex> lock(mutex_);
            worker_bootstrap_failed_ = true;
            running_ = false;
            stopping_ = true;
            return;
        }

        std::string bootstrap_script;
        {
            std::lock_guard<std::mutex> lock(mutex_);
            bootstrap_script = bootstrap_script_;
        }
        if (!bootstrap_script.empty()) {
            std::string bootstrap_error;
            if (!executeBootstrapScript(bootstrap_script, &bootstrap_error)) {
                std::lock_guard<std::mutex> lock(mutex_);
                worker_bootstrap_failed_ = true;
                running_ = false;
                stopping_ = true;
                qt_qthreadruntime_total_worker_crash.fetch_add(1, std::memory_order_acq_rel);
                qt_qthreadruntime_result failed;
                failed.ready = true;
                failed.success = false;
                failed.canceled = false;
                failed.error.class_name = "RuntimeException";
                failed.error.message = bootstrap_error.empty()
                    ? std::string("Worker bootstrap script failed.")
                    : bootstrap_error;

                while (!queue_.empty()) {
                    std::shared_ptr<qt_qthreadruntime_job> job = queue_.front();
                    queue_.pop_front();
                    if (!job) {
                        continue;
                    }
                    jobs_.erase(job->id);
                    results_[job->id] = failed;
                }
                result_cv_.notify_all();
                gc_collect_cycles();
                php_request_shutdown(NULL);
                ts_free_thread();
                qt_qthreadruntime_tls_worker_request = false;
                return;
            }
        }

        while (true) {
            std::shared_ptr<qt_qthreadruntime_job> job;
            {
                std::unique_lock<std::mutex> lock(mutex_);
                job_cv_.wait(lock, [this]() {
                    return stopping_ || !queue_.empty();
                });

                if (stopping_ && queue_.empty()) {
                    break;
                }

                job = queue_.front();
                queue_.pop_front();
            }

            if (!job) {
                continue;
            }

            qt_qthreadruntime_result result = executeJob(job);

            {
                std::lock_guard<std::mutex> lock(mutex_);
                jobs_.erase(job->id);
                result.ready = true;
                results_[job->id] = std::move(result);
                stats_drained_++;
                qt_qthreadruntime_total_drained.fetch_add(1, std::memory_order_acq_rel);
            }
            result_cv_.notify_all();
        }

        gc_collect_cycles();
        php_request_shutdown(NULL);
        ts_free_thread();
        qt_qthreadruntime_tls_worker_request = false;
#endif
    }

    static bool serializeValue(zval *value, std::string *out)
    {
        if (value == nullptr || out == nullptr) {
            return false;
        }

        zval serializer;
        zval retval;
        zval param;
        ZVAL_STRINGL(&serializer, "serialize", sizeof("serialize") - 1);
        ZVAL_COPY(&param, value);
        ZVAL_UNDEF(&retval);

        int status = call_user_function(EG(function_table), NULL, &serializer, &retval, 1, &param);
        zval_ptr_dtor(&param);
        zval_ptr_dtor(&serializer);

        if (status != SUCCESS || EG(exception) != NULL || Z_TYPE(retval) != IS_STRING) {
            if (EG(exception) != NULL) {
                zend_clear_exception();
            }
            if (!Z_ISUNDEF(retval)) {
                zval_ptr_dtor(&retval);
            }
            return false;
        }

        out->assign(Z_STRVAL(retval), Z_STRLEN(retval));
        zval_ptr_dtor(&retval);
        return true;
    }

    static bool unserializeValue(const std::string &payload, zval *out)
    {
        if (out == nullptr) {
            return false;
        }

        zval serializer;
        zval arg;
        zval retval;
        ZVAL_STRINGL(&serializer, "unserialize", sizeof("unserialize") - 1);
        ZVAL_STRINGL(&arg, payload.data(), payload.size());
        ZVAL_UNDEF(&retval);

        int status = call_user_function(EG(function_table), NULL, &serializer, &retval, 1, &arg);
        zval_ptr_dtor(&arg);
        zval_ptr_dtor(&serializer);

        if (status != SUCCESS || EG(exception) != NULL) {
            if (EG(exception) != NULL) {
                zend_clear_exception();
            }
            if (!Z_ISUNDEF(retval)) {
                zval_ptr_dtor(&retval);
            }
            return false;
        }

        ZVAL_COPY_VALUE(out, &retval);
        return true;
    }

    static qt_qthreadruntime_result makeErrorResult(std::string class_name, std::string message, zend_long code = 0, bool fatal = false)
    {
        qt_qthreadruntime_result result;
        result.success = false;
        result.canceled = false;
        result.error.class_name = std::move(class_name);
        result.error.message = std::move(message);
        result.error.code = code;
        result.error.is_fatal = fatal;
        return result;
    }

    qt_qthreadruntime_result executeJob(const std::shared_ptr<qt_qthreadruntime_job> &job)
    {
        if (job->canceled.load(std::memory_order_acquire)) {
            qt_qthreadruntime_result result;
            result.success = false;
            result.canceled = true;
            return result;
        }

        qt_qthreadruntime_result result;
        bool bailed_out = false;

        zend_first_try {
            zval args_zv;
            if (!unserializeValue(job->args_payload, &args_zv) || Z_TYPE(args_zv) != IS_ARRAY) {
                if (Z_TYPE(args_zv) != IS_UNDEF) {
                    zval_ptr_dtor(&args_zv);
                }
                return makeErrorResult("RuntimeException", "Failed to unserialize worker arguments.");
            }

            zval callable_zv;
            if (!unserializeValue(job->callable_payload, &callable_zv)) {
                zval_ptr_dtor(&args_zv);
                return makeErrorResult("RuntimeException", "Failed to unserialize worker callable.");
            }

            uint32_t argc = (uint32_t) zend_hash_num_elements(Z_ARRVAL(args_zv));
            std::vector<zval> params;
            params.reserve(argc);
            zval *entry = NULL;
            ZEND_HASH_FOREACH_VAL(Z_ARRVAL(args_zv), entry) {
                zval param;
                ZVAL_COPY(&param, entry);
                params.push_back(param);
            } ZEND_HASH_FOREACH_END();

            zval retval;
            ZVAL_UNDEF(&retval);

            zend_fcall_info fci;
            zend_fcall_info_cache fcc;
            if (zend_fcall_info_init(&callable_zv, 0, &fci, &fcc, NULL, NULL) != SUCCESS) {
                for (zval &param : params) {
                    zval_ptr_dtor(&param);
                }
                zval_ptr_dtor(&callable_zv);
                zval_ptr_dtor(&args_zv);
                return makeErrorResult("RuntimeException", "Worker callable is not invokable.");
            }

            fci.retval = &retval;
            fci.param_count = argc;
            fci.params = argc > 0 ? params.data() : NULL;

            int call_status = zend_call_function(&fci, &fcc);

            for (zval &param : params) {
                zval_ptr_dtor(&param);
            }
            zval_ptr_dtor(&callable_zv);
            zval_ptr_dtor(&args_zv);

            if (call_status != SUCCESS) {
                if (!Z_ISUNDEF(retval)) {
                    zval_ptr_dtor(&retval);
                }
                return makeErrorResult("RuntimeException", "zend_call_function() failed in worker runtime.");
            }

            if (EG(exception) != NULL) {
                zval ex_zv;
                ZVAL_OBJ_COPY(&ex_zv, EG(exception));
                zend_clear_exception();

                zend_object *ex_obj = Z_OBJ(ex_zv);
                zend_long error_code = 0;
                std::string class_name = ex_obj != NULL && ex_obj->ce != NULL
                    ? std::string(ZSTR_VAL(ex_obj->ce->name), ZSTR_LEN(ex_obj->ce->name))
                    : std::string("RuntimeException");
                std::string message = "Worker exception.";
                if (ex_obj != NULL) {
                    zval rv;
                    zval *message_prop = zend_read_property_ex(ex_obj->ce, ex_obj, ZSTR_KNOWN(ZEND_STR_MESSAGE), 1, &rv);
                    if (message_prop != NULL) {
                        zend_string *msg = zval_get_string(message_prop);
                        if (msg != NULL) {
                            message.assign(ZSTR_VAL(msg), ZSTR_LEN(msg));
                            zend_string_release(msg);
                        }
                    }

                    zval *code_prop = zend_read_property_ex(ex_obj->ce, ex_obj, ZSTR_KNOWN(ZEND_STR_CODE), 1, &rv);
                    if (code_prop != NULL) {
                        error_code = zval_get_long(code_prop);
                    }
                }

                zval_ptr_dtor(&ex_zv);
                if (!Z_ISUNDEF(retval)) {
                    zval_ptr_dtor(&retval);
                }
                return makeErrorResult(class_name, message, error_code, false);
            }

            if (!serializeValue(&retval, &result.payload)) {
                zval_ptr_dtor(&retval);
                return makeErrorResult("RuntimeException", "Failed to serialize worker result.");
            }

            zval_ptr_dtor(&retval);
            result.success = true;
            result.canceled = false;
        } zend_catch {
            bailed_out = true;
        } zend_end_try();

        if (bailed_out) {
            std::lock_guard<std::mutex> lock(mutex_);
            stats_worker_crash_++;
            qt_qthreadruntime_total_worker_crash.fetch_add(1, std::memory_order_acq_rel);
            return makeErrorResult("RuntimeException", "Worker bailed out while executing the job.", 0, true);
        }

        return result;
    }

    static bool executeBootstrapScript(const std::string &scriptPath, std::string *error)
    {
        if (scriptPath.empty()) {
            return true;
        }

        zend_file_handle file_handle;
        zend_stream_init_filename(&file_handle, scriptPath.c_str());
        zend_result rc = zend_execute_scripts(ZEND_REQUIRE, NULL, 1, &file_handle);
        if (rc == SUCCESS && EG(exception) == NULL) {
            return true;
        }

        if (error != nullptr) {
            if (EG(exception) != NULL) {
                zval ex_zv;
                ZVAL_OBJ_COPY(&ex_zv, EG(exception));
                zend_clear_exception();

                std::string message = "Worker bootstrap script threw an exception.";
                zval rv;
                zval *message_prop = zend_read_property_ex(Z_OBJCE_P(&ex_zv), Z_OBJ(ex_zv), ZSTR_KNOWN(ZEND_STR_MESSAGE), 1, &rv);
                if (message_prop != NULL) {
                    zend_string *msg = zval_get_string(message_prop);
                    if (msg != NULL) {
                        message.assign(ZSTR_VAL(msg), ZSTR_LEN(msg));
                        zend_string_release(msg);
                    }
                }
                zval_ptr_dtor(&ex_zv);
                *error = message;
            } else {
                *error = "Worker bootstrap script could not be executed.";
            }
        }

        return false;
    }

private:
    mutable std::mutex mutex_;
    std::condition_variable job_cv_;
    std::condition_variable result_cv_;
    std::deque<std::shared_ptr<qt_qthreadruntime_job>> queue_;
    std::unordered_map<uint64_t, std::shared_ptr<qt_qthreadruntime_job>> jobs_;
    std::unordered_map<uint64_t, qt_qthreadruntime_result> results_;
    std::unique_ptr<qt_qthreadruntime_worker_thread> worker_thread_;
    uint64_t next_job_id_{1};
    uint64_t stats_enqueued_{0};
    uint64_t stats_drained_{0};
    uint64_t stats_canceled_{0};
    uint64_t stats_rejected_full_{0};
    uint64_t stats_rejected_stopping_{0};
    uint64_t stats_timeouts_{0};
    uint64_t stats_worker_crash_{0};
    size_t max_queue_depth_{qt_qthreadruntime_env_queue_depth()};
    std::string bootstrap_script_;
    bool running_{false};
    bool stopping_{false};
    bool worker_bootstrap_failed_{false};
};

void qt_qthreadruntime_worker_thread::run()
{
    std::shared_ptr<qt_qthreadruntime_state> state = state_.lock();
    if (!state) {
        return;
    }

    state->workerMain();
}

static std::mutex qt_qthreadruntime_registry_mutex;
static std::vector<std::weak_ptr<qt_qthreadruntime_state>> qt_qthreadruntime_registry;

void qt_qthreadruntime_register(const std::shared_ptr<qt_qthreadruntime_state> &state)
{
    std::lock_guard<std::mutex> lock(qt_qthreadruntime_registry_mutex);
    qt_qthreadruntime_registry.erase(
        std::remove_if(
            qt_qthreadruntime_registry.begin(),
            qt_qthreadruntime_registry.end(),
            [](const std::weak_ptr<qt_qthreadruntime_state> &entry) {
                return entry.expired();
            }
        ),
        qt_qthreadruntime_registry.end()
    );
    qt_qthreadruntime_registry.emplace_back(state);
}

void qt_qthreadruntime_unregister(const std::shared_ptr<qt_qthreadruntime_state> &state)
{
    std::lock_guard<std::mutex> lock(qt_qthreadruntime_registry_mutex);
    qt_qthreadruntime_registry.erase(
        std::remove_if(
            qt_qthreadruntime_registry.begin(),
            qt_qthreadruntime_registry.end(),
            [&state](const std::weak_ptr<qt_qthreadruntime_state> &entry) {
                std::shared_ptr<qt_qthreadruntime_state> resolved = entry.lock();
                return !resolved || resolved.get() == state.get();
            }
        ),
        qt_qthreadruntime_registry.end()
    );
}

PHP_QT_API void qt_qthreadruntime_shutdown_all(zend_long timeout_ms)
{
    if (qt_qthreadruntime_tls_worker_request) {
        return;
    }

    std::vector<std::shared_ptr<qt_qthreadruntime_state>> runtimes;
    {
        std::lock_guard<std::mutex> lock(qt_qthreadruntime_registry_mutex);
        runtimes.reserve(qt_qthreadruntime_registry.size());
        for (const std::weak_ptr<qt_qthreadruntime_state> &entry : qt_qthreadruntime_registry) {
            std::shared_ptr<qt_qthreadruntime_state> runtime = entry.lock();
            if (runtime) {
                runtimes.push_back(runtime);
            }
        }
    }

    for (const std::shared_ptr<qt_qthreadruntime_state> &runtime : runtimes) {
        runtime->stop(timeout_ms);
    }
}

PHP_QT_API bool qt_qthreadruntime_is_worker_request_context(void)
{
    return qt_qthreadruntime_tls_worker_request;
}

PHP_QT_API void qt_qthreadruntime_phpinfo_rows(void)
{
    php_info_print_table_row(2, "qthreadruntime queue max depth", "4096 (default)");
    php_info_print_table_row(2, "qthreadruntime total enqueued", std::to_string(qt_qthreadruntime_total_enqueued.load(std::memory_order_acquire)).c_str());
    php_info_print_table_row(2, "qthreadruntime total drained", std::to_string(qt_qthreadruntime_total_drained.load(std::memory_order_acquire)).c_str());
    php_info_print_table_row(2, "qthreadruntime total canceled", std::to_string(qt_qthreadruntime_total_canceled.load(std::memory_order_acquire)).c_str());
    php_info_print_table_row(2, "qthreadruntime rejected (full)", std::to_string(qt_qthreadruntime_total_rejected_full.load(std::memory_order_acquire)).c_str());
    php_info_print_table_row(2, "qthreadruntime rejected (stopping)", std::to_string(qt_qthreadruntime_total_rejected_stopping.load(std::memory_order_acquire)).c_str());
    php_info_print_table_row(2, "qthreadruntime total await timeouts", std::to_string(qt_qthreadruntime_total_timeouts.load(std::memory_order_acquire)).c_str());
    php_info_print_table_row(2, "qthreadruntime worker crashes", std::to_string(qt_qthreadruntime_total_worker_crash.load(std::memory_order_acquire)).c_str());
}

static inline qt_qthreadruntime_state *qt_qthreadruntime_fetch_state(zval *zv)
{
    qt_qthreadruntime_object *intern = Z_QTHREADRUNTIME_P(zv);
    if (intern->state == NULL || intern->state->get() == NULL) {
        return NULL;
    }

    return intern->state->get();
}

static bool qt_qthreadruntime_payload_supported(zval *value)
{
    switch (Z_TYPE_P(value)) {
        case IS_RESOURCE:
            return false;
        case IS_OBJECT:
            return !instanceof_function(Z_OBJCE_P(value), zend_ce_closure);
        case IS_ARRAY: {
            zval *entry = NULL;
            ZEND_HASH_FOREACH_VAL(Z_ARRVAL_P(value), entry) {
                if (entry == NULL || !qt_qthreadruntime_payload_supported(entry)) {
                    return false;
                }
            } ZEND_HASH_FOREACH_END();
            return true;
        }
        default:
            return true;
    }
}

static bool qt_qthreadruntime_validate_callable(zval *callable, std::string *error)
{
    if (callable == NULL) {
        if (error != NULL) {
            *error = "must be a callable";
        }
        return false;
    }

    if (Z_TYPE_P(callable) == IS_STRING) {
        if (Z_STRLEN_P(callable) > 0) {
            return true;
        }
        if (error != NULL) {
            *error = "must be a non-empty callable string";
        }
        return false;
    }

    if (Z_TYPE_P(callable) != IS_ARRAY || zend_hash_num_elements(Z_ARRVAL_P(callable)) != 2) {
        if (error != NULL) {
            *error = "must be a non-empty callable string or [class-string, method-string] pair; closures/object callables are not supported yet";
        }
        return false;
    }

    zval *first = zend_hash_index_find(Z_ARRVAL_P(callable), 0);
    zval *second = zend_hash_index_find(Z_ARRVAL_P(callable), 1);
    if (first == NULL
        || second == NULL
        || Z_TYPE_P(first) != IS_STRING
        || Z_TYPE_P(second) != IS_STRING
        || Z_STRLEN_P(first) == 0
        || Z_STRLEN_P(second) == 0
    ) {
        if (error != NULL) {
            *error = "must be [class-string, non-empty method-string] when callable is an array";
        }
        return false;
    }

    zend_string *class_name = Z_STR_P(first);
    zend_class_entry *ce = zend_lookup_class_ex(class_name, NULL, ZEND_FETCH_CLASS_NO_AUTOLOAD);
    if (ce == NULL) {
        if (error != NULL) {
            *error = "class-string callable requires a loaded class in owner runtime";
        }
        return false;
    }

    zend_string *lc_method = zend_string_tolower(Z_STR_P(second));
    zend_function *fn = (zend_function *) zend_hash_find_ptr(&ce->function_table, lc_method);
    zend_string_release(lc_method);
    if (fn == NULL) {
        if (error != NULL) {
            *error = "array callable method was not found on target class";
        }
        return false;
    }

    if ((fn->common.fn_flags & ZEND_ACC_STATIC) == 0) {
        if (error != NULL) {
            *error = "array callable must reference a static method";
        }
        return false;
    }

    return true;
}

static zend_object *qt_qthreadruntime_create_object(zend_class_entry *ce)
{
    qt_qthreadruntime_object *intern = (qt_qthreadruntime_object *) zend_object_alloc(
        sizeof(qt_qthreadruntime_object), ce
    );
    std::shared_ptr<qt_qthreadruntime_state> state = std::make_shared<qt_qthreadruntime_state>();
    intern->state = new std::shared_ptr<qt_qthreadruntime_state>(state);
    qt_qthreadruntime_register(state);

    zend_object_std_init(&intern->std, ce);
    object_properties_init(&intern->std, ce);

    return &intern->std;
}

static void qt_qthreadruntime_free_object(zend_object *object)
{
    qt_qthreadruntime_object *intern = qt_qthreadruntime_from_obj(object);

    if (intern->state != NULL) {
        std::shared_ptr<qt_qthreadruntime_state> state = *intern->state;
        if (state) {
            state->stop(2000);
            qt_qthreadruntime_unregister(state);
        }
        delete intern->state;
        intern->state = NULL;
    }

    zend_object_std_dtor(&intern->std);
}

static HashTable *qt_qthreadruntime_get_gc(zend_object *object, zval **table, int *n)
{
    *table = NULL;
    *n = 0;
    return zend_std_get_properties(object);
}

PHP_METHOD(QThreadRuntime, __construct)
{
    ZEND_PARSE_PARAMETERS_NONE();
}

PHP_METHOD(QThreadRuntime, start)
{
    ZEND_PARSE_PARAMETERS_NONE();

#if !defined(ZTS)
    zend_throw_error(NULL, "Qt\\Core\\QThreadRuntime requires a ZTS PHP build.");
    RETURN_THROWS();
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        zend_throw_error(NULL, "Invalid QThreadRuntime state.");
        RETURN_THROWS();
    }

    if (!state->start()) {
        zend_throw_error(NULL, "Failed to start worker runtime.");
        RETURN_THROWS();
    }
#endif
}

PHP_METHOD(QThreadRuntime, setBootstrapScript)
{
    zend_string *path = NULL;
    ZEND_PARSE_PARAMETERS_START(0, 1)
        Z_PARAM_OPTIONAL
        Z_PARAM_STR_OR_NULL(path)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_error(NULL, "Qt\\Core\\QThreadRuntime requires a ZTS PHP build.");
    RETURN_THROWS();
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        zend_throw_error(NULL, "Invalid QThreadRuntime state.");
        RETURN_THROWS();
    }

    std::string set_error;
    std::string value = path != NULL ? std::string(ZSTR_VAL(path), ZSTR_LEN(path)) : std::string();
    if (!state->setBootstrapScript(value, &set_error)) {
        zend_throw_error(NULL, "%s", set_error.c_str());
        RETURN_THROWS();
    }
#endif
}

PHP_METHOD(QThreadRuntime, submit)
{
    zval *callable = NULL;
    zval *args = NULL;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_ZVAL(callable)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY(args)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_error(NULL, "Qt\\Core\\QThreadRuntime requires a ZTS PHP build.");
    RETURN_THROWS();
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        zend_throw_error(NULL, "Invalid QThreadRuntime state.");
        RETURN_THROWS();
    }

    std::string callable_error;
    if (!qt_qthreadruntime_validate_callable(callable, &callable_error)) {
        zend_argument_value_error(1, "%s", callable_error.c_str());
        RETURN_THROWS();
    }

    if (args != NULL && !qt_qthreadruntime_payload_supported(args)) {
        zend_argument_value_error(
            2,
            "contains unsupported values for cross-runtime transport (resources/closures are not supported)"
        );
        RETURN_THROWS();
    }

    if (!state->start()) {
        zend_throw_error(NULL, "Failed to start worker runtime.");
        RETURN_THROWS();
    }

    zval callable_input;
    ZVAL_COPY(&callable_input, callable);
    std::string callable_payload;
    if (!qt_qthreadruntime_state::serializeValue(&callable_input, &callable_payload)) {
        zval_ptr_dtor(&callable_input);
        zend_throw_error(NULL, "Failed to serialize worker callable.");
        RETURN_THROWS();
    }
    zval_ptr_dtor(&callable_input);

    zval serialized_args_input;
    if (args != NULL) {
        ZVAL_COPY(&serialized_args_input, args);
    } else {
        array_init(&serialized_args_input);
    }

    std::string args_payload;
    if (!qt_qthreadruntime_state::serializeValue(&serialized_args_input, &args_payload)) {
        zval_ptr_dtor(&serialized_args_input);
        zend_throw_error(NULL, "Failed to serialize worker arguments.");
        RETURN_THROWS();
    }
    zval_ptr_dtor(&serialized_args_input);

    uint64_t job_id = 0;
    std::string submit_error;
    if (!state->submit(
        std::move(callable_payload),
        std::move(args_payload),
        &job_id,
        &submit_error
    )) {
        zend_throw_error(NULL, "%s", submit_error.c_str());
        RETURN_THROWS();
    }

    RETURN_LONG((zend_long) job_id);
#endif
}

PHP_METHOD(QThreadRuntime, await)
{
    zend_long job_id = 0;
    zend_long timeout_ms = 0;

    ZEND_PARSE_PARAMETERS_START(1, 2)
        Z_PARAM_LONG(job_id)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout_ms)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    zend_throw_error(NULL, "Qt\\Core\\QThreadRuntime requires a ZTS PHP build.");
    RETURN_THROWS();
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        zend_throw_error(NULL, "Invalid QThreadRuntime state.");
        RETURN_THROWS();
    }

    qt_qthreadruntime_result result;
    qt_qthreadruntime_await_status status = state->await((uint64_t) job_id, timeout_ms, &result);
    if (status == qt_qthreadruntime_await_status::timeout) {
        RETURN_NULL();
    }
    if (status == qt_qthreadruntime_await_status::unknown) {
        zend_throw_error(NULL, "Unknown job id %" ZEND_LONG_FMT ".", job_id);
        RETURN_THROWS();
    }

    if (result.canceled) {
        RETURN_FALSE;
    }

    if (!result.success) {
        zend_class_entry *exception_ce = zend_exception_get_default();
        if (!result.error.class_name.empty()) {
            zend_string *class_name = zend_string_init(result.error.class_name.c_str(), result.error.class_name.size(), 0);
            zend_class_entry *resolved_ce = zend_lookup_class_ex(class_name, NULL, 0);
            zend_string_release(class_name);
            if (resolved_ce != NULL && instanceof_function(resolved_ce, zend_ce_throwable)) {
                exception_ce = resolved_ce;
            }
        }

        const std::string &message = result.error.message.empty()
            ? std::string("Worker runtime execution failed.")
            : result.error.message;
        zend_throw_exception(exception_ce, message.c_str(), result.error.code);
        RETURN_THROWS();
    }

    zval payload;
    if (!qt_qthreadruntime_state::unserializeValue(result.payload, &payload)) {
        zend_throw_error(NULL, "Failed to unserialize worker result payload.");
        RETURN_THROWS();
    }

    ZVAL_COPY_VALUE(return_value, &payload);
#endif
}

PHP_METHOD(QThreadRuntime, cancel)
{
    zend_long job_id = 0;
    ZEND_PARSE_PARAMETERS_START(1, 1)
        Z_PARAM_LONG(job_id)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    RETURN_FALSE;
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        RETURN_FALSE;
    }

    RETURN_BOOL(state->cancel((uint64_t) job_id));
#endif
}

PHP_METHOD(QThreadRuntime, stop)
{
    zend_long timeout_ms = 5000;
    ZEND_PARSE_PARAMETERS_START(0, 1)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(timeout_ms)
    ZEND_PARSE_PARAMETERS_END();

#if !defined(ZTS)
    RETURN_FALSE;
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        RETURN_FALSE;
    }

    RETURN_BOOL(state->stop(timeout_ms));
#endif
}

PHP_METHOD(QThreadRuntime, isRunning)
{
    ZEND_PARSE_PARAMETERS_NONE();

#if !defined(ZTS)
    RETURN_FALSE;
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        RETURN_FALSE;
    }

    RETURN_BOOL(state->isRunning());
#endif
}

PHP_METHOD(QThreadRuntime, stats)
{
    ZEND_PARSE_PARAMETERS_NONE();

#if !defined(ZTS)
    array_init(return_value);
    add_assoc_bool(return_value, "running", false);
#else
    qt_qthreadruntime_state *state = qt_qthreadruntime_fetch_state(ZEND_THIS);
    if (state == NULL) {
        array_init(return_value);
        add_assoc_bool(return_value, "running", false);
        return;
    }

    state->fillStats(return_value);
#endif
}

static const zend_function_entry qt_qthreadruntime_methods[] = {
    ZEND_ME(QThreadRuntime, __construct, arginfo_class_Qt_Core_QThreadRuntime___construct, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, setBootstrapScript, arginfo_class_Qt_Core_QThreadRuntime_setBootstrapScript, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, start, arginfo_class_Qt_Core_QThreadRuntime_start, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, submit, arginfo_class_Qt_Core_QThreadRuntime_submit, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, await, arginfo_class_Qt_Core_QThreadRuntime_await, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, cancel, arginfo_class_Qt_Core_QThreadRuntime_cancel, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, stop, arginfo_class_Qt_Core_QThreadRuntime_stop, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, isRunning, arginfo_class_Qt_Core_QThreadRuntime_isRunning, ZEND_ACC_PUBLIC)
    ZEND_ME(QThreadRuntime, stats, arginfo_class_Qt_Core_QThreadRuntime_stats, ZEND_ACC_PUBLIC)
    ZEND_FE_END
};

PHP_MINIT_FUNCTION(qt_qthreadruntime)
{
    zend_class_entry ce;
    INIT_NS_CLASS_ENTRY(ce, "Qt\\Core", "QThreadRuntime", qt_qthreadruntime_methods);
    ce.create_object = qt_qthreadruntime_create_object;

    qt_ce_QThreadRuntime = zend_register_internal_class(&ce);
    qt_ce_QThreadRuntime->ce_flags |= ZEND_ACC_FINAL;

    memcpy(&qt_qthreadruntime_handlers, &std_object_handlers, sizeof(zend_object_handlers));
    qt_qthreadruntime_handlers.offset = XtOffsetOf(qt_qthreadruntime_object, std);
    qt_qthreadruntime_handlers.free_obj = qt_qthreadruntime_free_object;
    qt_qthreadruntime_handlers.clone_obj = NULL;
    qt_qthreadruntime_handlers.get_gc = qt_qthreadruntime_get_gc;
    qt_ce_QThreadRuntime->default_object_handlers = &qt_qthreadruntime_handlers;

    return SUCCESS;
}
