/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Isolated PHP worker runtime support for Qt\Core\QThreadRuntime.
 */

#ifndef QT_QTHREADRUNTIME_H
#define QT_QTHREADRUNTIME_H

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#ifdef __cplusplus
}
#endif
#include "qt_php_compat.h"
#include <cstdint>
#include <memory>
#include <string>

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

class qt_qthreadruntime_state;
struct qt_qfuture_continuation_state;
struct qt_qthread_task_host;
class QThread;

typedef struct _qt_qthreadruntime_object {
    std::shared_ptr<qt_qthreadruntime_state> *state;
    zend_object std; /* MUST be last */
} qt_qthreadruntime_object;

extern PHP_QT_API zend_class_entry *qt_ce_QThreadRuntime;
extern PHP_QT_API zend_class_entry *qt_ce_QFuture;
extern PHP_QT_API zend_class_entry *qt_ce_QPromise;
extern zend_object_handlers qt_qthreadruntime_handlers;
extern zend_object_handlers qt_qfuture_handlers;
extern zend_object_handlers qt_qpromise_handlers;

static inline qt_qthreadruntime_object *qt_qthreadruntime_from_obj(zend_object *obj)
{
    return (qt_qthreadruntime_object *)((char *)(obj) - XtOffsetOf(qt_qthreadruntime_object, std));
}

#define Z_QTHREADRUNTIME_P(zv) qt_qthreadruntime_from_obj(Z_OBJ_P(zv))

typedef struct _qt_qfuture_object {
    qt_qthread_task_host *host;
    uint64_t task_token;
    qt_qfuture_continuation_state *continuation;
    zend_object std; /* MUST be last */
} qt_qfuture_object;

static inline qt_qfuture_object *qt_qfuture_from_obj(zend_object *obj)
{
    return (qt_qfuture_object *)((char *)(obj) - XtOffsetOf(qt_qfuture_object, std));
}

#define Z_QFUTURE_P(zv) qt_qfuture_from_obj(Z_OBJ_P(zv))

typedef struct _qt_qpromise_object {
    bool worker_context_only;
    zend_object std; /* MUST be last */
} qt_qpromise_object;

static inline qt_qpromise_object *qt_qpromise_from_obj(zend_object *obj)
{
    return (qt_qpromise_object *)((char *)(obj) - XtOffsetOf(qt_qpromise_object, std));
}

#define Z_QPROMISE_P(zv) qt_qpromise_from_obj(Z_OBJ_P(zv))

PHP_MINIT_FUNCTION(qt_qthreadruntime);
PHP_MINIT_FUNCTION(qt_qfuture);
PHP_MINIT_FUNCTION(qt_qpromise);
PHP_QT_API void qt_qthreadruntime_shutdown_all(zend_long timeout_ms);
PHP_QT_API bool qt_qthreadruntime_is_worker_request_context(void);
PHP_QT_API void qt_qthreadruntime_restore_sapi_deactivate(void);
PHP_QT_API void qt_qthreadruntime_phpinfo_rows(void);
PHP_QT_API bool qt_qthreadruntime_payload_supported_for_worker(zval *value);
PHP_QT_API bool qt_qthreadruntime_worker_publish_zval(zend_string *event_name, zval *payload, std::string *error);
PHP_QT_API bool qt_qthreadruntime_worker_receive_zval(zend_long timeout_ms, zval *return_value, bool *has_message, std::string *error);
PHP_QT_API bool qt_qthreadruntime_validate_callable_string(zend_string *callable, std::string *error);
PHP_QT_API bool qt_qthreadruntime_serialize_worker_args(zval *args, std::string *out_payload, std::string *error);
PHP_QT_API bool qt_qthreadruntime_set_thread_interrupted(bool interrupted);
PHP_QT_API bool qt_qthreadruntime_current_task_context(qt_qthread_task_host **host, uint64_t *task_token);
PHP_QT_API bool qt_qthreadruntime_worker_is_canceled(void);
PHP_QT_API bool qt_qthreadruntime_worker_publish_progress(zend_long value, zend_long minimum, zend_long maximum, zend_string *text, std::string *error);
PHP_QT_API void qt_qfuture_wrap(zval *return_value, qt_qthread_task_host *host, uint64_t task_token);

PHP_QT_API qt_qthread_task_host *qt_qthread_task_host_create(void);
PHP_QT_API void qt_qthread_task_host_destroy(qt_qthread_task_host *host);
PHP_QT_API void qt_qthread_task_host_retain(qt_qthread_task_host *host);
PHP_QT_API void qt_qthread_task_host_release(qt_qthread_task_host *host);
PHP_QT_API bool qt_qthread_task_host_set_bootstrap_script(qt_qthread_task_host *host, const std::string &path, std::string *error);
PHP_QT_API bool qt_qthread_task_host_start(qt_qthread_task_host *host, QThread *thread, const std::string &callable_name, const std::string &args_payload, bool has_priority, int priority, std::string *error);
PHP_QT_API bool qt_qthread_task_host_start_future(qt_qthread_task_host *host, QThread *thread, const std::string &callable_name, const std::string &args_payload, bool has_priority, int priority, uint64_t *task_token, std::string *error);
PHP_QT_API bool qt_qthread_task_host_on(qt_qthread_task_host *host, const std::string &event_name, zval *listener, uint64_t *listener_id, std::string *error);
PHP_QT_API bool qt_qthread_task_host_on_for_token(qt_qthread_task_host *host, uint64_t task_token, const std::string &event_name, zval *listener, uint64_t *listener_id, std::string *error);
PHP_QT_API bool qt_qthread_task_host_off(qt_qthread_task_host *host, uint64_t listener_id);
PHP_QT_API zend_long qt_qthread_task_host_drain_events(qt_qthread_task_host *host, zend_long max_items);
PHP_QT_API bool qt_qthread_task_host_send(qt_qthread_task_host *host, const std::string &event_name, zval *payload, std::string *error);
PHP_QT_API bool qt_qthread_task_host_on_owner_interruption_request(qt_qthread_task_host *host);
PHP_QT_API bool qt_qthread_task_host_is_task_running(qt_qthread_task_host *host);
PHP_QT_API bool qt_qthread_task_host_execute_pending(qt_qthread_task_host *host, QThread *thread);
PHP_QT_API bool qt_qthread_task_host_future_is_valid(qt_qthread_task_host *host, uint64_t task_token);
PHP_QT_API bool qt_qthread_task_host_future_is_running(qt_qthread_task_host *host, uint64_t task_token);
PHP_QT_API bool qt_qthread_task_host_future_is_finished(qt_qthread_task_host *host, uint64_t task_token);
PHP_QT_API bool qt_qthread_task_host_future_is_canceled(qt_qthread_task_host *host, uint64_t task_token);
PHP_QT_API bool qt_qthread_task_host_future_cancel(qt_qthread_task_host *host, uint64_t task_token);
PHP_QT_API bool qt_qthread_task_host_future_wait(qt_qthread_task_host *host, uint64_t task_token, zend_long timeout_ms, bool *finished);
PHP_QT_API bool qt_qthread_task_host_future_result(qt_qthread_task_host *host, uint64_t task_token, zend_long timeout_ms, zval *return_value, bool *timed_out, bool *canceled, std::string *error_class, std::string *error_message, zend_long *error_code, std::string *internal_error);

#endif /* QT_QTHREADRUNTIME_H */
