/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Internal attribute support for Qt\Core\Attributes\Signal.
 */

#ifndef QT_SIGNALATTRIBUTE_H
#define QT_SIGNALATTRIBUTE_H

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include "php.h"
#ifdef __cplusplus
}
#endif
#include "qt_php_compat.h"

#ifndef PHP_QT_API
# if defined(PHP_WIN32)
#  define PHP_QT_API __declspec(dllexport)
# elif defined(__GNUC__) && __GNUC__ >= 4
#  define PHP_QT_API __attribute__ ((visibility("default")))
# else
#  define PHP_QT_API
# endif
#endif

extern PHP_QT_API zend_class_entry *qt_ce_SignalAttribute;

PHP_MINIT_FUNCTION(qt_signalattribute);

#endif /* QT_SIGNALATTRIBUTE_H */
