/**
 * Auto-generated by phpqt-builder -- DO NOT EDIT.
 *
 * Shared signal callback helpers for generated Qt wrapper classes.
 */

#ifndef QT_SIGNAL_HELPERS_H
#define QT_SIGNAL_HELPERS_H

#include "qt_class_helpers.h"
#include <QObject>
#include <memory>

struct qt_signal_callback_t {
    zend_fcall_info fci;
    zend_fcall_info_cache fci_cache;
};

template <typename InvokeCallback>
static inline bool qt_signal_dispatch(InvokeCallback invoke)
{
    if (qt_runtime_can_call_zend()) {
        invoke();
        return true;
    }

    return qt_runtime_enqueue_owner_task([invoke]() mutable {
        if (qt_runtime_can_call_zend()) {
            invoke();
        }
    });
}

static inline void qt_signal_callback_clear(const std::shared_ptr<qt_signal_callback_t> &callback)
{
    if (!callback) {
        return;
    }

    if (!qt_runtime_can_call_zend()) {
        return;
    }

    callback->fci.params = NULL;
    callback->fci.param_count = 0;
    callback->fci.retval = NULL;
    if (!Z_ISUNDEF(callback->fci.function_name)) {
        zval_ptr_dtor(&callback->fci.function_name);
        ZVAL_UNDEF(&callback->fci.function_name);
    }
}

static inline std::shared_ptr<qt_signal_callback_t> qt_signal_callback_create(const QObject *sender, zval *callback)
{
    auto handle = std::make_shared<qt_signal_callback_t>();
    memset(&handle->fci, 0, sizeof(handle->fci));
    memset(&handle->fci_cache, 0, sizeof(handle->fci_cache));
    ZVAL_UNDEF(&handle->fci.function_name);

    char *error = NULL;
    if (zend_fcall_info_init(callback, 0, &handle->fci, &handle->fci_cache, NULL, &error) != SUCCESS) {
        if (error != NULL) {
            zend_throw_exception_ex(zend_ce_type_error, 0, "Invalid signal callback: %s", error);
            efree(error);
        } else {
            zend_throw_exception_ex(zend_ce_type_error, 0, "Invalid signal callback.");
        }
        return nullptr;
    }

    Z_TRY_ADDREF(handle->fci.function_name);

    if (sender != NULL) {
        QObject::connect(sender, &QObject::destroyed, [handle]() {
            auto _qt_handle = handle;
            qt_signal_dispatch([_qt_handle]() mutable {
                qt_signal_callback_clear(_qt_handle);
            });
        });
    }

    return handle;
}

static inline bool qt_signal_callback_invoke(const std::shared_ptr<qt_signal_callback_t> &callback, uint32_t param_count, zval *params)
{
    if (!callback || !qt_runtime_can_call_zend()) {
        return false;
    }

    if (qt_runtime_is_shutdown_in_progress()) {
        return false;
    }

    zval retval;
    ZVAL_NULL(&retval);

    zval *previousRetval = callback->fci.retval;
    zval *previousParams = callback->fci.params;
    uint32_t previousParamCount = callback->fci.param_count;

    callback->fci.retval = &retval;
    callback->fci.params = params;
    callback->fci.param_count = param_count;

    bool ok = zend_call_function(&callback->fci, &callback->fci_cache) == SUCCESS;
    callback->fci.retval = previousRetval;
    callback->fci.params = previousParams;
    callback->fci.param_count = previousParamCount;
    zval_ptr_dtor(&retval);

    return ok;
}

#endif /* QT_SIGNAL_HELPERS_H */
