/**
 * Auto-generated by phpqt-builder — DO NOT EDIT.
 *
 * Internal attribute support for Qt\Core\Attributes\Signal.
 */

#include "qt_signalattribute.h"
#include "qt_signalattribute_arginfo.h"
#include "zend_attributes.h"

zend_class_entry *qt_ce_SignalAttribute = NULL;

ZEND_METHOD(Qt_Core_Attributes_Signal, __construct)
{
    zval *types = NULL;

    ZEND_PARSE_PARAMETERS_START(0, 1)
        Z_PARAM_OPTIONAL
        Z_PARAM_ARRAY(types)
    ZEND_PARSE_PARAMETERS_END();

    (void) types;
}

static const zend_function_entry qt_signalattribute_methods[] = {
    ZEND_ME(Qt_Core_Attributes_Signal, __construct, arginfo_class_Qt_Core_Attributes_Signal___construct, ZEND_ACC_PUBLIC)
    ZEND_FE_END
};

PHP_MINIT_FUNCTION(qt_signalattribute)
{
    zend_class_entry ce;
    INIT_NS_CLASS_ENTRY(ce, "Qt\\Core\\Attributes", "Signal", qt_signalattribute_methods);
#if (PHP_VERSION_ID >= 80400)
    qt_ce_SignalAttribute = zend_register_internal_class_with_flags(&ce, NULL, ZEND_ACC_FINAL);
#else
    qt_ce_SignalAttribute = zend_register_internal_class_ex(&ce, NULL);
    qt_ce_SignalAttribute->ce_flags |= ZEND_ACC_FINAL;
#endif

    zend_string *attribute_name = zend_string_init_interned("Attribute", sizeof("Attribute") - 1, 1);
    zend_attribute *attribute = zend_add_class_attribute(qt_ce_SignalAttribute, attribute_name, 1);
    zend_string_release(attribute_name);
    zval attribute_arg;
    ZVAL_LONG(&attribute_arg, ZEND_ATTRIBUTE_TARGET_METHOD);
    ZVAL_COPY_VALUE(&attribute->args[0].value, &attribute_arg);

    zend_mark_internal_attribute(qt_ce_SignalAttribute);

    return SUCCESS;
}
