/**
 * Auto-generated by phpqt-builder -- DO NOT EDIT.
 *
 * Shared signal callback helpers for generated Qt wrapper classes.
 */

#ifndef QT_SIGNAL_HELPERS_H
#define QT_SIGNAL_HELPERS_H

#include "qt_class_helpers.h"
#include <QObject>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <memory>

struct qt_signal_callback_t {
    zend_fcall_info fci;
    zend_fcall_info_cache fci_cache;
    zend_ulong owner_thread_id;
    bool owner_owner_queue_supported;
};

static inline zend_ulong qt_signal_current_thread_id()
{
#if defined(ZTS)
    if (!tsrm_is_managed_thread()) {
        return 0;
    }

    return (zend_ulong) (uintptr_t) tsrm_thread_id();
#else
    return 1;
#endif
}

static inline bool qt_signal_debug_enabled()
{
    static int enabled = -1;
    if (enabled >= 0) {
        return enabled == 1;
    }

    const char *raw = getenv("QT_SIGNAL_DEBUG");
    enabled = (raw != NULL && *raw != '\0' && strcmp(raw, "0") != 0) ? 1 : 0;
    return enabled == 1;
}

static inline void qt_signal_debug_log(const char *message, zend_ulong owner_thread_id)
{
    if (!qt_signal_debug_enabled() || message == NULL) {
        return;
    }

    fprintf(
        stderr,
        "[qt-signal] %s owner=%lu current=%lu can_call=%d owner_thread=%d\n",
        message,
        (unsigned long) owner_thread_id,
        (unsigned long) qt_signal_current_thread_id(),
        qt_runtime_can_call_zend() ? 1 : 0,
        qt_runtime_is_owner_thread() ? 1 : 0
    );
}

static inline bool qt_signal_callback_is_owner_thread(const std::shared_ptr<qt_signal_callback_t> &callback)
{
    if (!callback) {
        return false;
    }

#if defined(ZTS)
    return callback->owner_thread_id != 0 && qt_signal_current_thread_id() == callback->owner_thread_id;
#else
    return true;
#endif
}

template <typename InvokeCallback>
static inline bool qt_signal_dispatch(const std::shared_ptr<qt_signal_callback_t> &callback, InvokeCallback invoke)
{
    if (!callback) {
        return false;
    }

    if (qt_signal_callback_is_owner_thread(callback) && qt_runtime_can_call_zend()) {
        qt_signal_debug_log("dispatch-direct", callback->owner_thread_id);
        invoke();
        return true;
    }

    if (!callback->owner_owner_queue_supported) {
        qt_signal_debug_log("dispatch-drop-no-owner-queue", callback->owner_thread_id);
        return false;
    }

    qt_signal_debug_log("dispatch-enqueue-owner", callback->owner_thread_id);
    return qt_runtime_enqueue_owner_task([callback, invoke]() mutable {
        qt_signal_debug_log("dispatch-owner-task", callback->owner_thread_id);
        if (qt_signal_callback_is_owner_thread(callback) && qt_runtime_can_call_zend()) {
            invoke();
        }
    });
}

static inline void qt_signal_callback_clear(const std::shared_ptr<qt_signal_callback_t> &callback)
{
    if (!callback) {
        return;
    }

    if (!qt_signal_callback_is_owner_thread(callback) || !qt_runtime_can_call_zend()) {
        return;
    }

    callback->fci.params = NULL;
    callback->fci.param_count = 0;
    callback->fci.retval = NULL;
    if (!Z_ISUNDEF(callback->fci.function_name)) {
        zval_ptr_dtor(&callback->fci.function_name);
        ZVAL_UNDEF(&callback->fci.function_name);
    }
}

static inline std::shared_ptr<qt_signal_callback_t> qt_signal_callback_create(const QObject *sender, zval *callback)
{
    auto handle = std::make_shared<qt_signal_callback_t>();
    memset(&handle->fci, 0, sizeof(handle->fci));
    memset(&handle->fci_cache, 0, sizeof(handle->fci_cache));
    ZVAL_UNDEF(&handle->fci.function_name);
    handle->owner_thread_id = qt_signal_current_thread_id();
    handle->owner_owner_queue_supported = qt_runtime_is_owner_thread();
    qt_signal_debug_log("callback-create", handle->owner_thread_id);

    char *error = NULL;
    if (zend_fcall_info_init(callback, 0, &handle->fci, &handle->fci_cache, NULL, &error) != SUCCESS) {
        if (error != NULL) {
            zend_throw_exception_ex(zend_ce_type_error, 0, "Invalid signal callback: %s", error);
            efree(error);
        } else {
            zend_throw_exception_ex(zend_ce_type_error, 0, "Invalid signal callback.");
        }
        return nullptr;
    }

    Z_TRY_ADDREF(handle->fci.function_name);

    if (sender != NULL) {
        QObject::connect(sender, &QObject::destroyed, [handle]() {
            auto _qt_handle = handle;
            qt_signal_dispatch(_qt_handle, [_qt_handle]() mutable {
                qt_signal_callback_clear(_qt_handle);
            });
        });
    }

    return handle;
}

static inline bool qt_signal_callback_invoke(const std::shared_ptr<qt_signal_callback_t> &callback, uint32_t param_count, zval *params)
{
    if (!callback || !qt_signal_callback_is_owner_thread(callback) || !qt_runtime_can_call_zend()) {
        if (callback) {
            qt_signal_debug_log("invoke-rejected", callback->owner_thread_id);
        }
        return false;
    }

    if (qt_runtime_is_shutdown_in_progress()) {
        return false;
    }

    zval retval;
    ZVAL_NULL(&retval);

    zval *previousRetval = callback->fci.retval;
    zval *previousParams = callback->fci.params;
    uint32_t previousParamCount = callback->fci.param_count;

    callback->fci.retval = &retval;
    callback->fci.params = params;
    callback->fci.param_count = param_count;

    bool ok = zend_call_function(&callback->fci, &callback->fci_cache) == SUCCESS;
    qt_signal_debug_log(ok ? "invoke-success" : "invoke-failure", callback->owner_thread_id);
    callback->fci.retval = previousRetval;
    callback->fci.params = previousParams;
    callback->fci.param_count = previousParamCount;
    zval_ptr_dtor(&retval);

    return ok;
}

#endif /* QT_SIGNAL_HELPERS_H */
